import type { FieldType, PageBlockType } from '../types'

export type CreativeBlock = { type: PageBlockType; config: Record<string, unknown> }
export type SectionPreset = { id:string; name:string; category:string; icon:string; description:string; width:number; height:number; blocks:CreativeBlock[] }
export type StylePack = { id:string; name:string; icon:string; description:string; page:{background:string;textColor:string}; fontFamily:string; headingFont:string; primary:string; secondary:string; surface:string; surfaceAlt:string; border:string; accent:string; dark:string }
export type DataKitCollection = { name:string; fields:Array<{name:string;type:FieldType}> }
export type DataKit = { id:string; name:string; icon:string; description:string; collections:DataKitCollection[] }

const heading=(text:string,x:number,y:number,width=300,size=25,color='#2b2722'):CreativeBlock=>({type:'heading',config:{text,x,y,width,height:50,zIndex:12,background:'transparent',textColor:color,fontSize:size,fontWeight:600,fontFamily:'Georgia, serif',lineHeight:1.1,textAlign:'left'}})
const copy=(text:string,x:number,y:number,width=340,height=70,color='#74695f'):CreativeBlock=>({type:'text',config:{text,x,y,width,height,zIndex:10,background:'transparent',textColor:color,fontSize:14,fontWeight:400,fontFamily:'Georgia, serif',lineHeight:1.45,textAlign:'left'}})
const widget=(widgetType:string,x:number,y:number,width:number,height:number,config:Record<string,unknown>={}):CreativeBlock=>({type:'widget',config:{widgetType,x,y,width,height,zIndex:11,background:'transparent',textColor:'#2b2722',primaryColor:'#2b2722',secondaryColor:'#74695f',accentColor:'#665477',surfaceColor:'#ffffff',borderColor:'#ded4c7',widgetBorderWidth:1,widgetRadius:18,widgetPadding:16,radius:0,padding:0,fontFamily:'Georgia, serif',fontSize:15,...config}})
const databaseView=(x:number,y:number,width:number,height:number,mode='gallery'):CreativeBlock=>({type:'database_view',config:{databaseId:'$database',mode,recordLayoutMode:'auto',title:'',limit:8,x,y,width,height,zIndex:8,background:'transparent',textColor:'#2b2722',radius:0,padding:0}})
const list=(rows:string[])=>rows.map((text,index)=>({id:`preset-${index+1}`,text,done:false}))

export const SECTION_PRESETS:SectionPreset[]=[
  {id:'daily-magic',name:'Daily Magic',category:'Witchy',icon:'☾',description:'Moon, intention, and a small ritual checklist.',width:860,height:330,blocks:[heading('Daily magic',0,0,280,27,'#49384f'),widget('moon_phase',0,62,240,145,{surfaceColor:'#2f2833',primaryColor:'#fff6ec',secondaryColor:'#cbbdd0',borderColor:'#504457'}),widget('daily_focus',265,62,310,145,{label:'INTENTION',text:'What matters most today?',surfaceColor:'#fffaf3',borderColor:'#d6c7d8'}),widget('checklist',600,62,260,215,{label:'Practice',items:list(['Ground and check in','Tend altar or offering','Choose one practice']),surfaceColor:'#f7f2eb',borderColor:'#d9cfc5'})]},
  {id:'money-snapshot',name:'Money Snapshot',category:'Budget',icon:'$',description:'A compact spending, savings, and quick-capture section.',width:900,height:330,blocks:[heading('Money snapshot',0,0,310,27,'#395044'),widget('goal',0,62,280,145,{label:'Monthly spending',value:0,max:2500,accentColor:'#8a6b50',surfaceColor:'#fbfaf6',borderColor:'#d5dad3'}),widget('goal',305,62,280,145,{label:'Savings goal',value:0,max:5000,accentColor:'#5b7565',surfaceColor:'#e5ece6',borderColor:'#c6d2c9'}),widget('quick_capture',610,62,290,85,{databaseId:'$database',placeholder:'Log an expense…',surfaceColor:'#fbfaf6',borderColor:'#d5dad3'}),widget('recent_records',610,165,290,130,{label:'Recent activity',databaseId:'$database',limit:4,surfaceColor:'#f2f5f0',borderColor:'#d3d9d2'})]},
  {id:'currently-reading',name:'Currently Reading',category:'Books',icon:'📖',description:'Reading goal, random next pick, and a compact shelf.',width:900,height:390,blocks:[heading('Reading life',0,0,300,27,'#5a4035'),widget('goal',0,62,300,145,{label:'Reading goal',dataMode:'database',aggregate:'count',max:50,databaseId:'$database',accentColor:'#925f52',surfaceColor:'#fffaf3',borderColor:'#dfcfc0'}),widget('random_record',325,62,250,145,{label:'Pick my next read',databaseId:'$database',surfaceColor:'#dac9d0',borderColor:'#c3abb4'}),widget('sticky_note',600,62,300,145,{label:'READING MOOD',text:'What kind of story are you craving?',surfaceColor:'#e7d2af',borderColor:'#cfb486'}),databaseView(0,235,900,155,'gallery')]},
  {id:'podcast-next',name:'Podcast Next Episode',category:'Podcast',icon:'◉',description:'Next actions, idea capture, and recent episode activity.',width:900,height:360,blocks:[heading('Next episode',0,0,300,27,'#403a35'),widget('todo',0,62,310,235,{label:'Production steps',items:list(['Outline episode','Record','Edit','Write show notes','Schedule release']),surfaceColor:'#fbfaf6',borderColor:'#d8d1c8'}),widget('quick_capture',335,62,300,90,{databaseId:'$database',placeholder:'Capture an episode idea…',surfaceColor:'#f2ece3',borderColor:'#d7cabb'}),widget('recent_records',335,172,565,125,{label:'Recent episodes',databaseId:'$database',limit:5,surfaceColor:'#ffffff',borderColor:'#ddd5cb'})]},
  {id:'weekly-reset',name:'Weekly Reset',category:'Productivity',icon:'✓',description:'A focus statement, next actions, and an upcoming list.',width:900,height:330,blocks:[heading('Weekly reset',0,0,300,27,'#3c3b35'),widget('daily_focus',0,62,360,150,{label:'THIS WEEK',text:'What would make this week feel meaningful?',surfaceColor:'#fffdf8',borderColor:'#dad5cc'}),widget('todo',385,62,250,215,{label:'Next actions',items:list(['Choose top three priorities','Clear one lingering task','Schedule focused time']),surfaceColor:'#f2efe8',borderColor:'#d8d1c5'}),widget('upcoming',660,62,240,215,{label:'Upcoming',databaseId:'$database',limit:5,surfaceColor:'#e8ece8',borderColor:'#cdd5cd'})]},
  {id:'travel-countdown',name:'Travel Countdown',category:'Travel',icon:'✈',description:'Trip countdown, packing list, and itinerary preview.',width:900,height:360,blocks:[heading('Next adventure',0,0,300,27,'#355247'),widget('countdown',0,62,270,160,{label:'Trip countdown',surfaceColor:'#e1ebe5',accentColor:'#517365',borderColor:'#c6d7cd'}),widget('checklist',295,62,270,235,{label:'Packing',items:list(['Documents','Chargers','Comfort items','Last-minute essentials']),surfaceColor:'#fbfaf6',borderColor:'#d9d6ce'}),widget('timeline',590,62,310,235,{label:'Itinerary',databaseId:'$database',limit:6,surfaceColor:'#edf2ef',borderColor:'#ced9d2'})]},
  {id:'creative-scraps',name:'Creative Scraps',category:'Boards',icon:'◇',description:'Loose notes and prompts for a Milanote-style working area.',width:900,height:390,blocks:[heading('Creative scraps',0,0,310,27,'#4b433c'),widget('sticky_note',0,62,275,190,{label:'IDEA',text:'Something worth remembering…',surfaceColor:'#ecd9a8',borderColor:'#d7bd7d',widgetRadius:12}),widget('sticky_note',305,95,275,190,{label:'QUESTION',text:'What are you still trying to figure out?',surfaceColor:'#d8d0df',borderColor:'#beb1c7',widgetRadius:12}),widget('quote',610,62,290,150,{text:'Collect first. Decide what it means later.',author:'Working note',surfaceColor:'#3d3935',primaryColor:'#fff8ef',secondaryColor:'#d7cdc2',borderColor:'#3d3935'}),copy('Use this as a loose visual cluster. Move, overlap, duplicate, and replace anything.',610,235,290,75,'#756c64')]},
  {id:'writing-sprint',name:'Writing Sprint',category:'Writing',icon:'✎',description:'Focus, timer, word-count goal, and quick notes.',width:900,height:330,blocks:[heading('Writing sprint',0,0,300,27,'#493f45'),widget('daily_focus',0,62,310,145,{label:'SCENE / FOCUS',text:'What are you writing right now?',surfaceColor:'#fffaf4',borderColor:'#ddcfc5'}),widget('pomodoro',335,62,230,145,{label:'Focus timer',surfaceColor:'#302b31',primaryColor:'#fff7ed',secondaryColor:'#c8bac5',borderColor:'#4e454f'}),widget('goal',590,62,310,145,{label:'Words',value:0,max:1500,accentColor:'#785d73',surfaceColor:'#eee5eb',borderColor:'#d0c0ca'}),widget('sticky_note',335,225,565,90,{label:'SCRAPS',text:'Line, image, question, or thing to fix later…',surfaceColor:'#e5d8c9',borderColor:'#cfbfae'})]},
]

export const STYLE_PACKS:StylePack[]=[
  {id:'soft-editorial',name:'Soft Editorial',icon:'◌',description:'Warm paper, restrained contrast, elegant serif type.',page:{background:'#f5f0e8',textColor:'#2b2621'},fontFamily:'Georgia, serif',headingFont:'Georgia, serif',primary:'#2b2621',secondary:'#796e64',surface:'#fffaf3',surfaceAlt:'#e9dfd2',border:'#d8ccbd',accent:'#8a685d',dark:'#403630'},
  {id:'midnight-luxe',name:'Midnight Luxe',icon:'✦',description:'Ink-dark surfaces, soft ivory type, plum accents.',page:{background:'#17151b',textColor:'#f7efe7'},fontFamily:'Georgia, serif',headingFont:'Georgia, serif',primary:'#f7efe7',secondary:'#c0b2c5',surface:'#25212a',surfaceAlt:'#302837',border:'#493e50',accent:'#ad8ab5',dark:'#111015'},
  {id:'botanical',name:'Botanical',icon:'❧',description:'Moss, parchment, cream, and soft organic contrast.',page:{background:'#eef0e8',textColor:'#253128'},fontFamily:'Georgia, serif',headingFont:'Georgia, serif',primary:'#253128',secondary:'#68756b',surface:'#faf8f1',surfaceAlt:'#dfe6dc',border:'#c8d0c5',accent:'#58715f',dark:'#35443a'},
  {id:'dark-academia',name:'Dark Academia',icon:'◆',description:'Old paper, espresso, oxblood, and library warmth.',page:{background:'#e9dfce',textColor:'#30261f'},fontFamily:'Georgia, serif',headingFont:'Georgia, serif',primary:'#30261f',secondary:'#756458',surface:'#f7efe2',surfaceAlt:'#d8c6ae',border:'#c5ad91',accent:'#754b43',dark:'#3c2e28'},
  {id:'paper-ink',name:'Paper & Ink',icon:'□',description:'High-contrast monochrome with a tactile notebook feel.',page:{background:'#f6f4ef',textColor:'#242321'},fontFamily:'Georgia, serif',headingFont:'Georgia, serif',primary:'#242321',secondary:'#74716b',surface:'#ffffff',surfaceAlt:'#ebe8e1',border:'#cfcbc2',accent:'#4f4c47',dark:'#242321'},
  {id:'dreamy',name:'Dreamy',icon:'☁',description:'Lavender haze, dusty rose, soft cream, and gentle contrast.',page:{background:'#f1ecf3',textColor:'#332b38'},fontFamily:'Georgia, serif',headingFont:'Georgia, serif',primary:'#332b38',secondary:'#7d7082',surface:'#fffafd',surfaceAlt:'#e3d7e7',border:'#cfc1d5',accent:'#8a6e95',dark:'#4a3d50'},
  {id:'color-pop',name:'Color Pop',icon:'●',description:'Cream canvas with confident coral, cobalt, and golden accents.',page:{background:'#f7f2e8',textColor:'#282526'},fontFamily:'Arial, sans-serif',headingFont:'Arial, sans-serif',primary:'#282526',secondary:'#6e6865',surface:'#fffdf9',surfaceAlt:'#f1cf75',border:'#d9cfc0',accent:'#d86755',dark:'#344d88'},
  {id:'moonlit',name:'Moonlit',icon:'◐',description:'Deep blue-charcoal, silvered lavender, and moonstone surfaces.',page:{background:'#171c28',textColor:'#eef0f8'},fontFamily:'Georgia, serif',headingFont:'Georgia, serif',primary:'#eef0f8',secondary:'#aeb5c9',surface:'#232a3a',surfaceAlt:'#31394c',border:'#46506a',accent:'#a99cc4',dark:'#111620'},
]

export const DATA_KITS:DataKit[]=[
  {id:'budget-system',name:'Budget System',icon:'$',description:'Transactions, bills, savings goals, and subscriptions.',collections:[{name:'Transactions',fields:[{name:'Amount',type:'number'},{name:'Type',type:'select'},{name:'Category',type:'select'},{name:'Date',type:'date'},{name:'Account',type:'select'},{name:'Notes',type:'long_text'}]},{name:'Bills',fields:[{name:'Amount',type:'number'},{name:'Due date',type:'date'},{name:'Category',type:'select'},{name:'Paid',type:'checkbox'},{name:'Recurring',type:'checkbox'}]},{name:'Savings Goals',fields:[{name:'Target',type:'number'},{name:'Saved',type:'number'},{name:'Target date',type:'date'},{name:'Notes',type:'long_text'}]},{name:'Subscriptions',fields:[{name:'Amount',type:'number'},{name:'Renewal date',type:'date'},{name:'Category',type:'select'},{name:'Active',type:'checkbox'}]}]},
  {id:'reading-system',name:'Reading System',icon:'📚',description:'Books plus optional reading-session data.',collections:[{name:'Books',fields:[{name:'Author',type:'text'},{name:'Status',type:'select'},{name:'Rating',type:'number'},{name:'Genre',type:'multi_select'},{name:'Cover',type:'image'},{name:'Started',type:'date'},{name:'Finished',type:'date'},{name:'Notes',type:'long_text'}]},{name:'Reading Sessions',fields:[{name:'Book',type:'text'},{name:'Date',type:'date'},{name:'Minutes',type:'number'},{name:'Pages',type:'number'},{name:'Notes',type:'long_text'}]}]},
  {id:'podcast-system',name:'Podcast System',icon:'◉',description:'Episodes, guests, production tasks, and idea capture.',collections:[{name:'Episodes',fields:[{name:'Status',type:'select'},{name:'Guest',type:'text'},{name:'Record date',type:'date'},{name:'Publish date',type:'date'},{name:'Episode number',type:'number'},{name:'Show notes',type:'long_text'},{name:'Published URL',type:'url'}]},{name:'Guests',fields:[{name:'Email',type:'text'},{name:'Status',type:'select'},{name:'Bio',type:'long_text'},{name:'Links',type:'url'},{name:'Notes',type:'long_text'}]},{name:'Podcast Tasks',fields:[{name:'Status',type:'select'},{name:'Due date',type:'date'},{name:'Episode',type:'text'},{name:'Priority',type:'select'},{name:'Done',type:'checkbox'}]},{name:'Episode Ideas',fields:[{name:'Status',type:'select'},{name:'Hook',type:'long_text'},{name:'Notes',type:'long_text'}]}]},
  {id:'travel-system',name:'Travel System',icon:'✈',description:'Trips, itinerary items, travel expenses, and packing.',collections:[{name:'Trips',fields:[{name:'Destination',type:'text'},{name:'Start date',type:'date'},{name:'End date',type:'date'},{name:'Status',type:'select'},{name:'Budget',type:'number'},{name:'Cover',type:'image'},{name:'Notes',type:'long_text'}]},{name:'Itinerary',fields:[{name:'Trip',type:'text'},{name:'Date',type:'date'},{name:'Time',type:'text'},{name:'Place',type:'text'},{name:'Booking URL',type:'url'},{name:'Notes',type:'long_text'}]},{name:'Travel Expenses',fields:[{name:'Trip',type:'text'},{name:'Amount',type:'number'},{name:'Category',type:'select'},{name:'Date',type:'date'},{name:'Paid',type:'checkbox'}]},{name:'Packing',fields:[{name:'Trip',type:'text'},{name:'Category',type:'select'},{name:'Packed',type:'checkbox'},{name:'Notes',type:'text'}]}]},
  {id:'witchy-journal-system',name:'Witchy Journal System',icon:'☾',description:'Grimoire, dreams, divination, and ritual records.',collections:[{name:'Grimoire',fields:[{name:'Type',type:'select'},{name:'Date',type:'date'},{name:'Intent',type:'long_text'},{name:'Correspondences',type:'multi_select'},{name:'Result',type:'long_text'},{name:'Image',type:'image'}]},{name:'Dream Journal',fields:[{name:'Date',type:'date'},{name:'Dream',type:'long_text'},{name:'Symbols',type:'multi_select'},{name:'Mood',type:'select'},{name:'Notes',type:'long_text'}]},{name:'Divination',fields:[{name:'Date',type:'date'},{name:'Method',type:'select'},{name:'Question',type:'long_text'},{name:'Pull / Result',type:'long_text'},{name:'Reflection',type:'long_text'}]},{name:'Rituals',fields:[{name:'Date',type:'date'},{name:'Type',type:'select'},{name:'Intent',type:'long_text'},{name:'Outcome',type:'long_text'},{name:'Notes',type:'long_text'}]}]},
]

export function resolveCreativeConfig(config:Record<string,unknown>,databaseId:string,xOffset=0,yOffset=0,zOffset=0){const out={...config};if(out.databaseId==='$database')out.databaseId=databaseId;out.x=Number(out.x||0)+xOffset;out.y=Number(out.y||0)+yOffset;out.zIndex=Number(out.zIndex||1)+zOffset;return out}
