import { supabase } from './supabase'
import type { Database, DatabaseAutomation, DatabaseView, Field, Layout, LayoutElement, LayoutSurface, Page, PageBlock, PageBlockType, PageContextType, RecordRow, ViewType, Workspace } from '../types'

export async function ensureWorkspace(userId:string,email?:string|null):Promise<Workspace>{const{data:m,error:e}=await supabase.from('workspace_members').select('workspace:workspaces(*)').eq('user_id',userId).limit(1);if(e)throw e;const x=m?.[0]?.workspace as unknown as Workspace|undefined;if(x?.id)return x;const{data:w,error}=await supabase.from('workspaces').insert({name:email?`${email.split('@')[0]}'s workspace`:'My workspace',owner_id:userId}).select('*').single();if(error)throw error;return w as Workspace}
export async function getDatabases(workspaceId:string):Promise<Database[]>{const{data,error}=await supabase.from('databases').select('*').eq('workspace_id',workspaceId).order('created_at');if(error)throw error;return(data||[])as Database[]}
export async function createDatabase(workspaceId:string,name:string):Promise<Database>{const{data,error}=await supabase.from('databases').insert({workspace_id:workspaceId,name,description:''}).select('*').single();if(error)throw error;const db=data as Database;const{error:fe}=await supabase.from('fields').insert({database_id:db.id,name:'Name',type:'text',position:0,required:true,config:{}});if(fe)throw fe;await ensureDefaultViews(db.id);return db}
export async function getDatabase(id:string):Promise<Database>{const{data,error}=await supabase.from('databases').select('*').eq('id',id).single();if(error)throw error;return data as Database}
export async function updateDatabase(id:string,patch:Partial<Pick<Database,'name'|'description'|'icon'|'favorite'>>){const{error}=await supabase.from('databases').update(patch).eq('id',id);if(error)throw error}
export async function deleteDatabase(id:string){const{error}=await supabase.from('databases').delete().eq('id',id);if(error)throw error}
export async function getFields(id:string):Promise<Field[]>{const{data,error}=await supabase.from('fields').select('*').eq('database_id',id).order('position');if(error)throw error;return(data||[])as Field[]}
export async function createField(database_id:string,field:Pick<Field,'name'|'type'|'required'|'config'>,position:number){const{data,error}=await supabase.from('fields').insert({...field,database_id,position}).select('*').single();if(error)throw error;return data as Field}
export async function updateField(id:string,patch:Partial<Pick<Field,'name'|'type'|'required'|'config'|'position'>>){const{data,error}=await supabase.from('fields').update(patch).eq('id',id).select('*').single();if(error)throw error;return data as Field}
export async function deleteField(id:string){const{error}=await supabase.from('fields').delete().eq('id',id);if(error)throw error}
export async function getRecords(id:string):Promise<RecordRow[]>{const{data,error}=await supabase.from('records').select('*').eq('database_id',id).order('updated_at',{ascending:false});if(error)throw error;return(data||[])as RecordRow[]}
export async function getRecord(id:string):Promise<RecordRow>{const{data,error}=await supabase.from('records').select('*').eq('id',id).single();if(error)throw error;return data as RecordRow}
export async function createRecord(database_id:string,title='Untitled'){const{data,error}=await supabase.from('records').insert({database_id,title,data:{}}).select('*').single();if(error)throw error;return data as RecordRow}
export async function updateRecord(id:string,patch:Partial<Pick<RecordRow,'title'|'data'>>){const{data,error}=await supabase.from('records').update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data as RecordRow}
export async function deleteRecord(id:string){const{error}=await supabase.from('records').delete().eq('id',id);if(error)throw error}
export async function getViews(id:string):Promise<DatabaseView[]>{const{data,error}=await supabase.from('views').select('*').eq('database_id',id).order('position');if(error)throw error;return(data||[])as DatabaseView[]}
export async function ensureDefaultViews(id:string){const x=await getViews(id);if(x.length)return x;const{data,error}=await supabase.from('views').insert([{database_id:id,name:'Table',type:'table',position:0,config:{density:'comfortable',hiddenFields:[],columnWidths:{},fieldOrder:[],filters:[],sorts:[],rowHeights:{}}},{database_id:id,name:'Gallery',type:'gallery',position:1,config:{hiddenFields:[],fieldOrder:[],filters:[],sorts:[]}},{database_id:id,name:'Board',type:'board',position:2,config:{hiddenFields:[],fieldOrder:[],filters:[],sorts:[]}}]).select('*').order('position');if(error)throw error;return(data||[])as DatabaseView[]}
export async function createView(database_id:string,name:string,type:ViewType,position:number){const{data,error}=await supabase.from('views').insert({database_id,name,type,position,config:{hiddenFields:[],columnWidths:{},fieldOrder:[],filters:[],sorts:[],rowHeights:{}}}).select('*').single();if(error)throw error;return data as DatabaseView}
export async function updateView(id:string,patch:Partial<Pick<DatabaseView,'name'|'position'|'config'>>){const{data,error}=await supabase.from('views').update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data as DatabaseView}
export async function deleteView(id:string){const{error}=await supabase.from('views').delete().eq('id',id);if(error)throw error}
export async function getAutomations(databaseId:string):Promise<DatabaseAutomation[]>{const{data,error}=await supabase.from('database_automations').select('*').eq('database_id',databaseId).order('created_at');if(error)throw error;return(data||[])as DatabaseAutomation[]}
export async function createAutomation(database_id:string,automation:Pick<DatabaseAutomation,'name'|'enabled'|'trigger_type'|'trigger_config'|'action_type'|'action_config'>){const{data,error}=await supabase.from('database_automations').insert({...automation,database_id}).select('*').single();if(error)throw error;return data as DatabaseAutomation}
export async function updateAutomation(id:string,patch:Partial<Pick<DatabaseAutomation,'name'|'enabled'|'trigger_type'|'trigger_config'|'action_type'|'action_config'>>){const{data,error}=await supabase.from('database_automations').update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data as DatabaseAutomation}
export async function deleteAutomation(id:string){const{error}=await supabase.from('database_automations').delete().eq('id',id);if(error)throw error}

export async function getPages(workspaceId:string):Promise<Page[]>{const{data,error}=await supabase.from('pages').select('*').eq('workspace_id',workspaceId).order('position');if(error)throw error;return(data||[])as Page[]}
export async function getPage(id:string):Promise<Page>{const{data,error}=await supabase.from('pages').select('*').eq('id',id).single();if(error)throw error;return data as Page}
export async function createPage(workspace_id:string,title='Untitled page',position=0,parent_id:string|null=null){const{data,error}=await supabase.from('pages').insert({workspace_id,title,position,parent_id,context_type:'page'}).select('*').single();if(error)throw error;return data as Page}
export async function updatePage(id:string,patch:Partial<Pick<Page,'title'|'icon'|'cover'|'position'|'parent_id'|'favorite'|'settings'>>){const{data,error}=await supabase.from('pages').update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data as Page}
export async function deletePage(id:string){const{error}=await supabase.from('pages').delete().eq('id',id);if(error)throw error}
export async function getContextPage(workspaceId:string,contextType:PageContextType,databaseId?:string|null,recordId?:string|null):Promise<Page|null>{let q=supabase.from('pages').select('*').eq('workspace_id',workspaceId).eq('context_type',contextType);if(contextType==='database')q=q.eq('context_database_id',databaseId);if(contextType==='record')q=q.eq('context_record_id',recordId);const{data,error}=await q.limit(1);if(error)throw error;return(data?.[0]||null)as Page|null}
export async function getOrCreateContextPage(workspaceId:string,contextType:Exclude<PageContextType,'page'>,title:string,opts:{databaseId?:string|null;recordId?:string|null;icon?:string|null}={}):Promise<Page>{const found=await getContextPage(workspaceId,contextType,opts.databaseId,opts.recordId);if(found)return found;const{data,error}=await supabase.from('pages').insert({workspace_id:workspaceId,title,icon:opts.icon||null,context_type:contextType,context_database_id:opts.databaseId||null,context_record_id:opts.recordId||null,position:0}).select('*').single();if(error)throw error;return data as Page}
export async function getPageBlocks(pageId:string):Promise<PageBlock[]>{const{data,error}=await supabase.from('page_blocks').select('*').eq('page_id',pageId).order('position');if(error)throw error;return(data||[])as PageBlock[]}
export async function createPageBlock(page_id:string,type:PageBlockType,position:number,config:Record<string,unknown>={}){const{data,error}=await supabase.from('page_blocks').insert({page_id,type,position,config}).select('*').single();if(error)throw error;return data as PageBlock}
export async function updatePageBlock(id:string,patch:Partial<Pick<PageBlock,'position'|'config'>>){const{data,error}=await supabase.from('page_blocks').update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data as PageBlock}
export async function deletePageBlock(id:string){const{error}=await supabase.from('page_blocks').delete().eq('id',id);if(error)throw error}

const surfaceSize:Record<LayoutSurface,{width:number;height:number}>={record:{width:900,height:700},gallery:{width:420,height:560},board:{width:320,height:220}}
export async function getLayoutForSurface(databaseId:string,surface:LayoutSurface,recordId?:string|null):Promise<Layout|null>{let q=supabase.from('layouts').select('*').eq('database_id',databaseId).eq('surface',surface);q=recordId?q.eq('record_id',recordId):q.is('record_id',null);const{data,error}=await q.limit(1);if(error)throw error;return(data?.[0]||null)as Layout|null}
export async function getOrCreateSurfaceLayout(databaseId:string,surface:LayoutSurface,recordId?:string|null):Promise<Layout>{const existing=await getLayoutForSurface(databaseId,surface,recordId);if(existing)return existing;const size=surfaceSize[surface];let seed:Layout|null=null;if(recordId)seed=await getLayoutForSurface(databaseId,surface,null);const{data,error}=await supabase.from('layouts').insert({database_id:databaseId,name:recordId?`Custom ${surface}`:`Default ${surface}`,surface,record_id:recordId||null,canvas_width:seed?.canvas_width||size.width,canvas_height:seed?.canvas_height||size.height,background:seed?.background||'#f8f4ec'}).select('*').single();if(error)throw error;const layout=data as Layout;if(recordId&&seed){const els=await getLayoutElements(seed.id);if(els.length){const copies=els.map(({id:_id,layout_id:_layoutId,...e})=>({...e,layout_id:layout.id}));const{error:ce}=await supabase.from('layout_elements').insert(copies);if(ce)throw ce}}return layout}
export async function getOrCreateLayout(id:string){return getOrCreateSurfaceLayout(id,'record',null)}
export async function updateLayout(id:string,patch:Partial<Pick<Layout,'name'|'canvas_width'|'canvas_height'|'background'>>){const{error}=await supabase.from('layouts').update(patch).eq('id',id);if(error)throw error}
export async function getLayoutElements(id:string):Promise<LayoutElement[]>{const{data,error}=await supabase.from('layout_elements').select('*').eq('layout_id',id).order('z_index');if(error)throw error;return(data||[])as LayoutElement[]}
export async function createLayoutElement(layout_id:string,element:Omit<LayoutElement,'id'|'layout_id'>){const{data,error}=await supabase.from('layout_elements').insert({...element,layout_id}).select('*').single();if(error)throw error;return data as LayoutElement}
export async function updateLayoutElement(id:string,patch:Partial<Omit<LayoutElement,'id'|'layout_id'>>){const{error}=await supabase.from('layout_elements').update(patch).eq('id',id);if(error)throw error}
export async function deleteLayoutElement(id:string){const{error}=await supabase.from('layout_elements').delete().eq('id',id);if(error)throw error}
