export type WidgetPresetCategory = 'Witchy' | 'Budget' | 'Books' | 'Podcast' | 'Productivity'
export type WidgetPreset = { id:string; name:string; category:WidgetPresetCategory; description:string; config:Record<string,unknown> }

const item=(id:string,text:string)=>({id,text,done:false})

export const WIDGET_PRESETS:WidgetPreset[] = [
  { id:'altar-checklist',name:'Altar Checklist',category:'Witchy',description:'A reusable altar setup and reset checklist.',config:{widgetType:'checklist',label:'Altar checklist',items:[item('altar-1','Refresh water or offering'),item('altar-2','Clean altar surface'),item('altar-3','Dress or replace candle'),item('altar-4','Return tools to their places')],surfaceColor:'#f6efe5',primaryColor:'#2e2530',secondaryColor:'#75657a',accentColor:'#665477',borderColor:'#cfc0d2',widgetBorderWidth:1,widgetRadius:18,widgetPadding:16}},
  { id:'daily-intention',name:'Daily Intention',category:'Witchy',description:'A soft editable intention card for the day.',config:{widgetType:'daily_focus',label:'DAILY INTENTION',text:'What do you want to embody today?',surfaceColor:'#efe4d5',primaryColor:'#2d2530',secondaryColor:'#75657a',accentColor:'#665477',borderColor:'#d4c3b2',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'deity-devotion',name:'Devotion Note',category:'Witchy',description:'A devotional note or offering reminder.',config:{widgetType:'custom',customIcon:'✦',customTitle:'Devotion',customValue:'Today’s offering',customBody:'What do you want to remember, offer, ask, or honor today?',surfaceColor:'#2c2530',primaryColor:'#f7efe7',secondaryColor:'#c7b8cc',accentColor:'#b69bc2',borderColor:'#54455c',widgetBorderWidth:1,widgetRadius:22,widgetPadding:20}},
  { id:'divination-prompt',name:'Divination Prompt',category:'Witchy',description:'A journal prompt for tarot, oracle, runes, or other divination.',config:{widgetType:'sticky_note',label:'DIVINATION',text:'What is asking to be seen clearly today?',surfaceColor:'#e6d7bd',primaryColor:'#30272e',secondaryColor:'#796a73',borderColor:'#c9b58e',widgetBorderWidth:1,widgetRadius:12,widgetPadding:18}},
  { id:'dream-prompt',name:'Dream Journal Prompt',category:'Witchy',description:'A quick dream capture card.',config:{widgetType:'sticky_note',label:'DREAM NOTES',text:'What do you remember? Capture images, emotions, symbols, people, places, and anything that felt important.',surfaceColor:'#dcd9e7',primaryColor:'#282634',secondaryColor:'#666079',borderColor:'#bbb6ce',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'lunar-phase',name:'Lunar Phase',category:'Witchy',description:'Current moon phase and lunar age.',config:{widgetType:'moon_phase',surfaceColor:'#26212b',primaryColor:'#f7efe7',secondaryColor:'#c9bbcf',accentColor:'#b99ac6',borderColor:'#504458',widgetBorderWidth:1,widgetRadius:24,widgetPadding:20}},
  { id:'offering-tracker',name:'Offering Tracker',category:'Witchy',description:'Keep a small rotating list of offerings or devotional acts.',config:{widgetType:'todo',label:'Offerings & devotion',items:[item('offer-1','Fresh water'),item('offer-2','Incense or candle'),item('offer-3','Prayer, hymn, or devotional reading'),item('offer-4','Act of service or promised action')],surfaceColor:'#ede4d9',primaryColor:'#322832',secondaryColor:'#76697b',accentColor:'#775c80',borderColor:'#d3c1cb',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'ritual-countdown',name:'Ritual Countdown',category:'Witchy',description:'Countdown to a ritual, moon date, or sacred day.',config:{widgetType:'countdown',label:'Next ritual',surfaceColor:'#f5efe5',primaryColor:'#302730',secondaryColor:'#75657a',accentColor:'#75577c',borderColor:'#d6c7d8',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'ritual-planner',name:'Ritual Planner',category:'Witchy',description:'A compact ritual preparation workflow.',config:{widgetType:'todo',label:'Ritual plan',items:[item('ritual-1','Define the intention'),item('ritual-2','Choose timing and location'),item('ritual-3','Gather tools and correspondences'),item('ritual-4','Prepare offering or petition'),item('ritual-5','Ground, perform, close, and journal')],surfaceColor:'#f7f0e7',primaryColor:'#302730',secondaryColor:'#76677e',borderColor:'#d8c9d9',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'sabbat-countdown',name:'Sabbat Countdown',category:'Witchy',description:'A customizable seasonal celebration countdown.',config:{widgetType:'countdown',label:'Next seasonal celebration',surfaceColor:'#3a302b',primaryColor:'#fff5e8',secondaryColor:'#d7c5ac',accentColor:'#d8ab6b',borderColor:'#5e4c42',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'shadow-work',name:'Shadow Work Prompt',category:'Witchy',description:'A gentle prompt card for reflective journaling.',config:{widgetType:'sticky_note',label:'SHADOW WORK',text:'What reaction, fear, or pattern is asking for curiosity instead of judgment?',surfaceColor:'#302b33',primaryColor:'#f5eee8',secondaryColor:'#bdb0c3',accentColor:'#a58aad',borderColor:'#514756',widgetBorderWidth:1,widgetRadius:18,widgetPadding:20}},
  { id:'spell-checklist',name:'Spell Checklist',category:'Witchy',description:'A practical spell-working preparation list.',config:{widgetType:'checklist',label:'Spell checklist',items:[item('spell-1','Write a clear intention'),item('spell-2','Choose ingredients and correspondences'),item('spell-3','Check safety and practical concerns'),item('spell-4','Set up the working space'),item('spell-5','Record results and follow-up actions')],surfaceColor:'#e8dfd3',primaryColor:'#30272f',secondaryColor:'#766a78',accentColor:'#765a79',borderColor:'#ccbfc8',widgetBorderWidth:1,widgetRadius:16,widgetPadding:18}},
  { id:'wheel-year',name:'Wheel of the Year',category:'Witchy',description:'A customizable annual cycle tracker.',config:{widgetType:'annual_cycle',label:'Seasonal cycle',labels:'Yule,Imbolc,Ostara,Beltane,Litha,Lughnasadh,Mabon,Samhain',surfaceColor:'#e9dfcf',primaryColor:'#332b27',secondaryColor:'#76675c',accentColor:'#7b6656',borderColor:'#cebda4',widgetBorderWidth:1,widgetRadius:24,widgetPadding:18}},

  { id:'bills-due',name:'Bills Due',category:'Budget',description:'A practical recurring bills checklist.',config:{widgetType:'todo',label:'Bills due',items:[item('bill-1','Rent / mortgage'),item('bill-2','Utilities'),item('bill-3','Phone / internet'),item('bill-4','Insurance'),item('bill-5','Subscriptions to review')],surfaceColor:'#f7f5ef',primaryColor:'#243128',secondaryColor:'#68746b',accentColor:'#688371',borderColor:'#ccd4ce',widgetBorderWidth:1,widgetRadius:18,widgetPadding:16}},
  { id:'budget-used',name:'Budget Used',category:'Budget',description:'A circular budget progress indicator.',config:{widgetType:'progress_ring',label:'Budget used',value:35,max:100,accentColor:'#826b50',surfaceColor:'#f8f4ec',primaryColor:'#302b25',secondaryColor:'#746b61',borderColor:'#d9cdbd',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'debt-payoff',name:'Debt Payoff',category:'Budget',description:'Track payoff progress toward a target.',config:{widgetType:'goal',label:'Debt payoff',value:0,max:10000,accentColor:'#8a5b55',surfaceColor:'#faf5ef',primaryColor:'#352825',secondaryColor:'#796b67',borderColor:'#ddc9c5',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'emergency-fund',name:'Emergency Fund',category:'Budget',description:'A savings goal preset for an emergency fund.',config:{widgetType:'goal',label:'Emergency fund',value:0,max:5000,accentColor:'#557565',surfaceColor:'#f2f6f2',primaryColor:'#26362e',secondaryColor:'#65766d',borderColor:'#c6d5cb',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'monthly-money-checkin',name:'Monthly Money Check-in',category:'Budget',description:'A short financial review list for the end or beginning of a month.',config:{widgetType:'checklist',label:'Monthly money check-in',items:[item('money-1','Review income received'),item('money-2','Categorize uncategorized spending'),item('money-3','Review subscriptions and bills'),item('money-4','Move money to savings goals'),item('money-5','Set next month’s priorities')],surfaceColor:'#eef2ec',primaryColor:'#26342b',secondaryColor:'#667269',accentColor:'#58705f',borderColor:'#c8d0c8',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'monthly-spending',name:'Monthly Spending',category:'Budget',description:'Track spending against a monthly limit.',config:{widgetType:'goal',label:'Monthly spending',value:0,max:2500,accentColor:'#8b684c',surfaceColor:'#f8f3eb',primaryColor:'#342c26',secondaryColor:'#796d63',borderColor:'#d8c9b8',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'quick-expense',name:'Quick Expense',category:'Budget',description:'Quickly create an expense record in a selected database.',config:{widgetType:'quick_capture',placeholder:'Log expense: groceries, coffee, bill…',surfaceColor:'#ffffff',primaryColor:'#26302a',secondaryColor:'#6c756f',accentColor:'#557565',borderColor:'#cbd3ce',widgetBorderWidth:1,widgetRadius:16,widgetPadding:12}},
  { id:'savings-goal',name:'Savings Goal',category:'Budget',description:'Track saved amount toward any target.',config:{widgetType:'goal',label:'Savings goal',value:0,max:5000,accentColor:'#5f738d',surfaceColor:'#f3f5f8',primaryColor:'#27313d',secondaryColor:'#657181',borderColor:'#cad2dc',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'spending-total',name:'Spending Total',category:'Budget',description:'Sum a numeric property from a database.',config:{widgetType:'database_aggregate',label:'Spent this month',aggregate:'sum',surfaceColor:'#f8f4ec',primaryColor:'#352d27',secondaryColor:'#776c62',accentColor:'#8b684c',borderColor:'#d8cbbd',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},

  { id:'reading-goal',name:'Reading Goal',category:'Books',description:'A reading progress goal that can count database records.',config:{widgetType:'goal',label:'Reading goal',value:0,max:50,accentColor:'#80584f',surfaceColor:'#fbf6ee',primaryColor:'#332823',secondaryColor:'#796b64',borderColor:'#ddcec0',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'reading-session',name:'Reading Session',category:'Books',description:'A compact reading-session checklist.',config:{widgetType:'checklist',label:'Reading session',items:[item('read-1','Settle in and silence distractions'),item('read-2','Read today’s pages / chapter'),item('read-3','Capture a favorite quote or note'),item('read-4','Update reading progress')],surfaceColor:'#f4eadf',primaryColor:'#30261f',secondaryColor:'#786b61',accentColor:'#8a6455',borderColor:'#ddcaba',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'random-read',name:'Pick My Next Read',category:'Books',description:'Pull a random record from your library.',config:{widgetType:'random_record',label:'Pick my next read',surfaceColor:'#f1e8dc',primaryColor:'#302821',secondaryColor:'#776b61',accentColor:'#75594a',borderColor:'#d5c3af',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'bookish-note',name:'Bookish Note',category:'Books',description:'A sticky note for reading moods, quotes, and TBR thoughts.',config:{widgetType:'sticky_note',label:'BOOKISH NOTE',text:'What are you in the mood to read next?',surfaceColor:'#ead8b9',primaryColor:'#33271e',secondaryColor:'#796a5d',borderColor:'#d1b98f',widgetBorderWidth:1,widgetRadius:14,widgetPadding:18}},

  { id:'episode-idea',name:'Episode Idea Capture',category:'Podcast',description:'Quick capture for episode ideas.',config:{widgetType:'quick_capture',placeholder:'Capture an episode idea, title, hook, or guest…',surfaceColor:'#f8f5ef',primaryColor:'#292620',secondaryColor:'#706b61',accentColor:'#65577c',borderColor:'#d8d0c3',widgetBorderWidth:1,widgetRadius:16,widgetPadding:12}},
  { id:'episode-production',name:'Episode Production Checklist',category:'Podcast',description:'A repeatable episode-production workflow.',config:{widgetType:'todo',label:'Episode production',items:[item('pod-1','Outline the episode'),item('pod-2','Research and gather sources'),item('pod-3','Record'),item('pod-4','Edit audio'),item('pod-5','Write show notes'),item('pod-6','Create promotional assets'),item('pod-7','Schedule and publish')],surfaceColor:'#f2eee8',primaryColor:'#2a2622',secondaryColor:'#726b64',accentColor:'#66577b',borderColor:'#d7cfc5',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'guest-prep',name:'Guest Prep',category:'Podcast',description:'A concise guest interview preparation checklist.',config:{widgetType:'checklist',label:'Guest prep',items:[item('guest-1','Confirm recording date and timezone'),item('guest-2','Review guest bio and links'),item('guest-3','Draft talking points and questions'),item('guest-4','Send recording details'),item('guest-5','Prepare intro and outro notes')],surfaceColor:'#ece8f0',primaryColor:'#2b2630',secondaryColor:'#716879',accentColor:'#6d5d80',borderColor:'#d1c7d8',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},

  { id:'next-actions',name:'Next Actions',category:'Productivity',description:'A clean standalone task list.',config:{widgetType:'todo',label:'Next actions',items:[item('task-1','Choose the next concrete action'),item('task-2','Block time for focused work'),item('task-3','Clear one small obstacle')],surfaceColor:'#ffffff',primaryColor:'#282522',secondaryColor:'#777069',accentColor:'#65577c',borderColor:'#ddd6cd',widgetBorderWidth:1,widgetRadius:18,widgetPadding:16}},
  { id:'weekly-reset',name:'Weekly Reset',category:'Productivity',description:'A practical weekly planning checklist.',config:{widgetType:'checklist',label:'Weekly reset',items:[item('week-1','Review unfinished tasks'),item('week-2','Clear inboxes and quick notes'),item('week-3','Choose this week’s priorities'),item('week-4','Schedule important work'),item('week-5','Reset workspace')],surfaceColor:'#f6f4ef',primaryColor:'#2c2924',secondaryColor:'#777168',accentColor:'#66715f',borderColor:'#d9d5cc',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}}
]
