export type WidgetPresetCategory = 'Witchy' | 'Budget' | 'Books' | 'Podcast' | 'Productivity'
export type WidgetPreset = { id:string; name:string; category:WidgetPresetCategory; description:string; config:Record<string,unknown> }

export const WIDGET_PRESETS:WidgetPreset[] = [
  { id:'altar-checklist',name:'Altar Checklist',category:'Witchy',description:'A reusable ritual or altar preparation list.',config:{widgetType:'checklist',label:'Altar checklist',items:[{id:'1',text:'Cleanse the space',done:false},{id:'2',text:'Prepare candle / offering',done:false},{id:'3',text:'Gather tools',done:false}],surfaceColor:'#f6efe5',primaryColor:'#2e2530',secondaryColor:'#75657a',accentColor:'#665477',borderColor:'#cfc0d2',widgetBorderWidth:1,widgetRadius:18,widgetPadding:16}},
  { id:'daily-intention',name:'Daily Intention',category:'Witchy',description:'A soft editable intention card.',config:{widgetType:'daily_focus',label:'DAILY INTENTION',text:'What are you calling in today?',surfaceColor:'#efe4d5',primaryColor:'#2d2530',secondaryColor:'#75657a',accentColor:'#665477',borderColor:'#d4c3b2',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'deity-devotion',name:'Devotion Note',category:'Witchy',description:'A devotional note or offering reminder.',config:{widgetType:'custom',customIcon:'✦',customTitle:'Devotion',customValue:'Offering',customBody:'What do you want to remember, offer, or honor today?',surfaceColor:'#2c2530',primaryColor:'#f7efe7',secondaryColor:'#c7b8cc',accentColor:'#b69bc2',borderColor:'#54455c',widgetBorderWidth:1,widgetRadius:22,widgetPadding:20}},
  { id:'divination-prompt',name:'Divination Prompt',category:'Witchy',description:'A journal prompt for tarot, oracle, runes or other divination.',config:{widgetType:'sticky_note',label:'DIVINATION',text:'What is asking to be seen today?',surfaceColor:'#e6d7bd',primaryColor:'#30272e',secondaryColor:'#796a73',borderColor:'#c9b58e',widgetBorderWidth:1,widgetRadius:12,widgetPadding:18}},
  { id:'dream-prompt',name:'Dream Journal Prompt',category:'Witchy',description:'A quick dream capture card.',config:{widgetType:'sticky_note',label:'DREAM NOTES',text:'Images, feelings, symbols, people, places…',surfaceColor:'#dcd9e7',primaryColor:'#282634',secondaryColor:'#666079',borderColor:'#bbb6ce',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'lunar-phase',name:'Lunar Phase',category:'Witchy',description:'Current moon phase and lunar age.',config:{widgetType:'moon_phase',surfaceColor:'#26212b',primaryColor:'#f7efe7',secondaryColor:'#c9bbcf',accentColor:'#b99ac6',borderColor:'#504458',widgetBorderWidth:1,widgetRadius:24,widgetPadding:20}},
  { id:'ritual-countdown',name:'Ritual Countdown',category:'Witchy',description:'Countdown to a ritual, sabbat, moon date or sacred day.',config:{widgetType:'countdown',label:'Next ritual',surfaceColor:'#f5efe5',primaryColor:'#302730',secondaryColor:'#75657a',accentColor:'#75577c',borderColor:'#d6c7d8',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'ritual-planner',name:'Ritual Planner',category:'Witchy',description:'A compact ritual preparation checklist.',config:{widgetType:'todo',label:'Ritual plan',items:[{id:'1',text:'Set intention',done:false},{id:'2',text:'Gather correspondences',done:false},{id:'3',text:'Prepare space',done:false},{id:'4',text:'Journal afterward',done:false}],surfaceColor:'#f7f0e7',primaryColor:'#302730',secondaryColor:'#76677e',borderColor:'#d8c9d9',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'sabbat-countdown',name:'Sabbat Countdown',category:'Witchy',description:'A customizable seasonal celebration countdown.',config:{widgetType:'countdown',label:'Next seasonal celebration',surfaceColor:'#3a302b',primaryColor:'#fff5e8',secondaryColor:'#d7c5ac',accentColor:'#d8ab6b',borderColor:'#5e4c42',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'wheel-year',name:'Wheel of the Year',category:'Witchy',description:'A customizable annual cycle tracker.',config:{widgetType:'annual_cycle',label:'Seasonal cycle',labels:'Yule,Imbolc,Ostara,Beltane,Litha,Lughnasadh,Mabon,Samhain',surfaceColor:'#e9dfcf',primaryColor:'#332b27',secondaryColor:'#76675c',accentColor:'#7b6656',borderColor:'#cebda4',widgetBorderWidth:1,widgetRadius:24,widgetPadding:18}},

  { id:'bills-due',name:'Bills Due',category:'Budget',description:'A simple bills checklist that can later bind to a database.',config:{widgetType:'todo',label:'Bills due',surfaceColor:'#f7f5ef',primaryColor:'#243128',secondaryColor:'#68746b',accentColor:'#688371',borderColor:'#ccd4ce',widgetBorderWidth:1,widgetRadius:18,widgetPadding:16}},
  { id:'budget-used',name:'Budget Used',category:'Budget',description:'A circular budget progress indicator.',config:{widgetType:'progress_ring',label:'Budget used',value:35,max:100,accentColor:'#826b50',surfaceColor:'#f8f4ec',primaryColor:'#302b25',secondaryColor:'#746b61',borderColor:'#d9cdbd',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'debt-payoff',name:'Debt Payoff',category:'Budget',description:'Track payoff progress toward a target.',config:{widgetType:'goal',label:'Debt payoff',value:0,max:10000,accentColor:'#8a5b55',surfaceColor:'#faf5ef',primaryColor:'#352825',secondaryColor:'#796b67',borderColor:'#ddc9c5',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'emergency-fund',name:'Emergency Fund',category:'Budget',description:'A savings goal preset for an emergency fund.',config:{widgetType:'goal',label:'Emergency fund',value:0,max:5000,accentColor:'#557565',surfaceColor:'#f2f6f2',primaryColor:'#26362e',secondaryColor:'#65766d',borderColor:'#c6d5cb',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'monthly-spending',name:'Monthly Spending',category:'Budget',description:'Track spending against a monthly limit.',config:{widgetType:'goal',label:'Monthly spending',value:0,max:2500,accentColor:'#8b684c',surfaceColor:'#f8f3eb',primaryColor:'#342c26',secondaryColor:'#796d63',borderColor:'#d8c9b8',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'quick-expense',name:'Quick Expense',category:'Budget',description:'Quickly create an expense record in a selected database.',config:{widgetType:'quick_capture',placeholder:'Log an expense…',surfaceColor:'#ffffff',primaryColor:'#26302a',secondaryColor:'#6c756f',accentColor:'#557565',borderColor:'#cbd3ce',widgetBorderWidth:1,widgetRadius:16,widgetPadding:12}},
  { id:'savings-goal',name:'Savings Goal',category:'Budget',description:'Track saved amount toward any target.',config:{widgetType:'goal',label:'Savings goal',value:0,max:5000,accentColor:'#5f738d',surfaceColor:'#f3f5f8',primaryColor:'#27313d',secondaryColor:'#657181',borderColor:'#cad2dc',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'spending-total',name:'Spending Total',category:'Budget',description:'Sum a numeric property from a database.',config:{widgetType:'database_aggregate',label:'Spent this month',aggregate:'sum',surfaceColor:'#f8f4ec',primaryColor:'#352d27',secondaryColor:'#776c62',accentColor:'#8b684c',borderColor:'#d8cbbd',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},

  { id:'reading-goal',name:'Reading Goal',category:'Books',description:'A reading progress goal that can count database records.',config:{widgetType:'goal',label:'Reading goal',value:0,max:50,accentColor:'#80584f',surfaceColor:'#fbf6ee',primaryColor:'#332823',secondaryColor:'#796b64',borderColor:'#ddcec0',widgetBorderWidth:1,widgetRadius:18,widgetPadding:18}},
  { id:'random-read',name:'Pick My Next Read',category:'Books',description:'Pull a random record from your library.',config:{widgetType:'random_record',label:'Pick my next read',surfaceColor:'#f1e8dc',primaryColor:'#302821',secondaryColor:'#776b61',accentColor:'#75594a',borderColor:'#d5c3af',widgetBorderWidth:1,widgetRadius:20,widgetPadding:18}},
  { id:'episode-idea',name:'Episode Idea Capture',category:'Podcast',description:'Quick capture for episode ideas.',config:{widgetType:'quick_capture',placeholder:'Capture an episode idea…',surfaceColor:'#f8f5ef',primaryColor:'#292620',secondaryColor:'#706b61',accentColor:'#65577c',borderColor:'#d8d0c3',widgetBorderWidth:1,widgetRadius:16,widgetPadding:12}},
  { id:'next-actions',name:'Next Actions',category:'Productivity',description:'A clean standalone task list.',config:{widgetType:'todo',label:'Next actions',surfaceColor:'#ffffff',primaryColor:'#282522',secondaryColor:'#777069',accentColor:'#65577c',borderColor:'#ddd6cd',widgetBorderWidth:1,widgetRadius:18,widgetPadding:16}}
]
