import { useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Database as DatabaseIcon, ExternalLink, Grid3X3, KanbanSquare, LayoutGrid, Plus, Search, SlidersHorizontal, Sparkles, Trash2, X } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { createField, createRecord, deleteField, deleteRecord, getDatabase, getFields, getRecords, updateField, updateRecord } from '../lib/data'
import type { Database, Field, FieldType, RecordRow } from '../types'

type ViewMode='table'|'gallery'|'board'
type SortDirection='asc'|'desc'
const FIELD_TYPES:Array<{value:FieldType;label:string;hint:string}>=[
 {value:'text',label:'Text',hint:'Names, authors, locations, short notes'},
 {value:'long_text',label:'Long text',hint:'Descriptions, notes, journal entries'},
 {value:'number',label:'Number',hint:'Counts, ratings, money, quantities'},
 {value:'date',label:'Date',hint:'Deadlines, release dates, reading dates'},
 {value:'checkbox',label:'Checkbox',hint:'Done, paid, favorite, packed'},
 {value:'select',label:'Single select',hint:'One status, type, category, mood'},
 {value:'multi_select',label:'Multi-select',hint:'Genres, tags, ingredients, correspondences'},
 {value:'url',label:'Link',hint:'Websites, bookings, published URLs'},
 {value:'image',label:'Image',hint:'Covers, photos, artwork, receipts'},
 {value:'relation',label:'Relation',hint:'Connect records to another collection'},
]

export default function DatabaseWorkspace(){
 const {databaseId=''}=useParams();const[database,setDatabase]=useState<Database|null>(null),[fields,setFields]=useState<Field[]>([]),[records,setRecords]=useState<RecordRow[]>([]),[mode,setMode]=useState<ViewMode>('table'),[query,setQuery]=useState(''),[fieldsOpen,setFieldsOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sortField,setSortField]=useState('__updated__'),[sortDirection,setSortDirection]=useState<SortDirection>('desc'),[boardField,setBoardField]=useState('')
 const load=async()=>{setError('');try{const [db,nextFields,nextRecords]=await Promise.all([getDatabase(databaseId),getFields(databaseId),getRecords(databaseId)]);setDatabase(db);setFields(nextFields);setRecords(nextRecords)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[databaseId])
 const visibleFields=useMemo(()=>fields.filter(f=>f.name.trim().toLowerCase()!=='name').sort((a,b)=>a.position-b.position),[fields])
 const boardFields=useMemo(()=>visibleFields.filter(f=>['select','multi_select','checkbox'].includes(f.type)),[visibleFields])
 useEffect(()=>{if(!boardField&&boardFields.length)setBoardField(boardFields.find(f=>f.name.toLowerCase()==='status')?.id||boardFields[0].id)},[boardFields,boardField])
 const shown=useMemo(()=>{const q=query.trim().toLowerCase();let next=q?records.filter(r=>r.title.toLowerCase().includes(q)||visibleFields.some(f=>formatValue(r.data?.[f.id]).toLowerCase().includes(q))):[...records];if(sortField==='__title__')next.sort((a,b)=>a.title.localeCompare(b.title)*(sortDirection==='desc'?-1:1));else if(sortField==='__updated__')next.sort((a,b)=>a.updated_at.localeCompare(b.updated_at)*(sortDirection==='desc'?-1:1));else{const field=visibleFields.find(f=>f.id===sortField);if(field)next.sort((a,b)=>compare(a.data?.[field.id],b.data?.[field.id])*(sortDirection==='desc'?-1:1))}return next},[records,visibleFields,query,sortField,sortDirection])
 const addRecord=async()=>{setBusy(true);try{const created=await createRecord(databaseId,'Untitled');setRecords(v=>[created,...v])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const saveRecord=async(record:RecordRow,patch:{title?:string;fieldId?:string;value?:unknown})=>{const nextData=patch.fieldId?{...record.data,[patch.fieldId]:patch.value}:record.data;setRecords(v=>v.map(r=>r.id===record.id?{...r,title:patch.title??r.title,data:nextData}:r));try{const updated=await updateRecord(record.id,{...(patch.title!==undefined?{title:patch.title}:{}),...(patch.fieldId?{data:nextData}:{})});setRecords(v=>v.map(r=>r.id===record.id?updated:r))}catch(e){setError(e instanceof Error?e.message:String(e));void load()}}
 const removeRecord=async(record:RecordRow)=>{if(!window.confirm(`Delete “${record.title}”?`))return;await deleteRecord(record.id);setRecords(v=>v.filter(r=>r.id!==record.id))}
 if(error&&!database)return <div className="db-workspace-error"><h2>Atlas could not open this collection</h2><p>{error}</p></div>
 if(!database)return <div className="db-workspace-loading">Opening collection…</div>
 return <div className="database-workspace">
  <header className="database-workspace-head"><div><span>DATABASE</span><h1>{database.name}</h1><p>{records.length} record{records.length===1?'':'s'} · {visibleFields.length+1} field{visibleFields.length===0?'':'s'}</p></div><div className="database-workspace-head-actions"><Link className="db-page-link" to={`/database/${database.id}/page`}><Sparkles/>Design HQ page</Link><button className="db-primary" onClick={()=>void addRecord()} disabled={busy}><Plus/>New {singular(database.name)}</button></div></header>
  <div className="database-workspace-toolbar"><div className="db-view-switch"><button className={mode==='table'?'active':''} onClick={()=>setMode('table')}><Grid3X3/>Table</button><button className={mode==='gallery'?'active':''} onClick={()=>setMode('gallery')}><LayoutGrid/>Gallery</button><button className={mode==='board'?'active':''} onClick={()=>setMode('board')}><KanbanSquare/>Board</button></div><div className="db-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${database.name}`}/></div><label className="db-sort"><span>Sort</span><select value={sortField} onChange={e=>setSortField(e.target.value)}><option value="__updated__">Last edited</option><option value="__title__">Title</option>{visibleFields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button onClick={()=>setSortDirection(v=>v==='asc'?'desc':'asc')} title={sortDirection==='asc'?'Ascending':'Descending'}>{sortDirection==='asc'?<ArrowUp/>:<ArrowDown/>}</button></label><button className={fieldsOpen?'active db-fields-button':'db-fields-button'} onClick={()=>setFieldsOpen(v=>!v)}><SlidersHorizontal/>Fields</button></div>
  {error&&<div className="db-inline-error">{error}</div>}
  <div className="database-workspace-body">{mode==='table'?<DatabaseTable database={database} records={shown} fields={visibleFields} onSave={saveRecord} onDelete={removeRecord} onAdd={addRecord}/>:mode==='gallery'?<DatabaseGallery database={database} records={shown} fields={visibleFields}/>:<DatabaseBoard database={database} records={shown} fields={visibleFields} boardFields={boardFields} groupFieldId={boardField} onGroupField={setBoardField} onSave={saveRecord}/>}</div>
  {fieldsOpen&&<FieldManager database={database} fields={visibleFields} allFields={fields} onClose={()=>setFieldsOpen(false)} onChanged={load}/>} 
 </div>
}

function DatabaseTable({database,records,fields,onSave,onDelete,onAdd}:{database:Database;records:RecordRow[];fields:Field[];onSave:(r:RecordRow,p:{title?:string;fieldId?:string;value?:unknown})=>void;onDelete:(r:RecordRow)=>void;onAdd:()=>void}){return <div className="db-sheet-wrap"><table className="db-sheet"><thead><tr><th className="db-row-index">#</th><th className="db-title-column">Title</th>{fields.map(f=><th key={f.id}><span>{f.name}</span><small>{fieldTypeLabel(f.type)}</small></th>)}<th className="db-actions-column"/></tr></thead><tbody>{records.map((record,index)=><tr key={record.id}><td className="db-row-index">{index+1}</td><td className="db-title-column"><input value={record.title} onChange={e=>onSave(record,{title:e.target.value})}/><Link title="Open full record page" to={`/database/${database.id}/record/${record.id}`}><ExternalLink/></Link></td>{fields.map(field=><td key={field.id}><CellEditor field={field} value={record.data?.[field.id]} onChange={value=>onSave(record,{fieldId:field.id,value})}/></td>)}<td className="db-actions-column"><button title="Delete record" onClick={()=>void onDelete(record)}><Trash2/></button></td></tr>)}</tbody></table><button className="db-add-row" onClick={()=>void onAdd()}><Plus/>Add record</button></div>}

function CellEditor({field,value,onChange}:{field:Field;value:unknown;onChange:(value:unknown)=>void}){const options=Array.isArray(field.config?.options)?field.config.options.map(String):[];if(field.type==='checkbox')return <input className="db-cell-check" type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>;if(field.type==='date')return <input className="db-cell-input" type="date" value={String(value??'')} onChange={e=>onChange(e.target.value)}/>;if(field.type==='number')return <input className="db-cell-input" type="number" value={value===null||value===undefined?'':String(value)} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/>;if(field.type==='select')return <select className="db-cell-input" value={String(value??'')} onChange={e=>onChange(e.target.value)}><option value="">None</option>{options.map(o=><option key={o}>{o}</option>)}</select>;if(field.type==='multi_select'){const selected=Array.isArray(value)?value.map(String):[];return <div className="db-multi-cell">{options.length?<select multiple value={selected} onChange={e=>onChange(Array.from(e.target.selectedOptions).map(o=>o.value))}>{options.map(o=><option key={o}>{o}</option>)}</select>:<input className="db-cell-input" value={selected.join(', ')} placeholder="comma, separated" onChange={e=>onChange(e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/>}</div>};if(field.type==='long_text')return <textarea className="db-cell-input db-cell-textarea" value={String(value??'')} onChange={e=>onChange(e.target.value)}/>;if(field.type==='image')return <input className="db-cell-input" value={String(value??'')} placeholder="Image URL" onChange={e=>onChange(e.target.value)}/>;return <input className="db-cell-input" type={field.type==='url'?'url':'text'} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>}

function DatabaseGallery({database,records,fields}:{database:Database;records:RecordRow[];fields:Field[]}){const preview=fields.slice(0,4);return <div className="db-native-gallery">{records.map(record=><Link key={record.id} to={`/database/${database.id}/record/${record.id}`} className="db-native-card"><strong>{record.title}</strong>{preview.map(field=>{const value=formatValue(record.data?.[field.id]);return value?<span key={field.id}><small>{field.name}</small>{value}</span>:null})}</Link>)}</div>}

function DatabaseBoard({database,records,fields,boardFields,groupFieldId,onGroupField,onSave}:{database:Database;records:RecordRow[];fields:Field[];boardFields:Field[];groupFieldId:string;onGroupField:(id:string)=>void;onSave:(r:RecordRow,p:{fieldId?:string;value?:unknown})=>void}){const field=fields.find(f=>f.id===groupFieldId);if(!field)return <div className="db-board-empty"><KanbanSquare/><strong>Choose a grouping field</strong><select value={groupFieldId} onChange={e=>onGroupField(e.target.value)}><option value="">Choose field</option>{boardFields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div>;const configured=Array.isArray(field.config?.options)?field.config.options.map(String):[];const values=new Set<string>(configured);records.forEach(r=>{const raw=r.data?.[field.id];(Array.isArray(raw)?raw:[raw]).filter(Boolean).forEach(v=>values.add(String(v)))});values.add('No value');return <div className="db-board-shell"><div className="db-board-controls"><span>Group by</span><select value={groupFieldId} onChange={e=>onGroupField(e.target.value)}>{boardFields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="db-native-board">{Array.from(values).map(value=>{const lane=records.filter(r=>{const raw=r.data?.[field.id];if(value==='No value')return raw===null||raw===undefined||raw===''||(Array.isArray(raw)&&!raw.length);return Array.isArray(raw)?raw.map(String).includes(value):String(raw??'')===value});return <section key={value}><header><strong>{value}</strong><span>{lane.length}</span></header>{lane.map(record=><Link to={`/database/${database.id}/record/${record.id}`} key={record.id} className="db-board-card"><strong>{record.title}</strong>{fields.slice(0,3).filter(f=>f.id!==field.id).map(f=>{const v=formatValue(record.data?.[f.id]);return v?<small key={f.id}>{f.name}: {v}</small>:null})}</Link>)}</section>})}</div></div>}

function FieldManager({database,fields,allFields,onClose,onChanged}:{database:Database;fields:Field[];allFields:Field[];onClose:()=>void;onChanged:()=>Promise<void>}){const[name,setName]=useState(''),[type,setType]=useState<FieldType>('text'),[options,setOptions]=useState(''),[busy,setBusy]=useState(false);const add=async()=>{if(!name.trim())return;setBusy(true);try{const config=['select','multi_select'].includes(type)?{options:options.split('\n').map(x=>x.trim()).filter(Boolean)}:{};await createField(database.id,{name:name.trim(),type,required:false,config},allFields.length);setName('');setOptions('');await onChanged()}finally{setBusy(false)}};const move=async(field:Field,direction:-1|1)=>{const ordered=[...fields].sort((a,b)=>a.position-b.position);const i=ordered.findIndex(f=>f.id===field.id),other=ordered[i+direction];if(!other)return;await Promise.all([updateField(field.id,{position:other.position}),updateField(other.id,{position:field.position})]);await onChanged()};return <aside className="db-field-manager"><div className="db-field-manager-head"><div><span>DATABASE STRUCTURE</span><strong>{database.name} fields</strong></div><button onClick={onClose}><X/></button></div><div className="db-field-manager-scroll"><p className="db-field-intro">Columns are the information every {singular(database.name)} can store. Change them whenever your system evolves.</p><div className="db-built-in-field"><div><strong>Title</strong><span>Built in · every record needs a name</span></div></div>{fields.map((field,index)=><FieldEditor key={field.id} field={field} first={index===0} last={index===fields.length-1} onMove={move} onChanged={onChanged}/>) }<div className="db-new-field"><strong>Add a field</strong><input value={name} onChange={e=>setName(e.target.value)} placeholder="Release date, Moon cycle, Money spent…"/><select value={type} onChange={e=>setType(e.target.value as FieldType)}>{FIELD_TYPES.map(t=><option key={t.value} value={t.value}>{t.label} · {t.hint}</option>)}</select>{['select','multi_select'].includes(type)&&<textarea value={options} onChange={e=>setOptions(e.target.value)} placeholder={'Add one option per line\nIdea\nRecording\nPublished'}/>}<button className="db-primary" disabled={busy||!name.trim()} onClick={()=>void add()}><Plus/>Add field</button></div></div></aside>}

function FieldEditor({field,first,last,onMove,onChanged}:{field:Field;first:boolean;last:boolean;onMove:(f:Field,d:-1|1)=>Promise<void>;onChanged:()=>Promise<void>}){const[name,setName]=useState(field.name),[type,setType]=useState<FieldType>(field.type),[options,setOptions]=useState(Array.isArray(field.config?.options)?field.config.options.map(String).join('\n'):''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{setName(field.name);setType(field.type);setOptions(Array.isArray(field.config?.options)?field.config.options.map(String).join('\n'):'')},[field]);const save=async()=>{setBusy(true);try{const config=['select','multi_select'].includes(type)?{...field.config,options:options.split('\n').map(x=>x.trim()).filter(Boolean)}:field.config;await updateField(field.id,{name:name.trim()||field.name,type,config});await onChanged()}finally{setBusy(false)}};return <div className="db-field-editor"><button className="db-field-editor-summary" onClick={()=>setOpen(v=>!v)}><span><strong>{field.name}</strong><small>{fieldTypeLabel(field.type)}{Array.isArray(field.config?.options)&&field.config.options.length?` · ${field.config.options.length} options`:''}</small></span><SlidersHorizontal/></button>{open&&<div className="db-field-editor-body"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value as FieldType)}>{FIELD_TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label>{['select','multi_select'].includes(type)&&<label>Choices<textarea value={options} onChange={e=>setOptions(e.target.value)} placeholder="One option per line"/></label>}<label className="db-required-row"><input type="checkbox" checked={field.required} onChange={async e=>{await updateField(field.id,{required:e.target.checked});await onChanged()}}/>Required</label><div className="db-field-editor-actions"><button disabled={first} onClick={()=>void onMove(field,-1)}><ArrowLeft/>Move left</button><button disabled={last} onClick={()=>void onMove(field,1)}>Move right<ArrowRight/></button><button onClick={()=>void save()} disabled={busy}>Save</button><button className="danger" onClick={async()=>{if(!window.confirm(`Delete field “${field.name}”?`))return;await deleteField(field.id);await onChanged()}}><Trash2/>Delete</button></div></div>}</div>}

function singular(name:string){const trimmed=name.trim();if(/ies$/i.test(trimmed))return trimmed.replace(/ies$/i,'y');if(/s$/i.test(trimmed)&&!/(ss)$/i.test(trimmed))return trimmed.slice(0,-1);return trimmed||'record'}
function fieldTypeLabel(type:FieldType){return FIELD_TYPES.find(t=>t.value===type)?.label||type}
function formatValue(value:unknown){if(Array.isArray(value))return value.join(', ');if(typeof value==='boolean')return value?'Yes':'No';return String(value??'')}
function compare(a:unknown,b:unknown){if(typeof a==='number'&&typeof b==='number')return a-b;return formatValue(a).localeCompare(formatValue(b),undefined,{numeric:true})}
