import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowDown, ArrowUp, ChevronDown, ExternalLink, GripVertical, Grid3X3, KanbanSquare, LayoutGrid, Plus, Search, Sparkles, Trash2 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useAppContext } from '../App'
import { createField, createRecord, deleteField, deleteRecord, getDatabase, getDatabases, getFields, getRecords, updateDatabase, updateField, updateRecord } from '../lib/data'
import type { Database, Field, FieldType, RecordRow } from '../types'

type ViewMode='table'|'gallery'|'board'
type SortDirection='asc'|'desc'
const FIELD_TYPES:Array<{value:FieldType;label:string;hint:string}>=[
 {value:'text',label:'Text',hint:'Names, authors, locations, short notes'},
 {value:'long_text',label:'Long text',hint:'Descriptions, notes, journal entries'},
 {value:'number',label:'Number',hint:'Counts, ratings, money, quantities'},
 {value:'date',label:'Date',hint:'Deadlines, release dates, reading dates'},
 {value:'checkbox',label:'Checkbox',hint:'Done, paid, favorite, packed'},
 {value:'select',label:'Single select',hint:'One status, type, category, mood'},
 {value:'multi_select',label:'Multi-select',hint:'Genres, tags, ingredients, correspondences'},
 {value:'url',label:'Link',hint:'Websites, bookings, published URLs'},
 {value:'image',label:'Image',hint:'Covers, photos, artwork, receipts'},
 {value:'relation',label:'Relation',hint:'Connect records to another collection'},
]

export default function DatabaseWorkspace(){
 const {databaseId=''}=useParams();const{workspace}=useAppContext()
 const[database,setDatabase]=useState<Database|null>(null),[databases,setDatabases]=useState<Database[]>([]),[fields,setFields]=useState<Field[]>([]),[records,setRecords]=useState<RecordRow[]>([]),[mode,setMode]=useState<ViewMode>('table'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sortField,setSortField]=useState('__manual__'),[sortDirection,setSortDirection]=useState<SortDirection>('asc'),[boardField,setBoardField]=useState(''),[addingField,setAddingField]=useState(false)
 const load=async()=>{setError('');try{const [db,allDbs,nextFields,nextRecords]=await Promise.all([getDatabase(databaseId),getDatabases(workspace.id),getFields(databaseId),getRecords(databaseId)]);setDatabase(db);setDatabases(allDbs);setFields(nextFields);setRecords(nextRecords)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[databaseId,workspace.id])
 const visibleFields=useMemo(()=>fields.filter(f=>f.name.trim().toLowerCase()!=='name').sort((a,b)=>a.position-b.position),[fields])
 const boardFields=useMemo(()=>visibleFields.filter(f=>['select','checkbox'].includes(f.type)),[visibleFields])
 useEffect(()=>{if(!boardField&&boardFields.length)setBoardField(boardFields.find(f=>f.name.toLowerCase()==='status')?.id||boardFields[0].id)},[boardFields,boardField])
 const manualRecords=useMemo(()=>[...records].sort((a,b)=>Number(a.data?.__atlas_order??999999)-Number(b.data?.__atlas_order??999999)||a.created_at.localeCompare(b.created_at)),[records])
 const shown=useMemo(()=>{const q=query.trim().toLowerCase();let next=q?manualRecords.filter(r=>r.title.toLowerCase().includes(q)||visibleFields.some(f=>formatValue(r.data?.[f.id]).toLowerCase().includes(q))):[...manualRecords];if(sortField==='__title__')next.sort((a,b)=>a.title.localeCompare(b.title)*(sortDirection==='desc'?-1:1));else if(sortField==='__updated__')next.sort((a,b)=>a.updated_at.localeCompare(b.updated_at)*(sortDirection==='desc'?-1:1));else if(sortField!=='__manual__'){const field=visibleFields.find(f=>f.id===sortField);if(field)next.sort((a,b)=>compare(a.data?.[field.id],b.data?.[field.id])*(sortDirection==='desc'?-1:1))}return next},[manualRecords,visibleFields,query,sortField,sortDirection])
 const addRecord=async()=>{setBusy(true);try{const created=await createRecord(databaseId,'Untitled');const updated=await updateRecord(created.id,{data:{...created.data,__atlas_order:manualRecords.length}});setRecords(v=>[...v,updated])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const saveRecord=async(record:RecordRow,patch:{title?:string;fieldId?:string;value?:unknown})=>{const nextData=patch.fieldId?{...record.data,[patch.fieldId]:patch.value}:record.data;setRecords(v=>v.map(r=>r.id===record.id?{...r,title:patch.title??r.title,data:nextData}:r));try{const updated=await updateRecord(record.id,{...(patch.title!==undefined?{title:patch.title}:{}),...(patch.fieldId?{data:nextData}:{})});setRecords(v=>v.map(r=>r.id===record.id?updated:r))}catch(e){setError(e instanceof Error?e.message:String(e));void load()}}
 const removeRecord=async(record:RecordRow)=>{if(!window.confirm(`Delete “${record.title}”?`))return;await deleteRecord(record.id);setRecords(v=>v.filter(r=>r.id!==record.id))}
 const renameDatabase=async(name:string)=>{const clean=name.trim();if(!clean||!database||clean===database.name)return;setDatabase({...database,name:clean});try{await updateDatabase(database.id,{name:clean})}catch(e){setError(e instanceof Error?e.message:String(e));void load()}}
 const reorderFields=async(sourceId:string,targetId:string)=>{if(sourceId===targetId)return;const list=[...visibleFields];const from=list.findIndex(f=>f.id===sourceId),to=list.findIndex(f=>f.id===targetId);if(from<0||to<0)return;const[moved]=list.splice(from,1);list.splice(to,0,moved);setFields(current=>current.map(f=>{const i=list.findIndex(x=>x.id===f.id);return i>=0?{...f,position:i+1}:f}));try{await Promise.all(list.map((f,i)=>updateField(f.id,{position:i+1})))}catch(e){setError(e instanceof Error?e.message:String(e));void load()}}
 const reorderRecords=async(sourceId:string,targetId:string)=>{if(sourceId===targetId||sortField!=='__manual__')return;const list=[...manualRecords];const from=list.findIndex(r=>r.id===sourceId),to=list.findIndex(r=>r.id===targetId);if(from<0||to<0)return;const[moved]=list.splice(from,1);list.splice(to,0,moved);const optimistic=list.map((r,i)=>({...r,data:{...r.data,__atlas_order:i}}));setRecords(optimistic);try{await Promise.all(optimistic.map((r,i)=>updateRecord(r.id,{data:{...r.data,__atlas_order:i}})))}catch(e){setError(e instanceof Error?e.message:String(e));void load()}}
 if(error&&!database)return <div className="db-workspace-error"><h2>Atlas could not open this collection</h2><p>{error}</p></div>
 if(!database)return <div className="db-workspace-loading">Opening collection…</div>
 return <div className="database-workspace">
  <header className="database-workspace-head"><div><span>DATABASE</span><DatabaseName value={database.name} onSave={renameDatabase}/><p>{records.length} record{records.length===1?'':'s'} · {visibleFields.length+1} field{visibleFields.length===0?'':'s'} · Click the name or any column to edit it</p></div><div className="database-workspace-head-actions"><Link className="db-page-link" to={`/database/${database.id}/page`}><Sparkles/>Design HQ page</Link><button className="db-primary" onClick={()=>void addRecord()} disabled={busy}><Plus/>New {singular(database.name)}</button></div></header>
  <div className="database-workspace-toolbar"><div className="db-view-switch"><button className={mode==='table'?'active':''} onClick={()=>setMode('table')}><Grid3X3/>Table</button><button className={mode==='gallery'?'active':''} onClick={()=>setMode('gallery')}><LayoutGrid/>Gallery</button><button className={mode==='board'?'active':''} onClick={()=>setMode('board')}><KanbanSquare/>Board</button></div><div className="db-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${database.name}`}/></div><label className="db-sort"><span>Sort</span><select value={sortField} onChange={e=>setSortField(e.target.value)}><option value="__manual__">Manual order</option><option value="__updated__">Last edited</option><option value="__title__">Title</option>{visibleFields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button onClick={()=>setSortDirection(v=>v==='asc'?'desc':'asc')} disabled={sortField==='__manual__'} title={sortDirection==='asc'?'Ascending':'Descending'}>{sortDirection==='asc'?<ArrowUp/>:<ArrowDown/>}</button></label><button className="db-inline-add-field-button" onClick={()=>{setMode('table');setAddingField(true)}}><Plus/>Field</button></div>
  {error&&<div className="db-inline-error">{error}</div>}
  <div className="database-workspace-body">{mode==='table'?<DatabaseTable database={database} databases={databases} records={shown} fields={visibleFields} allFields={fields} manualOrder={sortField==='__manual__'} addingField={addingField} onAddingField={setAddingField} onSave={saveRecord} onDelete={removeRecord} onAdd={addRecord} onChanged={load} onReorderFields={reorderFields} onReorderRecords={reorderRecords}/>:mode==='gallery'?<DatabaseGallery database={database} records={shown} fields={visibleFields}/>:<DatabaseBoard database={database} records={shown} fields={visibleFields} boardFields={boardFields} groupFieldId={boardField} onGroupField={setBoardField} onSave={saveRecord}/>}</div>
 </div>
}

function DatabaseName({value,onSave}:{value:string;onSave:(name:string)=>void}){const[local,setLocal]=useState(value);useEffect(()=>setLocal(value),[value]);return <input className="db-inline-name" value={local} onChange={e=>setLocal(e.target.value)} onBlur={()=>onSave(local)} onKeyDown={e=>{if(e.key==='Enter')(e.currentTarget as HTMLInputElement).blur();if(e.key==='Escape'){setLocal(value);(e.currentTarget as HTMLInputElement).blur()}}}/>} 

function DatabaseTable({database,databases,records,fields,allFields,manualOrder,addingField,onAddingField,onSave,onDelete,onAdd,onChanged,onReorderFields,onReorderRecords}:{database:Database;databases:Database[];records:RecordRow[];fields:Field[];allFields:Field[];manualOrder:boolean;addingField:boolean;onAddingField:(v:boolean)=>void;onSave:(r:RecordRow,p:{title?:string;fieldId?:string;value?:unknown})=>void;onDelete:(r:RecordRow)=>void;onAdd:()=>void;onChanged:()=>Promise<void>;onReorderFields:(s:string,t:string)=>Promise<void>;onReorderRecords:(s:string,t:string)=>Promise<void>}){
 const dragField=useRef(''),dragRecord=useRef('')
 return <div className="db-sheet-wrap"><table className="db-sheet"><thead><tr><th className="db-row-index">#</th><th className="db-title-column"><span>Title</span><small>Built in · record name</small></th>{fields.map(field=><FieldHeader key={field.id} field={field} databases={databases} onChanged={onChanged} onDragStart={()=>{dragField.current=field.id}} onDrop={()=>void onReorderFields(dragField.current,field.id)}/>)}<th className="db-add-field-column">{addingField?<InlineAddField database={database} position={allFields.length} databases={databases} onCancel={()=>onAddingField(false)} onAdded={async()=>{onAddingField(false);await onChanged()}}/>:<button onClick={()=>onAddingField(true)}><Plus/>Add field</button>}</th><th className="db-actions-column"/></tr></thead><tbody>{records.map((record,index)=><tr key={record.id} draggable={manualOrder} onDragStart={()=>{dragRecord.current=record.id}} onDragOver={e=>{if(manualOrder)e.preventDefault()}} onDrop={()=>void onReorderRecords(dragRecord.current,record.id)} className={manualOrder?'db-draggable-row':''}><td className="db-row-index">{manualOrder?<GripVertical/>:index+1}</td><td className="db-title-column"><input value={record.title} onChange={e=>onSave(record,{title:e.target.value})}/><Link title="Open full record page" to={`/database/${database.id}/record/${record.id}`}><ExternalLink/></Link></td>{fields.map(field=><td key={field.id}><CellEditor field={field} value={record.data?.[field.id]} onChange={value=>onSave(record,{fieldId:field.id,value})}/></td>)}<td className="db-add-field-column db-empty-column"/><td className="db-actions-column"><button title="Delete record" onClick={()=>void onDelete(record)}><Trash2/></button></td></tr>)}</tbody></table><button className="db-add-row" onClick={()=>void onAdd()}><Plus/>Add record</button></div>
}

function FieldHeader({field,databases,onChanged,onDragStart,onDrop}:{field:Field;databases:Database[];onChanged:()=>Promise<void>;onDragStart:()=>void;onDrop:()=>void}){const[open,setOpen]=useState(false),[name,setName]=useState(field.name),[type,setType]=useState<FieldType>(field.type),[options,setOptions]=useState(Array.isArray(field.config?.options)?field.config.options.map(String).join('\n'):''),[target,setTarget]=useState(String(field.config?.target_database_id||''));useEffect(()=>{setName(field.name);setType(field.type);setOptions(Array.isArray(field.config?.options)?field.config.options.map(String).join('\n'):'');setTarget(String(field.config?.target_database_id||''))},[field.id,field.name,field.type,field.config]);const save=async()=>{const config={...field.config,...(['select','multi_select'].includes(type)?{options:options.split(/\n|,/).map(x=>x.trim()).filter(Boolean)}:{}),...(type==='relation'?{target_database_id:target}:{})};await updateField(field.id,{name:name.trim()||field.name,type,config});setOpen(false);await onChanged()};const remove=async()=>{if(!window.confirm(`Delete field “${field.name}”? Existing values in this column will no longer be shown.`))return;await deleteField(field.id);await onChanged()};return <th className={`db-field-header ${open?'editing':''}`} draggable={!open} onDragStart={onDragStart} onDragOver={e=>e.preventDefault()} onDrop={onDrop}>{!open?<button className="db-field-header-summary" onClick={()=>setOpen(true)}><GripVertical/><span><strong>{field.name}</strong><small>{fieldTypeLabel(field.type)}</small></span><ChevronDown/></button>:<div className="db-field-inline-editor"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Field name"/><select value={type} onChange={e=>setType(e.target.value as FieldType)}>{FIELD_TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select>{['select','multi_select'].includes(type)&&<textarea value={options} onChange={e=>setOptions(e.target.value)} placeholder={'One option per line\nIdea\nRecording\nPublished'}/>} {type==='relation'&&<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose database…</option>{databases.map(db=><option key={db.id} value={db.id}>{db.name}</option>)}</select>}<label className="db-inline-required"><input type="checkbox" checked={field.required} onChange={async e=>{await updateField(field.id,{required:e.target.checked});await onChanged()}}/>Required</label><div><button className="db-field-save" onClick={()=>void save()}>Save</button><button onClick={()=>setOpen(false)}>Cancel</button><button className="danger" onClick={()=>void remove()}><Trash2/>Delete</button></div></div>}</th>}

function InlineAddField({database,position,databases,onCancel,onAdded}:{database:Database;position:number;databases:Database[];onCancel:()=>void;onAdded:()=>Promise<void>}){const[name,setName]=useState(''),[type,setType]=useState<FieldType>('text'),[options,setOptions]=useState(''),[target,setTarget]=useState(''),[busy,setBusy]=useState(false);const add=async()=>{if(!name.trim())return;setBusy(true);try{const config={...(['select','multi_select'].includes(type)?{options:options.split(/\n|,/).map(x=>x.trim()).filter(Boolean)}:{}),...(type==='relation'?{target_database_id:target}:{})};await createField(database.id,{name:name.trim(),type,required:false,config},position);await onAdded()}finally{setBusy(false)}};return <div className="db-inline-add-field"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Field name"/><select value={type} onChange={e=>setType(e.target.value as FieldType)}>{FIELD_TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select>{['select','multi_select'].includes(type)&&<textarea value={options} onChange={e=>setOptions(e.target.value)} placeholder={'Options, one per line\nIdea\nRecording\nPublished'}/>} {type==='relation'&&<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose database…</option>{databases.map(db=><option key={db.id} value={db.id}>{db.name}</option>)}</select>}<div><button className="db-field-save" disabled={busy||!name.trim()} onClick={()=>void add()}><Plus/>Add</button><button onClick={onCancel}>Cancel</button></div></div>}

function CellEditor({field,value,onChange}:{field:Field;value:unknown;onChange:(value:unknown)=>void}){const options=Array.isArray(field.config?.options)?field.config.options.map(String):[];if(field.type==='checkbox')return <input className="db-cell-check" type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>;if(field.type==='date')return <input className="db-cell-input" type="date" value={String(value??'')} onChange={e=>onChange(e.target.value)}/>;if(field.type==='number')return <input className="db-cell-input" type="number" value={value===null||value===undefined?'':String(value)} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/>;if(field.type==='select')return <select className="db-cell-input" value={String(value??'')} onChange={e=>onChange(e.target.value)}><option value="">None</option>{options.map(o=><option key={o}>{o}</option>)}</select>;if(field.type==='multi_select'){const selected=Array.isArray(value)?value.map(String):[];return <div className="db-multi-cell">{options.length?<div className="db-multi-checks">{options.map(o=><label key={o}><input type="checkbox" checked={selected.includes(o)} onChange={e=>onChange(e.target.checked?[...selected,o]:selected.filter(x=>x!==o))}/><span>{o}</span></label>)}</div>:<input className="db-cell-input" value={selected.join(', ')} placeholder="Add options in the column header" onChange={e=>onChange(e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/>}</div>};if(field.type==='long_text')return <textarea className="db-cell-input db-cell-textarea" value={String(value??'')} onChange={e=>onChange(e.target.value)}/>;if(field.type==='image')return <input className="db-cell-input" value={String(value??'')} placeholder="Image URL" onChange={e=>onChange(e.target.value)}/>;return <input className="db-cell-input" type={field.type==='url'?'url':'text'} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>}

function DatabaseGallery({database,records,fields}:{database:Database;records:RecordRow[];fields:Field[]}){const preview=fields.slice(0,4);return <div className="db-native-gallery">{records.map(record=><Link key={record.id} to={`/database/${database.id}/record/${record.id}`} className="db-native-card"><strong>{record.title}</strong>{preview.map(field=>{const value=formatValue(record.data?.[field.id]);return value?<span key={field.id}><small>{field.name}</small>{value}</span>:null})}</Link>)}</div>}

function DatabaseBoard({database,records,fields,boardFields,groupFieldId,onGroupField,onSave}:{database:Database;records:RecordRow[];fields:Field[];boardFields:Field[];groupFieldId:string;onGroupField:(id:string)=>void;onSave:(r:RecordRow,p:{fieldId?:string;value?:unknown})=>void}){const field=fields.find(f=>f.id===groupFieldId),drag=useRef('');if(!field)return <div className="db-board-empty"><KanbanSquare/><strong>Create a Single select or Checkbox field to group this board.</strong></div>;const configured=Array.isArray(field.config?.options)?field.config.options.map(String):[];const values=new Set<string>(configured);records.forEach(r=>{const raw=r.data?.[field.id];if(raw!==null&&raw!==undefined&&raw!=='')values.add(field.type==='checkbox'?(raw?'Checked':'Unchecked'):String(raw))});values.add('No value');const drop=(value:string)=>{const record=records.find(r=>r.id===drag.current);if(!record)return;let next:unknown=value==='No value'?'':value;if(field.type==='checkbox')next=value==='Checked';onSave(record,{fieldId:field.id,value:next})};return <div className="db-board-shell"><div className="db-board-controls"><span>Group by</span><select value={groupFieldId} onChange={e=>onGroupField(e.target.value)}>{boardFields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="db-native-board">{Array.from(values).map(value=>{const lane=records.filter(r=>{const raw=r.data?.[field.id];if(value==='No value')return raw===null||raw===undefined||raw==='';if(field.type==='checkbox')return (raw?'Checked':'Unchecked')===value;return String(raw??'')===value});return <section key={value} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(value)}><header><strong>{value}</strong><span>{lane.length}</span></header>{lane.map(record=><Link draggable onDragStart={()=>{drag.current=record.id}} to={`/database/${database.id}/record/${record.id}`} key={record.id} className="db-board-card"><strong>{record.title}</strong>{fields.slice(0,3).filter(f=>f.id!==field.id).map(f=>{const v=formatValue(record.data?.[f.id]);return v?<small key={f.id}>{f.name}: {v}</small>:null})}</Link>)}</section>})}</div></div>}

function fieldTypeLabel(type:FieldType){return FIELD_TYPES.find(t=>t.value===type)?.label||type}
function formatValue(value:unknown){if(Array.isArray(value))return value.join(', ');if(value===true)return'Yes';if(value===false)return'No';return String(value??'')}
function compare(a:unknown,b:unknown){const an=typeof a==='number'?a:Number.NaN,bn=typeof b==='number'?b:Number.NaN;if(!Number.isNaN(an)&&!Number.isNaN(bn))return an-bn;return formatValue(a).localeCompare(formatValue(b),undefined,{numeric:true,sensitivity:'base'})}
function singular(name:string){const clean=name.trim();if(/ies$/i.test(clean))return clean.replace(/ies$/i,'y');if(/ses$/i.test(clean))return clean.replace(/es$/i,'');if(/s$/i.test(clean)&&!/(ss|us)$/i.test(clean))return clean.slice(0,-1);return clean||'record'}
