import { useEffect, useMemo, useState, type PointerEvent as ReactPointerEvent, type ReactNode } from 'react'
import { ArrowDown, ArrowUp, BarChart3, Columns2, Database, Grip, Heading, Image, LayoutGrid, List, Minus, MousePointer2, Palette, Pencil, Plus, Quote, Rows3, Settings2, SlidersHorizontal, Trash2, Type, X } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useAppContext } from '../App'
import FieldInput from '../components/FieldInput'
import { createPageBlock, createRecord, deletePageBlock, getDatabase, getDatabases, getFields, getOrCreateContextPage, getPage, getPageBlocks, getRecord, getRecords, updatePage, updatePageBlock, updateRecord } from '../lib/data'
import { displayValue } from '../lib/value'
import type { Database as DatabaseType, Field, Page, PageBlock, PageBlockType, RecordRow } from '../types'

type Kind='home'|'page'|'database'|'record'
type Width='full'|'half'|'third'
type Mode='table'|'gallery'|'board'
type LayoutMode='flow'|'canvas'

export default function UniversalPage({kind}:{kind:Kind}){
 const params=useParams();const{workspace}=useAppContext()
 const[page,setPage]=useState<Page|null>(null),[blocks,setBlocks]=useState<PageBlock[]>([]),[databases,setDatabases]=useState<DatabaseType[]>([]),[database,setDatabase]=useState<DatabaseType|null>(null),[record,setRecord]=useState<RecordRow|null>(null),[fields,setFields]=useState<Field[]>([])
 const[editing,setEditing]=useState(false),[dataOpen,setDataOpen]=useState(false),[styleOpen,setStyleOpen]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null),[error,setError]=useState('')
 const load=async()=>{setError('');try{const all=await getDatabases(workspace.id);setDatabases(all);let p:Page;let db:DatabaseType|null=null;let rec:RecordRow|null=null;if(kind==='page')p=await getPage(params.pageId||'');else if(kind==='home')p=await getOrCreateContextPage(workspace.id,'home','Home',{icon:'✦'});else if(kind==='database'){db=await getDatabase(params.databaseId||'');p=await getOrCreateContextPage(workspace.id,'database',db.name,{databaseId:db.id,icon:db.icon||'✦'})}else{db=await getDatabase(params.databaseId||'');rec=await getRecord(params.recordId||'');p=await getOrCreateContextPage(workspace.id,'record',rec.title,{databaseId:db.id,recordId:rec.id,icon:db.icon||'✦'})}setDatabase(db);setRecord(rec);const fs=db?await getFields(db.id):[];setFields(fs);setPage(p);let loaded=await getPageBlocks(p.id);if(!loaded.length&&kind==='database'&&db){await createPageBlock(p.id,'database_view',0,{width:'full',databaseId:db.id,mode:'gallery',title:db.name,limit:24,cardBackground:'#ffffff'});loaded=await getPageBlocks(p.id)}if(!loaded.length&&kind==='record'&&rec){await createPageBlock(p.id,'property',0,{width:'full',fieldId:'__title__',label:'',display:'hero'});for(let i=0;i<Math.min(fs.length,6);i++)await createPageBlock(p.id,'property',i+1,{width:i<2?'half':'third',fieldId:fs[i].id,label:fs[i].name,display:'default'});loaded=await getPageBlocks(p.id)}setBlocks(loaded)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[workspace.id,kind,params.pageId,params.databaseId,params.recordId])
 const layoutMode=(page?.settings?.layoutMode||'flow')as LayoutMode
 const selected=blocks.find(b=>b.id===selectedId)||null
 const patchPage=async(patch:Record<string,unknown>)=>{if(!page)return;const settings={...page.settings,...patch};setPage({...page,settings});await updatePage(page.id,{settings})}
 const add=async(type:PageBlockType)=>{if(!page)return;let config:Record<string,unknown>={width:'full',x:60+(blocks.length%4)*60,y:80+blocks.length*38,pixelWidth:320,minHeight:100,background:'transparent',textColor:'inherit',radius:16,padding:14};if(type==='heading')config={...config,text:'New heading',fontSize:36};if(type==='text')config={...config,text:'Start writing…',fontSize:17};if(type==='callout')config={...config,text:'Add a note…',background:'#f0ebe3'};if(type==='image')config={...config,url:'',fit:'cover',minHeight:240};if(type==='database_view')config={...config,databaseId:database?.id||databases[0]?.id||'',mode:'gallery',title:'',limit:12,cardBackground:'#ffffff',pixelWidth:720};if(type==='property')config={...config,fieldId:record?'__title__':fields[0]?.id||'',label:'',display:'default'};if(type==='metric')config={...config,label:'Total',databaseId:database?.id||databases[0]?.id||'',operation:'count'};if(type==='progress')config={...config,label:'Progress',fieldId:fields.find(f=>f.type==='number')?.id||'',value:50,max:100};if(type==='button')config={...config,label:'Button',url:''};const created=await createPageBlock(page.id,type,blocks.length,config);setBlocks(x=>[...x,created]);setSelectedId(created.id)}
 const updateBlock=async(id:string,config:Record<string,unknown>)=>{const next=await updatePageBlock(id,{config});setBlocks(x=>x.map(b=>b.id===id?next:b))}
 const move=async(index:number,direction:-1|1)=>{const other=index+direction;if(other<0||other>=blocks.length)return;const a=blocks[index],b=blocks[other],next=[...blocks];next[index]=b;next[other]=a;setBlocks(next);await Promise.all([updatePageBlock(a.id,{position:b.position}),updatePageBlock(b.id,{position:a.position})])}
 if(error)return <div className="atlas-error"><h2>Atlas could not open this page</h2><p>{error}</p><p>Run <code>supabase/004_universal_pages.sql</code> if needed.</p></div>
 if(!page)return <div className="atlas-loading"><div className="spinner"/><p>Opening page…</p></div>
 return <div className={`atlas-page ${editing?'editing':''} layout-${layoutMode}`} style={{background:String(page.settings?.background||'#fbfaf7'),color:String(page.settings?.textColor||'#211e1a')}}>
  <header className="atlas-page-toolbar"><div className="atlas-context">{kind==='home'?'Home':kind==='database'?database?.name:kind==='record'?`${database?.name} / ${record?.title}`:'Page'}</div><div className="atlas-toolbar-actions"><button onClick={()=>setDataOpen(true)}><Database/>Data</button><button onClick={()=>setStyleOpen(v=>!v)}><Palette/>Page style</button><button className={editing?'active':''} onClick={()=>{setEditing(v=>!v);setSelectedId(null)}}><Pencil/>{editing?'Done':'Edit page'}</button></div></header>
  {page.cover&&<div className="atlas-page-cover" style={{backgroundImage:`url(${page.cover})`}}/>}
  <div className={editing?'atlas-editor-shell':'atlas-view-shell'}>
   {editing&&<ElementPalette onAdd={add} canProperty={Boolean(record)} />}
   <main className="atlas-page-canvas">
    <div className="atlas-page-heading"><div className="atlas-page-icon">{page.icon||'✦'}</div><input value={page.title} readOnly={!editing} onChange={e=>setPage({...page,title:e.target.value})} onBlur={()=>updatePage(page.id,{title:page.title})}/></div>
    {styleOpen&&<PageStyle page={page} layoutMode={layoutMode} setPage={setPage} savePage={updatePage} patchPage={patchPage}/>} 
    {editing&&<div className="atlas-layout-switch"><span>Layout</span><button className={layoutMode==='flow'?'active':''} onClick={()=>patchPage({layoutMode:'flow'})}>Flow</button><button className={layoutMode==='canvas'?'active':''} onClick={()=>patchPage({layoutMode:'canvas'})}>Freeform canvas</button>{layoutMode==='canvas'&&<label>Height <input type="number" min="500" step="100" value={Number(page.settings?.canvasHeight||1000)} onChange={e=>patchPage({canvasHeight:Number(e.target.value)})}/></label>}</div>}
    <div className="atlas-component-grid" style={layoutMode==='canvas'?{height:Number(page.settings?.canvasHeight||1000)}:undefined}>{blocks.map((b,i)=><Block key={b.id} block={b} editing={editing} selected={selectedId===b.id} layoutMode={layoutMode} index={i} total={blocks.length} databases={databases} record={record} fields={fields} onSelect={()=>setSelectedId(b.id)} onMove={d=>move(i,d)} onRecordChange={setRecord} onChange={config=>updateBlock(b.id,config)} onDelete={async()=>{await deletePageBlock(b.id);setBlocks(x=>x.filter(y=>y.id!==b.id));if(selectedId===b.id)setSelectedId(null)}}/>)}</div>
   </main>
   {editing&&<Inspector block={selected} fields={fields} databases={databases} record={record} onChange={config=>selected&&updateBlock(selected.id,config)}/>} 
  </div>
  {dataOpen&&<DataDrawer database={database} record={record} databases={databases} fields={fields} onClose={()=>setDataOpen(false)} onRecordChange={setRecord}/>} 
 </div>
}

function ElementPalette({onAdd,canProperty}:{onAdd:(t:PageBlockType)=>void;canProperty:boolean}){return <aside className="atlas-element-palette"><div className="atlas-panel-title"><Plus/>Add</div><PanelGroup title="Text"><PaletteButton icon={<Heading/>} label="Heading" onClick={()=>onAdd('heading')}/><PaletteButton icon={<Type/>} label="Text" onClick={()=>onAdd('text')}/><PaletteButton icon={<Quote/>} label="Callout" onClick={()=>onAdd('callout')}/></PanelGroup><PanelGroup title="Data"><PaletteButton icon={<Database/>} label="Database view" onClick={()=>onAdd('database_view')}/>{canProperty&&<PaletteButton icon={<SlidersHorizontal/>} label="Property" onClick={()=>onAdd('property')}/>}<PaletteButton icon={<BarChart3/>} label="Metric" onClick={()=>onAdd('metric')}/><PaletteButton icon={<BarChart3/>} label="Progress" onClick={()=>onAdd('progress')}/></PanelGroup><PanelGroup title="Media & actions"><PaletteButton icon={<Image/>} label="Image" onClick={()=>onAdd('image')}/><PaletteButton icon={<MousePointer2/>} label="Button" onClick={()=>onAdd('button')}/><PaletteButton icon={<Minus/>} label="Divider" onClick={()=>onAdd('divider')}/></PanelGroup></aside>}
function PanelGroup({title,children}:{title:string;children:ReactNode}){return <div className="atlas-palette-group"><span>{title}</span><div>{children}</div></div>}
function PaletteButton({icon,label,onClick}:{icon:ReactNode;label:string;onClick:()=>void}){return <button onClick={onClick}>{icon}<span>{label}</span></button>}

function PageStyle({page,layoutMode,setPage,savePage,patchPage}:{page:Page;layoutMode:LayoutMode;setPage:(p:Page)=>void;savePage:(id:string,p:Partial<Page>)=>Promise<unknown>;patchPage:(p:Record<string,unknown>)=>Promise<void>}){return <div className="atlas-style-strip"><label>Icon<input value={page.icon||''} onChange={e=>setPage({...page,icon:e.target.value})} onBlur={()=>savePage(page.id,{icon:page.icon})}/></label><label>Cover<input value={page.cover||''} placeholder="Image URL" onChange={e=>setPage({...page,cover:e.target.value})} onBlur={()=>savePage(page.id,{cover:page.cover})}/></label><label>Background<input type="color" value={String(page.settings?.background||'#fbfaf7')} onChange={e=>patchPage({background:e.target.value})}/></label><label>Text<input type="color" value={String(page.settings?.textColor||'#211e1a')} onChange={e=>patchPage({textColor:e.target.value})}/></label><label>Page width<select value={String(page.settings?.pageWidth||'wide')} onChange={e=>patchPage({pageWidth:e.target.value})}><option value="compact">Compact</option><option value="wide">Wide</option><option value="full">Full</option></select></label><label>Layout<strong>{layoutMode==='flow'?'Responsive flow':'Freeform canvas'}</strong></label></div>}

function Block({block,editing,selected,layoutMode,index,total,databases,record,fields,onSelect,onMove,onRecordChange,onChange,onDelete}:{block:PageBlock;editing:boolean;selected:boolean;layoutMode:LayoutMode;index:number;total:number;databases:DatabaseType[];record:RecordRow|null;fields:Field[];onSelect:()=>void;onMove:(d:-1|1)=>void;onRecordChange:(r:RecordRow)=>void;onChange:(c:Record<string,unknown>)=>void;onDelete:()=>void}){
 const[config,setConfig]=useState(block.config);useEffect(()=>setConfig(block.config),[block.config]);const save=(patch:Record<string,unknown>)=>{const next={...config,...patch};setConfig(next);void onChange(next)};const width=(config.width||'full')as Width
 const drag=(e:ReactPointerEvent<HTMLButtonElement>)=>{if(layoutMode!=='canvas')return;e.preventDefault();const startX=e.clientX,startY=e.clientY,originX=Number(config.x||0),originY=Number(config.y||0);const target=e.currentTarget;target.setPointerCapture(e.pointerId);const move=(ev:PointerEvent)=>setConfig(c=>({...c,x:Math.max(0,originX+ev.clientX-startX),y:Math.max(0,originY+ev.clientY-startY)}));const up=()=>{target.removeEventListener('pointermove',move as EventListener);target.removeEventListener('pointerup',up);setConfig(c=>{void onChange(c);return c})};target.addEventListener('pointermove',move as EventListener);target.addEventListener('pointerup',up)}
 const style:React.CSSProperties={background:String(config.background||'transparent'),color:String(config.textColor||'inherit'),borderRadius:Number(config.radius||16),padding:Number(config.padding??14)};if(layoutMode==='canvas'){style.left=Number(config.x||0);style.top=Number(config.y||0);style.width=Number(config.pixelWidth||320);style.minHeight=Number(config.minHeight||80)}
 const tools=editing?<div className="atlas-block-tools">{layoutMode==='canvas'?<button className="drag-handle" onPointerDown={drag}><Grip/></button>:<><button disabled={index===0} onClick={()=>onMove(-1)}><ArrowUp/></button><button disabled={index===total-1} onClick={()=>onMove(1)}><ArrowDown/></button><button onClick={()=>save({width:width==='full'?'half':width==='half'?'third':'full'})}><Columns2/></button></>}<button onClick={onDelete}><Trash2/></button></div>:null
 const cls=`atlas-block width-${width} ${selected?'selected':''}`
 return <section className={cls} style={style} onClick={editing?onSelect:undefined}>{tools}{block.type==='divider'?<hr/>:block.type==='database_view'?<DatabaseView config={config} editing={editing} databases={databases} save={save}/>:block.type==='property'?<Property config={config} editing={editing} record={record} fields={fields} save={save} onRecordChange={onRecordChange}/>:block.type==='metric'?<Metric config={config} editing={editing} databases={databases} save={save}/>:block.type==='progress'?<Progress config={config} editing={editing} record={record} fields={fields} save={save}/>:block.type==='button'?<Button config={config} editing={editing} save={save}/>:block.type==='image'?<ImageBlock config={config} editing={editing} save={save}/>:<TextBlock type={block.type} config={config} editing={editing} save={save}/>}</section>
}
function TextBlock({type,config,editing,save}:{type:PageBlockType;config:Record<string,unknown>;editing:boolean;save:(p:Record<string,unknown>)=>void}){const Tag=(type==='heading'?'h2':'div')as'h2'|'div';return <Tag contentEditable={editing} suppressContentEditableWarning className="atlas-editable" style={{fontSize:Number(config.fontSize||undefined)}} onBlur={e=>save({text:e.currentTarget.textContent||''})}>{String(config.text||'')}</Tag>}
function ImageBlock({config,editing,save}:{config:Record<string,unknown>;editing:boolean;save:(p:Record<string,unknown>)=>void}){return <>{config.url?<img src={String(config.url)} alt="" style={{objectFit:String(config.fit||'cover')as'cover'|'contain'}}/>:<div className="atlas-image-placeholder">Image</div>}{editing&&<input value={String(config.url||'')} placeholder="Image URL" onChange={e=>save({url:e.target.value})}/>}</>}
function DatabaseView({config,editing,databases,save}:{config:Record<string,unknown>;editing:boolean;databases:DatabaseType[];save:(p:Record<string,unknown>)=>void}){const id=String(config.databaseId||'');const[records,setRecords]=useState<RecordRow[]>([]);useEffect(()=>{if(!id){setRecords([]);return}getRecords(id).then(setRecords).catch(console.error)},[id]);const mode=(config.mode||'gallery')as Mode;const shown=records.slice(0,Number(config.limit||12));return <div className="atlas-data-view">{editing&&<div className="atlas-data-view-controls"><input value={String(config.title||'')} placeholder="View title" onChange={e=>save({title:e.target.value})}/><select value={id} onChange={e=>save({databaseId:e.target.value})}>{databases.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><div className="atlas-mode-buttons"><button className={mode==='table'?'active':''} onClick={()=>save({mode:'table'})}><List/></button><button className={mode==='gallery'?'active':''} onClick={()=>save({mode:'gallery'})}><LayoutGrid/></button><button className={mode==='board'?'active':''} onClick={()=>save({mode:'board'})}><Rows3/></button></div></div>}{Boolean(config.title)&&<h3>{String(config.title)}</h3>}<Records records={shown} databaseId={id} mode={mode}/></div>}
function Records({records,databaseId,mode}:{records:RecordRow[];databaseId:string;mode:Mode}){if(!records.length)return <div className="atlas-empty-component">No records yet.</div>;if(mode==='gallery')return <div className="atlas-gallery">{records.map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`} className="atlas-record-card"><strong>{r.title}</strong><span>Open</span></Link>)}</div>;if(mode==='board')return <div className="atlas-board"><div><b>Records</b>{records.map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}>{r.title}</Link>)}</div></div>;return <div className="atlas-table-list">{records.map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}><span>{r.title}</span><span>↗</span></Link>)}</div>}
function Property({config,editing,record,fields,save,onRecordChange}:{config:Record<string,unknown>;editing:boolean;record:RecordRow|null;fields:Field[];save:(p:Record<string,unknown>)=>void;onRecordChange:(r:RecordRow)=>void}){const fieldId=String(config.fieldId||'');const field=fields.find(f=>f.id===fieldId);const value=fieldId==='__title__'?record?.title:field?record?.data?.[field.id]:'';const label=String(config.label||field?.name||'');const change=async(v:unknown)=>{if(!record)return;const next=fieldId==='__title__'?await updateRecord(record.id,{title:String(v??'')}):field?await updateRecord(record.id,{data:{...record.data,[field.id]:v}}):record;onRecordChange(next)};return <div className={`atlas-property-display ${config.display==='hero'?'hero':''}`}>{editing&&<div className="atlas-inline-config"><select value={fieldId} onChange={e=>save({fieldId:e.target.value})}><option value="__title__">Record title</option>{fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input value={label} placeholder="Label" onChange={e=>save({label:e.target.value})}/></div>}{label&&config.display!=='hero'&&<span>{label}</span>}{editing&&record?(fieldId==='__title__'?<input className="atlas-property-live-input" value={record.title} onChange={e=>onRecordChange({...record,title:e.target.value})} onBlur={e=>change(e.target.value)}/>:field?<FieldInput field={field} value={value} onChange={change}/>:<strong>Choose a property</strong>):<strong>{displayValue(value,field)||'Empty'}</strong>}</div>}
function Metric({config,editing,databases,save}:{config:Record<string,unknown>;editing:boolean;databases:DatabaseType[];save:(p:Record<string,unknown>)=>void}){const id=String(config.databaseId||'');const[count,setCount]=useState(0);useEffect(()=>{if(id)getRecords(id).then(r=>setCount(r.length)).catch(console.error)},[id]);return <div className="atlas-metric">{editing&&<><input value={String(config.label||'')} onChange={e=>save({label:e.target.value})}/><select value={id} onChange={e=>save({databaseId:e.target.value})}>{databases.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></>}<strong>{count}</strong><span>{String(config.label||'records')}</span></div>}
function Progress({config,editing,record,fields,save}:{config:Record<string,unknown>;editing:boolean;record:RecordRow|null;fields:Field[];save:(p:Record<string,unknown>)=>void}){const field=fields.find(f=>f.id===String(config.fieldId||''));const raw=field&&record?record.data?.[field.id]:config.value;const value=Math.max(0,Number(raw||0)),max=Math.max(1,Number(config.max||100)),pct=Math.min(100,(value/max)*100);return <div className="atlas-progress"><div><strong>{String(config.label||'Progress')}</strong><span>{Math.round(pct)}%</span></div><div className="atlas-progress-track"><i style={{width:`${pct}%`}}/></div>{editing&&<div className="atlas-inline-config"><select value={String(config.fieldId||'')} onChange={e=>save({fieldId:e.target.value})}><option value="">Manual value</option>{fields.filter(f=>f.type==='number').map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input type="number" value={Number(config.max||100)} onChange={e=>save({max:Number(e.target.value)})}/></div>}</div>}
function Button({config,editing,save}:{config:Record<string,unknown>;editing:boolean;save:(p:Record<string,unknown>)=>void}){return <div className="atlas-button-component">{editing&&<div className="atlas-inline-config"><input value={String(config.label||'')} onChange={e=>save({label:e.target.value})}/><input value={String(config.url||'')} placeholder="URL" onChange={e=>save({url:e.target.value})}/></div>}<a href={String(config.url||'#')} target={config.url?'_blank':undefined} rel="noreferrer">{String(config.label||'Button')}</a></div>}

function Inspector({block,fields,databases,record,onChange}:{block:PageBlock|null;fields:Field[];databases:DatabaseType[];record:RecordRow|null;onChange:(c:Record<string,unknown>)=>void}){const config=block?.config||{};const patch=(p:Record<string,unknown>)=>onChange({...config,...p});return <aside className="atlas-inspector"><div className="atlas-panel-title"><Settings2/>Inspector</div>{!block?<div className="atlas-inspector-empty">Select something on the page to style it.</div>:<><div className="atlas-inspector-name"><strong>{block.type.replace('_',' ')}</strong><small>Live component</small></div><PanelField label="Background"><input type="color" value={String(config.background||'#ffffff')} onChange={e=>patch({background:e.target.value})}/></PanelField><PanelField label="Text color"><input type="color" value={String(config.textColor||'#211e1a')} onChange={e=>patch({textColor:e.target.value})}/></PanelField><div className="atlas-inspector-row"><PanelField label="Radius"><input type="number" value={Number(config.radius||0)} onChange={e=>patch({radius:Number(e.target.value)})}/></PanelField><PanelField label="Padding"><input type="number" value={Number(config.padding||0)} onChange={e=>patch({padding:Number(e.target.value)})}/></PanelField></div><div className="atlas-inspector-row"><PanelField label="Width px"><input type="number" value={Number(config.pixelWidth||320)} onChange={e=>patch({pixelWidth:Number(e.target.value)})}/></PanelField><PanelField label="Min height"><input type="number" value={Number(config.minHeight||80)} onChange={e=>patch({minHeight:Number(e.target.value)})}/></PanelField></div>{(block.type==='heading'||block.type==='text')&&<PanelField label="Font size"><input type="number" value={Number(config.fontSize||17)} onChange={e=>patch({fontSize:Number(e.target.value)})}/></PanelField>}{block.type==='property'&&record&&<PanelField label="Property"><select value={String(config.fieldId||'')} onChange={e=>patch({fieldId:e.target.value})}><option value="__title__">Record title</option>{fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></PanelField>}{block.type==='database_view'&&<PanelField label="Database"><select value={String(config.databaseId||'')} onChange={e=>patch({databaseId:e.target.value})}>{databases.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></PanelField>}</>}</aside>}
function PanelField({label,children}:{label:string;children:ReactNode}){return <label className="atlas-inspector-field"><span>{label}</span>{children}</label>}

function DataDrawer({database,record,databases,fields,onClose,onRecordChange}:{database:DatabaseType|null;record:RecordRow|null;databases:DatabaseType[];fields:Field[];onClose:()=>void;onRecordChange:(r:RecordRow)=>void}){const[activeDb,setActiveDb]=useState(database?.id||databases[0]?.id||''),[records,setRecords]=useState<RecordRow[]>([]),[drawerFields,setDrawerFields]=useState<Field[]>(fields);useEffect(()=>{if(!activeDb)return;Promise.all([getRecords(activeDb),getFields(activeDb)]).then(([r,f])=>{setRecords(r);setDrawerFields(f)}).catch(console.error)},[activeDb]);const saveRecord=async(patch:Partial<RecordRow>)=>{if(!record)return;const updated=await updateRecord(record.id,{title:patch.title??record.title,data:patch.data??record.data});onRecordChange(updated)};return <aside className="atlas-data-drawer"><div className="atlas-drawer-head"><div><span>Data</span><strong>{database?.name||'Workspace data'}</strong></div><button onClick={onClose}><X/></button></div>{record&&database?<div className="atlas-record-data"><label>Title<input value={record.title} onChange={e=>onRecordChange({...record,title:e.target.value})} onBlur={()=>saveRecord({title:record.title})}/></label>{fields.map(f=><label key={f.id}>{f.name}<FieldInput field={f} value={record.data?.[f.id]} onChange={async value=>{const updated=await updateRecord(record.id,{data:{...record.data,[f.id]:value}});onRecordChange(updated)}}/></label>)}</div>:<><select value={activeDb} onChange={e=>setActiveDb(e.target.value)}>{databases.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="atlas-new-record" onClick={async()=>{const r=await createRecord(activeDb,'Untitled');setRecords(x=>[r,...x])}}><Plus/>New record</button><div className="atlas-drawer-table">{records.map(r=><Link key={r.id} to={`/database/${activeDb}/record/${r.id}`}>{r.title}</Link>)}</div><div className="atlas-schema-summary"><h4>Properties</h4>{drawerFields.map(f=><div key={f.id}><span>{f.name}</span><small>{f.type}</small></div>)}</div></>}</aside>}
