import { useEffect, useMemo, useState, type CSSProperties, type KeyboardEvent as ReactKeyboardEvent, type PointerEvent as ReactPointerEvent } from 'react'
import { Check, ChevronLeft, ChevronRight, CirclePlus, Minus as MinusIcon, Pause, Play, Plus, RotateCcw, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { createRecord, getFields, getRecords, getViews, updateRecord } from '../lib/data'
import type { Database, Field, RecordRow } from '../types'
import CanvasCardView, { ensureCanvasCardTemplate } from './CanvasCardView'

type Config = Record<string, any>
type TodoItem = { id: string; text: string; done: boolean }
type TabItem = { id: string; title: string; body: string }
type TextLogEntry = { id: string; text: string; createdAt: string }
type Props = { config: Config; editing: boolean; databases: Database[]; save: (patch: Config) => void }

export const WIDGET_TYPES = [
  ['accordion','Accordion'],['analog_clock','Analog clock'],['annual_cycle','Annual cycle'],['button_group','Button group'],['calendar','Calendar'],['canvas_card','Canvas Card'],['checklist','Checklist'],['conditional_text','Conditional text'],['countup','Count up / since'],['countdown','Countdown'],['counter','Counter'],['custom','Custom widget'],['daily_focus','Daily focus'],['database_aggregate','Database aggregate'],['database_count','Database count'],['form','Database form'],['search','Database search'],['date','Date'],['digital_clock','Digital clock'],['dynamic_text','Dynamic text'],['featured_record','Featured record'],['gallery_strip','Gallery strip'],['goal','Goal tracker'],['greeting','Greeting'],['habit','Habit tracker'],['image_carousel','Image carousel'],['mini_kanban','Mini kanban'],['mini_table','Mini table'],['moon_phase','Moon phase'],['pomodoro','Pomodoro'],['progress_ring','Progress ring'],['quick_add','Quick add'],['quick_capture','Quick capture'],['quote','Quote'],['random_record','Random record'],['recent_records','Recently added'],['slideshow','Slideshow'],['sticky_note','Sticky note'],['stopwatch','Stopwatch'],['streak','Streak'],['tabs','Tabs'],['timeline','Timeline'],['todo','To-do list'],['upcoming_records','Upcoming'],
] as const

export default function AtlasWidget({ config, editing, databases: _databases, save }: Props) {
  const type = String(config.widgetType || 'digital_clock')
  const databaseId = String(config.databaseId || '')
  const { records, fields, setRecords, refresh } = useDatabaseData(databaseId)
  const now = useNow(['digital_clock','analog_clock','date','countdown','countup','greeting','moon_phase','annual_cycle','dynamic_text'].includes(type))
  const commonStyle: CSSProperties = { fontFamily: String(config.fontFamily || 'inherit'), fontSize: Number(config.fontSize || 16), textAlign: String(config.textAlign || 'left') as CSSProperties['textAlign'] }
  const shellStyle = {
    fontFamily: String(config.fontFamily || 'inherit'), fontSize: Number(config.fontSize || 16), fontWeight: Number(config.fontWeight || 400),
    textAlign: String(config.textAlign || 'left') as CSSProperties['textAlign'], color: String(config.primaryColor || config.textColor || 'inherit'),
    background: String(config.surfaceColor || 'transparent'), borderRadius: Number(config.widgetRadius || 0), padding: Number(config.widgetPadding || 0),
    border: `${Number(config.widgetBorderWidth || 0)}px solid ${String(config.borderColor || 'transparent')}`,
    '--widget-primary': String(config.primaryColor || config.textColor || 'currentColor'), '--widget-secondary': String(config.secondaryColor || config.primaryColor || config.textColor || 'currentColor'),
    '--widget-accent': String(config.accentColor || config.primaryColor || config.textColor || 'currentColor'), '--widget-muted': String(config.mutedColor || config.secondaryColor || '#8a7e72'),
    '--widget-surface': String(config.surfaceColor || 'transparent'), '--widget-border': String(config.borderColor || '#d8cec2'),
  } as CSSProperties & Record<string, string | number>

  let content: JSX.Element
  if (type === 'digital_clock') content = <DigitalClock now={now} config={config} style={commonStyle}/>
  else if (type === 'analog_clock') content = <AnalogClock now={now} config={config}/>
  else if (type === 'date') content = <DateWidget now={now} config={config} style={commonStyle}/>
  else if (type === 'calendar') content = <CalendarWidget config={config}/>
  else if (type === 'countdown') content = <Countdown now={now} config={config}/>
  else if (type === 'countup') content = <Countup now={now} config={config}/>
  else if (type === 'todo') content = <TodoWidget config={config} save={save} records={records} fields={fields} setRecords={setRecords}/>
  else if (type === 'checklist') content = <Checklist config={config} save={save}/>
  else if (type === 'counter') content = <Counter config={config} save={save}/>
  else if (type === 'progress_ring') content = <ProgressRing config={config} records={records} fields={fields}/>
  else if (type === 'goal') content = <GoalWidget config={config} records={records} fields={fields}/>
  else if (type === 'streak') content = <Streak config={config} save={save}/>
  else if (type === 'habit') content = <Habit config={config} save={save}/>
  else if (type === 'pomodoro') content = <Pomodoro config={config}/>
  else if (type === 'stopwatch') content = <Stopwatch/>
  else if (type === 'daily_focus') content = <EditableCard config={config} save={save} field="text" fallback="What matters most today?" editing={editing} databaseId={databaseId} refresh={refresh}/>
  else if (type === 'sticky_note') content = <EditableCard config={config} save={save} field="text" fallback="Write something…" editing={editing} multiline databaseId={databaseId} refresh={refresh}/>
  else if (type === 'quote') content = <QuoteWidget config={config} records={records} save={save}/>
  else if (type === 'greeting') content = <Greeting now={now} config={config}/>
  else if (type === 'moon_phase') content = <MoonPhase now={now}/>
  else if (type === 'annual_cycle') content = <AnnualCycle now={now} config={config}/>
  else if (type === 'database_count') content = <DatabaseCount config={config} records={records}/>
  else if (type === 'database_aggregate') content = <DatabaseAggregate config={config} records={records} fields={fields}/>
  else if (type === 'canvas_card') content = <SingleCanvasCardWidget config={config} databaseId={databaseId} records={records} fields={fields}/>
  else if (type === 'random_record') content = <RandomRecord config={config} records={records} databaseId={databaseId}/>
  else if (type === 'featured_record') content = <FeaturedRecord config={config} records={records} databaseId={databaseId}/>
  else if (type === 'recent_records') content = <RecordList records={records.slice(0,Number(config.limit||5))} databaseId={databaseId} label={String(config.label||'Recently added')}/>
  else if (type === 'upcoming_records') content = <Upcoming config={config} records={records} fields={fields} databaseId={databaseId}/>
  else if (type === 'timeline') content = <Timeline config={config} records={records} fields={fields} databaseId={databaseId}/>
  else if (type === 'mini_kanban') content = <MiniKanban config={config} records={records} fields={fields} databaseId={databaseId}/>
  else if (type === 'mini_table') content = <MiniTable config={config} records={records} fields={fields} databaseId={databaseId}/>
  else if (type === 'gallery_strip') content = <GalleryStrip config={config} records={records} fields={fields} databaseId={databaseId}/>
  else if (type === 'quick_add') content = <QuickAdd config={config} databaseId={databaseId} refresh={refresh}/>
  else if (type === 'quick_capture') content = <QuickCapture config={config} databaseId={databaseId} refresh={refresh}/>
  else if (type === 'form') content = <DatabaseForm config={config} databaseId={databaseId} fields={fields} refresh={refresh}/>
  else if (type === 'search') content = <DatabaseSearch records={records} databaseId={databaseId}/>
  else if (type === 'dynamic_text') content = <DynamicText now={now} config={config} records={records} save={save}/>
  else if (type === 'conditional_text') content = <ConditionalText config={config} records={records} save={save}/>
  else if (type === 'image_carousel' || type === 'slideshow') content = <ImageCarousel config={config} auto={type==='slideshow'}/>
  else if (type === 'button_group') content = <ButtonGroup config={config} editing={editing}/>
  else if (type === 'tabs') content = <TabsWidget config={config}/>
  else if (type === 'accordion') content = <AccordionWidget config={config}/>
  else if (type === 'custom') content = <CustomWidget config={config} editing={editing} save={save}/>
  else content = <div className="atlas-widget-empty">Choose a widget type in Design.</div>
  return <div className="atlas-widget-shell" style={shellStyle}>{content}</div>
}

function useNow(active:boolean){const[now,setNow]=useState(new Date());useEffect(()=>{if(!active)return;const id=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(id)},[active]);return now}
function useDatabaseData(databaseId:string){const[records,setRecords]=useState<RecordRow[]>([]),[fields,setFields]=useState<Field[]>([]);const refresh=async()=>{if(!databaseId){setRecords([]);setFields([]);return}const[r,f]=await Promise.all([getRecords(databaseId),getFields(databaseId)]);setRecords(r);setFields(f)};useEffect(()=>{void refresh()},[databaseId]);return{records,fields,setRecords,refresh}}
function DigitalClock({now,config,style}:{now:Date;config:Config;style:CSSProperties}){return <div className="widget-digital-clock" style={style}><strong style={{color:String(config.valueColor||'var(--widget-primary)'),fontFamily:String(config.timeFontFamily||config.fontFamily||'inherit')}}>{now.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit',second:config.showSeconds===false?undefined:'2-digit',hour12:String(config.timeFormat||'12h')!=='24h'})}</strong>{config.showDate!==false&&<span style={{color:String(config.secondaryTextColor||'var(--widget-secondary)'),fontFamily:String(config.dateFontFamily||config.fontFamily||'inherit')}}>{now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</span>}</div>}
function AnalogClock({now,config}:{now:Date;config:Config}){const s=now.getSeconds(),m=now.getMinutes()+s/60,h=now.getHours()%12+m/60;return <div className="widget-analog" style={{background:String(config.faceColor||'transparent'),color:String(config.handColor||'var(--widget-primary)'),borderColor:String(config.clockBorderColor||'var(--widget-border)')}}><div className="analog-hand hour" style={{transform:`rotate(${h*30}deg)`}}/><div className="analog-hand minute" style={{transform:`rotate(${m*6}deg)`}}/>{config.showSeconds!==false&&<div className="analog-hand second" style={{transform:`rotate(${s*6}deg)`,background:String(config.secondHandColor||'var(--widget-accent)')}}/>}<div className="analog-dot"/>{[12,3,6,9].map((n,i)=><span className={`analog-number n${i}`} key={n}>{n}</span>)}</div>}
function DateWidget({now,config,style}:{now:Date;config:Config;style:CSSProperties}){const mode=String(config.dateFormat||'full'),options:Intl.DateTimeFormatOptions=mode==='short'?{month:'short',day:'numeric',year:'numeric'}:mode==='weekday'?{weekday:'long'}:{weekday:'long',month:'long',day:'numeric',year:'numeric'};return <div className="widget-date" style={{...style,color:String(config.valueColor||'var(--widget-primary)')}}>{now.toLocaleDateString(undefined,options)}</div>}
function CalendarWidget({config}:{config:Config}){const[cursor,setCursor]=useState(()=>new Date()),year=cursor.getFullYear(),month=cursor.getMonth(),first=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate(),today=new Date(),cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1);return <div className="widget-calendar"><div className="widget-calendar-head"><button onClick={()=>setCursor(new Date(year,month-1,1))}><ChevronLeft/></button><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{cursor.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button onClick={()=>setCursor(new Date(year,month+1,1))}><ChevronRight/></button></div><div className="calendar-weekdays" style={{color:String(config.secondaryTextColor||'var(--widget-secondary)')}}>{'SMTWTFS'.split('').map((d,i)=><span key={i}>{d}</span>)}</div><div className="calendar-grid">{cells.map((d,i)=><span key={i} className={d===today.getDate()&&month===today.getMonth()&&year===today.getFullYear()?'today':''}>{d||''}</span>)}</div>{Boolean(config.label)&&<small>{String(config.label)}</small>}</div>}
function Countdown({now,config}:{now:Date;config:Config}){const target=new Date(String(config.targetDate||new Date(Date.now()+86400000).toISOString())),diff=Math.max(0,target.getTime()-now.getTime()),d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);return <div className="widget-countdown"><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{String(config.label||'Countdown')}</span><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{d}<small>d</small> {h}<small>h</small> {m}<small>m</small> {s}<small>s</small></strong></div>}
function Countup({now,config}:{now:Date;config:Config}){const start=new Date(String(config.targetDate||new Date().toISOString())),days=Math.max(0,Math.floor((now.getTime()-start.getTime())/86400000));return <div className="widget-countdown"><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{String(config.label||'Since')}</span><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{days}<small> days</small></strong></div>}
function TodoWidget({config,save,records,fields,setRecords}:{config:Config;save:(p:Config)=>void;records:RecordRow[];fields:Field[];setRecords:(r:RecordRow[])=>void}){const status=fields.find(f=>f.id===String(config.statusFieldId||''))||fields.find(f=>f.type==='checkbox');if(String(config.dataMode||'simple')==='database')return <div className="widget-list"><strong style={{color:String(config.labelColor||'var(--widget-primary)')}}>{String(config.label||'To do')}</strong>{records.slice(0,Number(config.limit||8)).map(r=><label key={r.id}><input type="checkbox" checked={status?Boolean(r.data?.[status.id]):false} disabled={!status} onChange={async()=>{if(!status)return;const u=await updateRecord(r.id,{data:{...r.data,[status.id]:!Boolean(r.data?.[status.id])}});setRecords(records.map(x=>x.id===u.id?u:x))}}/><span>{r.title}</span></label>)}</div>;return <SimpleItems config={config} save={save} label={String(config.label||'To do')}/>}
function Checklist({config,save}:{config:Config;save:(p:Config)=>void}){return <SimpleItems config={config} save={save} label={String(config.label||'Checklist')}/>}
function SimpleItems({config,save,label}:{config:Config;save:(p:Config)=>void;label:string}){const items=(Array.isArray(config.items)?config.items:[]) as TodoItem[],[text,setText]=useState(''),persist=(n:TodoItem[])=>save({items:n});return <div className="widget-list"><InlineText as="strong" value={label} style={{color:String(config.labelColor||'var(--widget-primary)')}} onSave={value=>save({label:value})}/>{items.map(item=><label key={item.id}><input type="checkbox" checked={item.done} onChange={()=>persist(items.map(x=>x.id===item.id?{...x,done:!x.done}:x))}/><InlineText className={item.done?'done':''} value={item.text} onSave={value=>persist(items.map(x=>x.id===item.id?{...x,text:value}:x))}/><button onClick={()=>persist(items.filter(x=>x.id!==item.id))}>×</button></label>)}<div className="widget-add-row"><input value={text} placeholder="Add item" onChange={e=>setText(e.target.value)}/><button onClick={()=>{if(text.trim()){persist([...items,{id:crypto.randomUUID(),text:text.trim(),done:false}]);setText('')}}}><Plus/></button></div></div>}
function Counter({config,save}:{config:Config;save:(p:Config)=>void}){const v=Number(config.value||0),step=Number(config.step||1);return <div className="widget-counter"><InlineText value={String(config.label||'Counter')} style={{color:String(config.labelColor||'var(--widget-secondary)')}} onSave={label=>save({label})}/><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{v}</strong><div><button onClick={()=>save({value:v-step})}><MinusIcon/></button><button onClick={()=>save({value:v+step})}><Plus/></button></div></div>}
function resolveNumber(c:Config,r:RecordRow[],f:Field[]){if(String(c.dataMode||'manual')==='database'){if(String(c.aggregate||'count')==='count')return r.length;const field=f.find(x=>x.id===String(c.fieldId||'')),nums=field?r.map(x=>Number(x.data?.[field.id])).filter(Number.isFinite):[];return String(c.aggregate)==='average'?(nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0):nums.reduce((a,b)=>a+b,0)}return Number(c.value||0)}
function ProgressRing({config,records,fields}:{config:Config;records:RecordRow[];fields:Field[]}){const v=resolveNumber(config,records,fields),max=Math.max(1,Number(config.max||100)),p=Math.max(0,Math.min(100,v/max*100));return <div className="widget-ring" style={{'--pct':`${p*3.6}deg`,color:String(config.accentColor||'var(--widget-accent)')} as CSSProperties}><div><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{Math.round(p)}%</strong><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{String(config.label||'Progress')}</span></div></div>}
function GoalWidget({config,records,fields}:{config:Config;records:RecordRow[];fields:Field[]}){const v=resolveNumber(config,records,fields),max=Math.max(1,Number(config.max||100)),p=Math.max(0,Math.min(100,v/max*100));return <div className="widget-goal"><div><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{String(config.label||'Goal')}</span><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{v} / {max}</strong></div><div className="widget-goal-track"><i style={{width:`${p}%`,background:String(config.accentColor||'var(--widget-accent)')}}/></div></div>}
function Streak({config,save}:{config:Config;save:(p:Config)=>void}){const v=Number(config.value||0);return <div className="widget-streak"><InlineText value={String(config.emoji||'🔥')} onSave={emoji=>save({emoji})}/><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{v} days</strong><button onClick={()=>save({value:v+1})}>Check in</button></div>}
function Habit({config,save}:{config:Config;save:(p:Config)=>void}){const days=(Array.isArray(config.days)?config.days:Array(7).fill(false)) as boolean[];return <div className="widget-habit"><InlineText as="strong" value={String(config.label||'Habit')} style={{color:String(config.labelColor||'var(--widget-primary)')}} onSave={label=>save({label})}/><div>{days.map((d,i)=><button key={i} className={d?'done':''} style={d?{background:String(config.accentColor||'var(--widget-accent)')}:undefined} onClick={()=>save({days:days.map((x,j)=>j===i?!x:x)})}>{'SMTWTFS'[i]}{d&&<Check/>}</button>)}</div></div>}
function Pomodoro({config}:{config:Config}){const focus=Math.max(1,Number(config.focusMinutes||25))*60,br=Math.max(1,Number(config.breakMinutes||5))*60,[remaining,setRemaining]=useState(focus),[running,setRunning]=useState(false),[mode,setMode]=useState<'focus'|'break'>('focus');useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setRemaining(v=>{if(v>1)return v-1;const n=mode==='focus'?'break':'focus';setMode(n);return n==='focus'?focus:br}),1000);return()=>clearInterval(id)},[running,mode,focus,br]);return <div className="widget-timer"><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{mode==='focus'?'Focus':'Break'}</span><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{formatSeconds(remaining)}</strong><div><button onClick={()=>setRunning(v=>!v)}>{running?<Pause/>:<Play/>}</button><button onClick={()=>{setRunning(false);setRemaining(mode==='focus'?focus:br)}}><RotateCcw/></button></div></div>}
function Stopwatch(){const[e,setE]=useState(0),[r,setR]=useState(false);useEffect(()=>{if(!r)return;const id=window.setInterval(()=>setE(v=>v+1),1000);return()=>clearInterval(id)},[r]);return <div className="widget-timer"><span>Stopwatch</span><strong>{formatSeconds(e)}</strong><div><button onClick={()=>setR(v=>!v)}>{r?<Pause/>:<Play/>}</button><button onClick={()=>{setR(false);setE(0)}}><RotateCcw/></button></div></div>}
function formatSeconds(s:number){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function EditableCard({config,save,field,fallback,multiline=false,databaseId,refresh}:{config:Config;save:(p:Config)=>void;field:string;fallback:string;editing:boolean;multiline?:boolean;databaseId?:string;refresh?:()=>Promise<void>}){const t=Object.prototype.hasOwnProperty.call(config,field)?String(config[field]??''):fallback,entries=(Array.isArray(config.entries)?config.entries:[]) as TextLogEntry[];const submit=async(value:string)=>{const clean=plainText(value);if(!clean)return;const next=[{id:crypto.randomUUID(),text:value,createdAt:new Date().toISOString()},...entries];save({[field]:'',entries:next});if(databaseId){await createRecord(databaseId,clean.slice(0,120));await refresh?.()}};const updateEntry=(id:string,text:string)=>save({entries:entries.map(entry=>entry.id===id?{...entry,text}:entry)});return <div className={`widget-editable ${multiline?'rich':''}`}><InlineText style={{color:String(config.labelColor||'var(--widget-secondary)')}} value={String(config.label||'')} onSave={label=>save({label})}/><RichEditableText value={t} multiline={multiline} placeholder={fallback} onSave={value=>save({[field]:value})} onSubmit={submit}/>{entries.length>0&&<div className="widget-text-log">{entries.map(entry=><div className="widget-text-log-entry" key={entry.id}><RichEditableText value={entry.text} multiline onSave={value=>updateEntry(entry.id,value)}/><button type="button" aria-label="Remove log entry" onClick={()=>save({entries:entries.filter(item=>item.id!==entry.id)})}>×</button></div>)}</div>}</div>}
function QuoteWidget({config,records,save}:{config:Config;records:RecordRow[];save:(p:Config)=>void}){const r=records.length?records[Math.abs(Number(config.seed||0))%records.length]:null,isDatabase=String(config.dataMode)==='database'&&r;return <blockquote className="widget-quote" style={{color:String(config.valueColor||'var(--widget-primary)'),fontFamily:String(config.quoteFontFamily||config.fontFamily||'Georgia, serif')}}>{isDatabase?`“${r.title}”`:<><span>“</span><InlineText value={String(config.text||'Add a quote in Design.')} onSave={text=>save({text})}/><span>”</span></>}{(Boolean(config.author)||!isDatabase)&&<InlineText as="cite" value={String(config.author||'Author')} style={{color:String(config.secondaryTextColor||'var(--widget-secondary)'),fontFamily:String(config.authorFontFamily||'inherit')}} onSave={author=>save({author})}/>}</blockquote>}
function Greeting({now,config}:{now:Date;config:Config}){const h=now.getHours(),g=h<12?'Good morning':h<18?'Good afternoon':'Good evening';return <div className="widget-greeting"><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{String(config.prefix||g)}{config.name?`, ${String(config.name)}`:''}</strong>{Boolean(config.subtitle)&&<span style={{color:String(config.secondaryTextColor||'var(--widget-secondary)')}}>{String(config.subtitle)}</span>}</div>}
function moonPhase(d:Date){const lunar=29.53058867,known=new Date('2000-01-06T18:14:00Z').getTime(),age=(((d.getTime()-known)/86400000)%lunar+lunar)%lunar,i=Math.floor(age/lunar*8+.5)%8,n=['New Moon','Waxing Crescent','First Quarter','Waxing Gibbous','Full Moon','Waning Gibbous','Last Quarter','Waning Crescent'],e=['🌑','🌒','🌓','🌔','🌕','🌖','🌗','🌘'];return{name:n[i],emoji:e[i],age}}
function MoonPhase({now}:{now:Date}){const p=moonPhase(now);return <div className="widget-moon"><span>{p.emoji}</span><div><strong>{p.name}</strong><small>{p.age.toFixed(1)} days into cycle</small></div></div>}
function AnnualCycle({now,config}:{now:Date;config:Config}){const labels=String(config.labels||'Winter,Spring,Summer,Autumn').split(',').map(s=>s.trim()),i=Math.floor(now.getMonth()/3)%Math.max(1,labels.length);return <div className="widget-cycle"><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{String(config.label||'Current season')}</span><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{labels[i]||'Cycle'}</strong><small>{now.toLocaleDateString(undefined,{month:'long',day:'numeric'})}</small></div>}
function DatabaseCount({config,records}:{config:Config;records:RecordRow[]}){return <div className="widget-db-count"><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{records.length}</strong><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{String(config.label||'records')}</span></div>}
function DatabaseAggregate({config,records,fields}:{config:Config;records:RecordRow[];fields:Field[]}){const v=resolveNumber({...config,dataMode:'database'},records,fields);return <div className="widget-db-count"><strong style={{color:String(config.valueColor||'var(--widget-primary)')}}>{Number.isInteger(v)?v:v.toFixed(1)}</strong><span style={{color:String(config.labelColor||'var(--widget-secondary)')}}>{String(config.label||config.aggregate||'Total')}</span></div>}
function SingleCanvasCardWidget({config,databaseId,records,fields}:{config:Config;databaseId:string;records:RecordRow[];fields:Field[]}){const[template,setTemplate]=useState<unknown>(null);useEffect(()=>{let alive=true;if(!databaseId){setTemplate(null);return()=>{alive=false}};getViews(databaseId).then(views=>{if(!alive)return;const view=views.find(item=>item.type==='canvas')||views.find(item=>item.config?.canvasCardTemplate);setTemplate(view?.config?.canvasCardTemplate||null)}).catch(()=>alive&&setTemplate(null));return()=>{alive=false}},[databaseId]);const record=records.find(item=>item.id===String(config.recordId||''))||records[0],usableFields=fields.filter(field=>field.name.trim().toLowerCase()!=='name'),cardTemplate=ensureCanvasCardTemplate(template,usableFields),w=Math.max(1,Number(config.width||cardTemplate.width)),h=Math.max(1,Number(config.height||cardTemplate.height)),scale=Math.max(.12,Math.min(w/cardTemplate.width,h/cardTemplate.height));if(!databaseId)return <div className="atlas-widget-empty">Choose a database.</div>;if(!record)return <div className="atlas-widget-empty">Choose a record.</div>;return <div className="widget-canvas-card" style={{width:w,height:h}}><div style={{width:cardTemplate.width*scale,height:cardTemplate.height*scale}}><div style={{transform:`scale(${scale})`,transformOrigin:'top left',width:cardTemplate.width,height:cardTemplate.height}}><CanvasCardView records={[record]} fields={usableFields} databaseId={databaseId} editing={false} template={cardTemplate} onChangeTemplate={()=>{}} inlineEditing={false} onPatchField={()=>{}} showTools={false}/></div></div></div>}
function RandomRecord({config,records,databaseId}:{config:Config;records:RecordRow[];databaseId:string}){const[i,setI]=useState(0),r=records.length?records[i%records.length]:null;return <div className="widget-featured">{r?<><Link to={`/database/${databaseId}/record/${r.id}`}>{r.title}</Link><button onClick={()=>setI(Math.floor(Math.random()*records.length))}>Another</button></>:<span>No records</span>}{Boolean(config.label)&&<small>{String(config.label)}</small>}</div>}
function FeaturedRecord({config,records,databaseId}:{config:Config;records:RecordRow[];databaseId:string}){const r=records.find(x=>x.id===String(config.recordId||''))||records[0];return <div className="widget-featured">{r?<Link to={`/database/${databaseId}/record/${r.id}`}>{r.title}</Link>:<span>No record selected</span>}{Boolean(config.label)&&<small>{String(config.label)}</small>}</div>}
function RecordList({records,databaseId,label}:{records:RecordRow[];databaseId:string;label:string}){return <div className="widget-record-list"><strong>{label}</strong>{records.map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}>{r.title}</Link>)}</div>}
function Upcoming({config,records,fields,databaseId}:{config:Config;records:RecordRow[];fields:Field[];databaseId:string}){const f=fields.find(x=>x.id===String(config.fieldId||''))||fields.find(x=>x.type==='date'),up=f?records.filter(r=>r.data?.[f.id]&&new Date(String(r.data[f.id]))>=new Date()).sort((a,b)=>new Date(String(a.data[f.id])).getTime()-new Date(String(b.data[f.id])).getTime()).slice(0,Number(config.limit||5)):[];return <RecordList records={up} databaseId={databaseId} label={String(config.label||'Upcoming')}/>}
function Timeline({config,records,fields,databaseId}:{config:Config;records:RecordRow[];fields:Field[];databaseId:string}){const f=fields.find(x=>x.id===String(config.fieldId||''))||fields.find(x=>x.type==='date'),sorted=f?[...records].filter(r=>r.data?.[f.id]).sort((a,b)=>new Date(String(a.data[f.id])).getTime()-new Date(String(b.data[f.id])).getTime()).slice(0,Number(config.limit||8)):records.slice(0,8);return <div className="widget-timeline">{sorted.map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}><i/><div><strong>{r.title}</strong></div></Link>)}</div>}
function MiniKanban({config,records,fields,databaseId}:{config:Config;records:RecordRow[];fields:Field[];databaseId:string}){const f=fields.find(x=>x.id===String(config.fieldId||''))||fields.find(x=>x.type==='select'),groups=f?Array.from(new Set(records.map(r=>String(r.data?.[f.id]||'Unassigned')))):['Records'];return <div className="widget-kanban">{groups.slice(0,4).map(g=><div key={g}><strong>{g}</strong>{records.filter(r=>!f||String(r.data?.[f.id]||'Unassigned')===g).slice(0,5).map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}>{r.title}</Link>)}</div>)}</div>}
function MiniTable({config,records,fields,databaseId}:{config:Config;records:RecordRow[];fields:Field[];databaseId:string}){const selected=fields.filter(f=>String(config.fieldIds||'').split(',').includes(f.id));return <div className="widget-mini-table">{records.slice(0,Number(config.limit||6)).map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}><strong>{r.title}</strong>{selected.map(f=><span key={f.id}>{String(r.data?.[f.id]??'')}</span>)}</Link>)}</div>}
function GalleryStrip({config,records,fields,databaseId}:{config:Config;records:RecordRow[];fields:Field[];databaseId:string}){const image=fields.find(f=>f.id===String(config.fieldId||''))||fields.find(f=>f.type==='image');return <div className="widget-gallery-strip">{records.slice(0,Number(config.limit||6)).map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}>{image&&r.data?.[image.id]?<img src={String(r.data[image.id])} alt=""/>:<div/>}<span>{r.title}</span></Link>)}</div>}
function QuickAdd({config,databaseId,refresh}:{config:Config;databaseId:string;refresh:()=>Promise<void>}){const[busy,setBusy]=useState(false);return <button className="widget-quick-button" disabled={!databaseId||busy} onClick={async()=>{setBusy(true);await createRecord(databaseId,String(config.defaultTitle||'Untitled'));await refresh();setBusy(false)}}><CirclePlus/>{String(config.label||'Add record')}</button>}
function QuickCapture({config,databaseId,refresh}:{config:Config;databaseId:string;refresh:()=>Promise<void>}){const[text,setText]=useState('');return <div className="widget-capture"><input value={text} placeholder={String(config.placeholder||'Capture something…')} onChange={e=>setText(e.target.value)}/><button disabled={!databaseId||!text.trim()} onClick={async()=>{await createRecord(databaseId,text.trim());setText('');await refresh()}}><Plus/></button></div>}
function DatabaseForm({config,databaseId,fields,refresh}:{config:Config;databaseId:string;fields:Field[];refresh:()=>Promise<void>}){const[title,setTitle]=useState(''),[values,setValues]=useState<Record<string,unknown>>({});return <div className="widget-form"><strong>{String(config.label||'Add record')}</strong><input placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/>{fields.filter(f=>f.type!=='relation').slice(0,Number(config.limit||5)).map(f=><input key={f.id} type={f.type==='date'?'date':f.type==='number'?'number':'text'} placeholder={f.name} value={String(values[f.id]??'')} onChange={e=>setValues(v=>({...v,[f.id]:f.type==='number'?Number(e.target.value):e.target.value}))}/>)}<button disabled={!databaseId||!title.trim()} onClick={async()=>{const r=await createRecord(databaseId,title.trim());if(Object.keys(values).length)await updateRecord(r.id,{data:values});setTitle('');setValues({});await refresh()}}>Save</button></div>}
function DatabaseSearch({records,databaseId}:{records:RecordRow[];databaseId:string}){const[q,setQ]=useState(''),found=q.trim()?records.filter(r=>r.title.toLowerCase().includes(q.toLowerCase())).slice(0,8):[];return <div className="widget-search"><div><Search/><input value={q} placeholder="Search" onChange={e=>setQ(e.target.value)}/></div>{found.map(r=><Link key={r.id} to={`/database/${databaseId}/record/${r.id}`}>{r.title}</Link>)}</div>}
function DynamicText({now,config,records,save}:{now:Date;config:Config;records:RecordRow[];save:(p:Config)=>void}){const raw=String(config.text||'Today is {date}. You have {count} records.'),t=raw.replaceAll('{date}',now.toLocaleDateString()).replaceAll('{time}',now.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})).replaceAll('{count}',String(records.length));return <InlineText className="widget-dynamic-text" style={{color:String(config.valueColor||'var(--widget-primary)')}} value={t} onSave={text=>save({text})}/>}
function ConditionalText({config,records,save}:{config:Config;records:RecordRow[];save:(p:Config)=>void}){const met=records.length>=Number(config.threshold||1);return <InlineText className="widget-dynamic-text" style={{color:String(config.valueColor||'var(--widget-primary)')}} value={met?String(config.trueText||'You have things to do.'):String(config.falseText||'All clear.')} onSave={text=>save(met?{trueText:text}:{falseText:text})}/>}
function ImageCarousel({config,auto}:{config:Config;auto:boolean}){const images=useMemo(()=>String(config.images||'').split(/\n|,/).map(s=>s.trim()).filter(Boolean),[config.images]),[i,setI]=useState(0);useEffect(()=>{if(!auto||images.length<2)return;const id=window.setInterval(()=>setI(x=>(x+1)%images.length),Math.max(1000,Number(config.interval||5)*1000));return()=>clearInterval(id)},[auto,images.length,config.interval]);if(!images.length)return <div className="atlas-widget-empty">Add image URLs in Design.</div>;return <div className="widget-carousel"><img src={images[i%images.length]} alt=""/><button className="prev" onClick={()=>setI(x=>(x-1+images.length)%images.length)}><ChevronLeft/></button><button className="next" onClick={()=>setI(x=>(x+1)%images.length)}><ChevronRight/></button><small>{i+1} / {images.length}</small></div>}
function ButtonGroup({config,editing}:{config:Config;editing:boolean}){const rows=String(config.buttons||'Open|#\nAnother|#').split('\n').map(x=>x.split('|'));return <div className="widget-button-group">{rows.map(([label,url],i)=><a key={i} href={editing?undefined:(url||'#')} onClick={editing?e=>e.preventDefault():undefined}>{label||'Button'}</a>)}</div>}
function parseTabs(config:Config):TabItem[]{return String(config.sections||'First|Add content here\nSecond|More content').split('\n').filter(Boolean).map((row,i)=>{const[title,...body]=row.split('|');return{id:String(i),title:title||`Tab ${i+1}`,body:body.join('|')}})}
function TabsWidget({config}:{config:Config}){const tabs=parseTabs(config),[active,setActive]=useState(0);return <div className="widget-tabs"><div>{tabs.map((t,i)=><button className={i===active?'active':''} key={t.id} onClick={()=>setActive(i)}>{t.title}</button>)}</div><p>{tabs[active]?.body||''}</p></div>}
function AccordionWidget({config}:{config:Config}){const tabs=parseTabs(config),[open,setOpen]=useState<number|null>(0);return <div className="widget-accordion">{tabs.map((t,i)=><section key={t.id}><button onClick={()=>setOpen(open===i?null:i)}>{t.title}<span>{open===i?'−':'+'}</span></button>{open===i&&<p>{t.body}</p>}</section>)}</div>}
function CustomWidget({config,editing,save}:{config:Config;editing:boolean;save:(p:Config)=>void}){const layout=String(config.customLayout||'stack');return <div className={`widget-custom layout-${layout}`}><InlineText className="custom-icon" style={{color:String(config.iconColor||'var(--widget-accent)')}} value={String(config.customIcon||'✦')} onSave={customIcon=>save({customIcon})}/><div className="custom-copy"><InlineText className="custom-title" style={{color:String(config.titleColor||'var(--widget-secondary)'),fontSize:Number(config.titleSize||12)}} value={String(config.customTitle||'Custom widget')} onSave={customTitle=>save({customTitle})}/><InlineText className="custom-value" style={{color:String(config.valueColor||'var(--widget-primary)'),fontSize:Number(config.valueSize||40),fontWeight:Number(config.valueWeight||700)}} value={String(config.customValue||'42')} onSave={customValue=>save({customValue})}/><InlineText className="custom-body" style={{color:String(config.bodyColor||'var(--widget-secondary)'),fontSize:Number(config.bodySize||14)}} value={String(config.customBody||'Add any supporting text you want.')} onSave={customBody=>save({customBody})}/>{Boolean(config.actionLabel)&&<a className="custom-action" style={{color:String(config.actionColor||'var(--widget-accent)')}} href={editing?undefined:String(config.actionUrl||'#')} onClick={editing?e=>e.preventDefault():undefined}>{String(config.actionLabel)}</a>}</div></div>}

function InlineText({value,onSave,as='span',className,style}:{value:string;onSave:(value:string)=>void;as?:'span'|'strong'|'cite';className?:string;style?:CSSProperties}){const Tag=as,html=sanitizeWidgetHtml(value);return <span className="atlas-widget-inline-host" data-workspace-interactive><Tag className={`atlas-widget-inline-text ${className||''}`} style={style} contentEditable suppressContentEditableWarning onBlur={event=>{const next=sanitizeWidgetHtml(event.currentTarget.innerHTML).trim();if(next!==html)onSave(next)}} dangerouslySetInnerHTML={{__html:html}}/></span>}

function RichEditableText({value,onSave,multiline,placeholder='',onSubmit}:{value:string;onSave:(value:string)=>void;multiline:boolean;placeholder?:string;onSubmit?:(value:string)=>void|Promise<void>}){const[html,setHtml]=useState(()=>sanitizeWidgetHtml(value));useEffect(()=>setHtml(sanitizeWidgetHtml(value)),[value]);const commit=(next:string)=>{const clean=sanitizeWidgetHtml(next).trim();setHtml(clean);if(clean!==html)onSave(clean);return clean};const handleKeyDown=async(event:ReactKeyboardEvent<HTMLDivElement>)=>{if(!onSubmit||event.key!=='Enter'||event.shiftKey)return;event.preventDefault();const clean=commit(event.currentTarget.innerHTML);if(!plainText(clean))return;await onSubmit(clean);event.currentTarget.innerHTML='';setHtml('')};return <div className={`widget-rich-editor ${multiline?'multiline':'single-line'}`} data-workspace-interactive><div className="widget-rich-content" data-atlas-rich-text="true" data-placeholder={placeholder} contentEditable suppressContentEditableWarning onKeyDown={handleKeyDown} onBlur={event=>commit(event.currentTarget.innerHTML)} dangerouslySetInnerHTML={{__html:html}}/></div>}

function sanitizeWidgetHtml(value:string){return String(value||'').replace(/<script[\s\S]*?>[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?>[\s\S]*?<\/style>/gi,'').replace(/\son\w+="[^"]*"/gi,'').replace(/\son\w+='[^']*'/gi,'').replace(/javascript:/gi,'')}
function plainText(value:string){const div=document.createElement('div');div.innerHTML=sanitizeWidgetHtml(value);return div.textContent?.trim()||''}
