import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Compass, Database, LayoutTemplate, MousePointer2, Palette, Sparkles, X } from 'lucide-react'

type Props={open:boolean;onClose:()=>void;onComplete?:()=>void}
const steps=[
 {icon:<Sparkles/>,title:'Welcome to Atlas',eyebrow:'THE BIG IDEA',body:<><p>Atlas is a visual workspace. Think of every page as a canvas you can make beautiful first, while databases quietly keep the information underneath organized and reusable.</p><p>You do not need to understand databases before you begin. Start with what you want to make, then connect information when you need it.</p></>},
 {icon:<Compass/>,title:'Your workspace',eyebrow:'NAVIGATION',body:<><p><strong>Dashboard</strong> is your permanent home page. It is customizable just like every other page.</p><p><strong>Pages</strong> are your visual spaces. Make a project hub, reading journal, podcast studio, travel board, budget, grimoire, or anything else. Pages can have subpages and favorites.</p><p><strong>Data</strong> holds reusable collections of information, such as Books, Episodes, Trips, Transactions, Tasks, or Characters.</p></>},
 {icon:<MousePointer2/>,title:'Editing a page',eyebrow:'THE CANVAS',body:<><p>Open any page and choose <strong>Edit</strong>. The normal navigation becomes your editing panel so the canvas gets as much room as possible.</p><p>Use <strong>Add</strong> for text, images, buttons, sections, widgets, database views, metrics, progress bars and more. Drag items anywhere. Resize them from their handles. Select an item to change its appearance and settings.</p><p>Use Delete or Backspace to remove a selected item. Arrow keys nudge it. Shift + Arrow moves farther. Ctrl/Cmd + D duplicates it. The Layers panel controls what sits in front of what.</p></>},
 {icon:<Palette/>,title:'Make it yours',eyebrow:'DESIGN',body:<><p>Page backgrounds, titles, covers and placed elements are independent pieces. You can move and resize them instead of being locked into a stacked document.</p><p>Change fonts, colors, sizes, spacing, borders, backgrounds and positioning. Upload images and custom fonts to Assets so you can reuse them later.</p><p>Templates are starting points, not rules. Apply one, keep the editor open, move everything around, restyle it, delete pieces, or replace them entirely.</p></>},
 {icon:<Database/>,title:'How data works',eyebrow:'COLLECTIONS',body:<><p>A database is simply a collection of things. <strong>Books</strong> can be a collection. <strong>Fourth Wing</strong> is one record inside Books. Title, author, rating, cover and genre are properties attached to that record.</p><p>The same collection can appear in multiple places without copying the information. Edit Fourth Wing once and every connected view can use the updated information.</p><p>When you see a database view on a page, select it and use its <strong>Data</strong> controls to choose what collection it shows, how it is grouped, filtered, sorted and which properties appear on cards.</p></>},
 {icon:<LayoutTemplate/>,title:'Views are displays, not separate data',eyebrow:'GALLERY · TABLE · BOARD',body:<><p>A gallery, table and Kanban board can all show the same collection. They are different ways of looking at the information, not different copies of it.</p><p>For example, a Podcast page might show Episodes as a board grouped by Status. A dashboard might show only the next three Episodes as cards. Both still read from Episodes.</p><p>Freeform record mode lets individual cards move independently. Auto layout keeps them arranged automatically. You can style cards and choose which record properties are visible.</p></>},
 {icon:<Sparkles/>,title:'Widgets and useful little things',eyebrow:'FUNCTION + DELIGHT',body:<><p>Widgets can be decorative, practical, or data-aware. Add clocks, moon information, to-do lists, budget pieces, progress, intentions and other tools from the widget library.</p><p>Some widgets keep their own information. Others can read from a collection. If something should stay reusable across pages, connecting it to data is usually the better choice.</p></>},
 {icon:<Check/>,title:'You are ready to make something',eyebrow:'START ANYWHERE',body:<><p>There is no required order. You can begin with a blank page, apply a template, create a collection first, or simply drag things onto the canvas until the page feels right.</p><p>If you get lost, select the thing you are trying to change. Atlas should show the controls that belong to it. You can reopen this full guide any time from the small <strong>Guide</strong> button at the bottom of the sidebar.</p><p><strong>The goal is not to build a database. The goal is to build a workspace you actually want to live in.</strong></p></>}
]
export default function AtlasTutorial({open,onClose,onComplete}:Props){const[index,setIndex]=useState(0);useEffect(()=>{if(open)setIndex(0)},[open]);if(!open)return null;const step=steps[index],last=index===steps.length-1;const finish=()=>{onComplete?.();onClose()};return <div className="atlas-tutorial-backdrop" role="dialog" aria-modal="true" aria-label="Atlas guide"><div className="atlas-tutorial"><button className="atlas-tutorial-close" onClick={onClose} aria-label="Close guide"><X/></button><aside><div className="atlas-tutorial-brand">A</div><span>ATLAS GUIDE</span><h2>Build beautifully.<br/>Keep everything connected.</h2><div className="atlas-tutorial-progress">{steps.map((_,i)=><button key={i} className={i===index?'active':i<index?'done':''} onClick={()=>setIndex(i)} aria-label={`Go to guide step ${i+1}`}><span>{i<index?'✓':i+1}</span><small>{steps[i].eyebrow}</small></button>)}</div></aside><main><div className="atlas-tutorial-icon">{step.icon}</div><span className="atlas-tutorial-eyebrow">{step.eyebrow}</span><h1>{step.title}</h1><div className="atlas-tutorial-copy">{step.body}</div><div className="atlas-tutorial-actions"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ArrowLeft/>Back</button><span>{index+1} of {steps.length}</span>{last?<button className="primary" onClick={finish}>Start creating <Check/></button>:<button className="primary" onClick={()=>setIndex(i=>i+1)}>Next <ArrowRight/></button>}</div></main></div></div>}
