import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Compass, Database, Layers3, LayoutTemplate, MousePointer2, Palette, Sparkles, Type, X } from 'lucide-react'

type Props={open:boolean;onClose:()=>void;onComplete?:()=>void}
const steps=[
 {icon:<Sparkles/>,title:'Welcome to Atlas',eyebrow:'THE BIG IDEA',body:<><p>Atlas is a visual workspace builder. Pages are freeform canvases, databases keep reusable information underneath, and views let the same information appear in different ways without creating copies.</p><p>You do not switch into a separate edit mode. The page you use is the page you design. Select something and Atlas opens the controls that belong to it.</p></>},
 {icon:<Compass/>,title:'Dashboard, pages, and data',eyebrow:'YOUR WORKSPACE',body:<><p><strong>Dashboard</strong> is your permanent home base. It is a real canvas and can combine pieces from many parts of your life or work.</p><p><strong>Pages</strong> are focused visual spaces. Build a project hub, reading room, podcast studio, travel board, grimoire, planning page, or something completely different.</p><p><strong>Data</strong> contains reusable collections such as Books, Episodes, Tasks, Trips, Characters, or Transactions. A database stores information. A page decides where and how that information appears.</p></>},
 {icon:<MousePointer2/>,title:'Design directly on the canvas',eyebrow:'SELECT · MOVE · RESIZE',body:<><p>Click an object to select it. Drag it to move it, use its resize handles to change its size, and use the floating <strong>Style</strong> control to open the Inspector.</p><p>The Inspector is contextual. A heading gets typography controls. A widget gets controls for its internal pieces. A database view gets source, view, and card controls. You only see settings that make sense for what you selected.</p><p>The bottom-right dock contains Add, Layers, Assets, and Library. The zoom control at the bottom can be clicked or held, and you can also zoom with Ctrl/Cmd + mouse wheel.</p></>},
 {icon:<Palette/>,title:'Every visible piece can have its own look',eyebrow:'COLOR & SHAPE',body:<><p>Atlas treats composed objects as collections of editable visual parts. A widget can have separate colors for its surface, text, border, input, input text, input border, button, icon, checkbox, checkmark, and other pieces when those pieces exist.</p><p>Color dots show the current color for each channel. Open one to use solid colors, gradients where appropriate, an eyedropper, colors already used on the page, and recently used colors.</p><p>Shape controls include corner radius, opacity, border width, and border style. The goal is simple: if you can point at a distinct visible part, Atlas should increasingly let you customize that part.</p></>},
 {icon:<Type/>,title:'Typography belongs to the object',eyebrow:'FONTS & TEXT',body:<><p>Text-bearing objects can use their own font family, size, weight, line height, letter spacing, alignment, and color. You are not locked into one page-wide font.</p><p>Upload custom fonts through Assets and reuse them around your workspace. The font picker also supports common system fonts and installed font names.</p><p>Text boxes and headings can be typed into directly on the canvas, then refined from the Inspector when you want exact values.</p></>},
 {icon:<Layers3/>,title:'Build with the bottom tool dock',eyebrow:'ADD · LAYERS · ASSETS',body:<><p><strong>Add</strong> is where page objects come from, including text, headings, media, useful widgets, database views, dividers, buttons, decorative surfaces, and other building pieces.</p><p><strong>Layers</strong> controls stacking order and helps you select objects that overlap. Lock objects when you want them to stay put.</p><p><strong>Assets</strong> is your reusable library for images, files, audio, and custom fonts. Add something once, then place it wherever it belongs.</p></>},
 {icon:<LayoutTemplate/>,title:'Templates are starting systems',eyebrow:'LIBRARY',body:<><p>The Library contains complete templates, reusable sections, style systems, and connected-data tools. Dashboard templates are designed as main home screens, while page templates are built for more focused spaces.</p><p>Templates are not permanent themes. After applying one, every piece remains part of the normal canvas. Move it, restyle it, reconnect it, delete it, or combine it with pieces from another system.</p><p>When a template needs a database, Atlas shows the connection before creating or linking anything important.</p></>},
 {icon:<Database/>,title:'Databases store things, views show them',eyebrow:'DATA & VIEWS',body:<><p>A database is a collection. <strong>Episode Ideas</strong> can be a database. Each idea is a record. Properties such as Status, Hook, Guest Idea, Notes, or Captured belong to those records.</p><p>Table, Gallery, Board, and Canvas Card presentations are views of the same records. Changing a record in one place changes the real record, so every connected view can stay in sync.</p><p>You can also place database views directly onto ordinary pages and dashboards. That lets a page show only the slice of a collection that is useful there instead of forcing you to open the master database every time.</p></>},
 {icon:<LayoutTemplate/>,title:'Canvas Cards are designed record views',eyebrow:'CANVAS CARDS',body:<><p>Canvas Cards let database records behave like designed visual cards. The card frame has its own fill, border, radius, and size, while the title, properties, custom text, dividers, buttons, and inputs can be styled and positioned independently.</p><p>The card design is shared by the records in that view, while individual record cards can still have their own positions when you use a freeform canvas layout.</p><p>Use Canvas Cards when the visual presentation of a record matters just as much as the underlying data.</p></>},
 {icon:<Sparkles/>,title:'Widgets are tiny usable interfaces',eyebrow:'FUNCTION + DELIGHT',body:<><p>Widgets are not only decoration. They can capture information, show database counts, display upcoming records, run checklists, show progress, keep notes, track time, display dates, and more.</p><p>Many widgets contain smaller interactive pieces, and Atlas exposes those pieces as separate design channels instead of treating the whole widget as one solid object.</p><p>Some widgets keep their own local content. Others read from a database. Use connected data when the information should stay reusable in more than one place.</p></>},
 {icon:<Check/>,title:'Build the workspace you actually want',eyebrow:'START ANYWHERE',body:<><p>There is no required order. Start with a blank dashboard, place a heading, add a box, connect a database, drop in a widget, apply a template, or simply move things around until the page starts making sense to you.</p><p>When you are unsure how to change something, select the exact thing you want to change. The floating controls and Inspector should reveal what Atlas knows how to do with it.</p><p><strong>Databases provide structure. Views provide perspective. Pages provide composition. Customization gives the whole workspace its personality.</strong></p></>}
]
export default function AtlasTutorial({open,onClose,onComplete}:Props){const[index,setIndex]=useState(0);useEffect(()=>{if(open)setIndex(0)},[open]);if(!open)return null;const step=steps[index],last=index===steps.length-1;const finish=()=>{onComplete?.();onClose()};return <div className="atlas-tutorial-backdrop" role="dialog" aria-modal="true" aria-label="Atlas guide"><div className="atlas-tutorial"><button className="atlas-tutorial-close" onClick={onClose} aria-label="Close guide"><X/></button><aside><div className="atlas-tutorial-brand">A</div><span>ATLAS GUIDE</span><h2>Build the workspace<br/>you actually want.</h2><div className="atlas-tutorial-progress">{steps.map((_,i)=><button key={i} className={i===index?'active':i<index?'done':''} onClick={()=>setIndex(i)} aria-label={`Go to guide step ${i+1}`}><span>{i<index?'✓':i+1}</span><small>{steps[i].eyebrow}</small></button>)}</div></aside><main><div className="atlas-tutorial-icon">{step.icon}</div><span className="atlas-tutorial-eyebrow">{step.eyebrow}</span><h1>{step.title}</h1><div className="atlas-tutorial-copy">{step.body}</div><div className="atlas-tutorial-actions"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ArrowLeft/>Back</button><span>{index+1} of {steps.length}</span>{last?<button className="primary" onClick={finish}>Start creating <Check/></button>:<button className="primary" onClick={()=>setIndex(i=>i+1)}>Next <ArrowRight/></button>}</div></main></div></div>}
