import { PropsWithChildren, useEffect, useMemo, useState, type ReactNode } from 'react'
import { ChevronDown, ChevronRight, CircleHelp, Database as DatabaseIcon, FilePlus2, Folder, FolderPlus, Heart, Home, LogOut, Menu, Plus, Search, Settings, Trash2, X } from 'lucide-react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'
import { createDatabase, createNavFolder, createPage, deleteDatabase, deleteNavFolder, deletePage, getDatabases, getNavFolders, getPages, updateDatabase, updatePage } from '../lib/data'
import { supabase } from '../lib/supabase'
import { useAppContext } from '../App'
import type { Database, NavFolder, Page } from '../types'
import AtlasTutorial from './AtlasTutorial'

export default function AtlasShell({children}:PropsWithChildren){
 const{workspace,user}=useAppContext();const[pages,setPages]=useState<Page[]>([]),[databases,setDatabases]=useState<Database[]>([]),[folders,setFolders]=useState<NavFolder[]>([]),[collapsed,setCollapsed]=useState(false),[searching,setSearching]=useState(false),[query,setQuery]=useState(''),[openGroups,setOpenGroups]=useState<Record<string,boolean>>({favorites:true,pages:true,data:true}),[openNodes,setOpenNodes]=useState<Record<string,boolean>>({}),[guideOpen,setGuideOpen]=useState(false);const navigate=useNavigate(),location=useLocation()
 const guideKey=`atlas-guide-complete:${user.id}`
 const refresh=async()=>{const[p,d]=await Promise.all([getPages(workspace.id),getDatabases(workspace.id)]);setPages(p);setDatabases(d);try{setFolders(await getNavFolders(workspace.id))}catch{setFolders([])}}
 useEffect(()=>{refresh().catch(console.error)},[workspace.id,location.pathname])
 useEffect(()=>{const handler=()=>{refresh().catch(console.error)};window.addEventListener('atlas-workspace-changed',handler);return()=>window.removeEventListener('atlas-workspace-changed',handler)},[workspace.id])
 useEffect(()=>{try{if(!localStorage.getItem(guideKey))setGuideOpen(true)}catch{}},[guideKey])
 const regularPages=useMemo(()=>pages.filter(p=>p.context_type==='page'),[pages]);const pageFolders=useMemo(()=>folders.filter(folder=>folder.kind==='page'),[folders]);const databaseFolders=useMemo(()=>folders.filter(folder=>folder.kind==='database'),[folders]);const favoritePages=useMemo(()=>regularPages.filter(p=>p.favorite),[regularPages]);const favoriteDatabases=useMemo(()=>databases.filter(d=>d.favorite),[databases]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return regularPages;return regularPages.filter(p=>p.title.toLowerCase().includes(q))},[regularPages,query])
 const addPage=async(parent_id:string|null=null)=>{const siblings=regularPages.filter(p=>p.parent_id===parent_id);const p=await createPage(workspace.id,'Untitled page',siblings.length,parent_id);if(parent_id)setOpenNodes(x=>({...x,[parent_id]:true}));await refresh();navigate(`/page/${p.id}`)}
 const addFolder=async(kind:NavFolder['kind'])=>{const name=window.prompt(kind==='page'?'Page folder name':'Data folder name','New folder')?.trim();if(!name)return;const count=folders.filter(folder=>folder.kind===kind).length;await createNavFolder(workspace.id,kind,name,count);await refresh()}
 const removeFolder=async(folder:NavFolder)=>{if(!window.confirm(`Delete folder “${folder.name}”? Its contents will stay in Atlas.`))return;await deleteNavFolder(folder.id);await refresh()}
 const movePageToFolder=async(page:Page)=>{const name=window.prompt('Move to folder. Leave blank for no folder.',pageFolders.find(folder=>folder.id===page.nav_folder_id)?.name||'')?.trim();const folder=name?pageFolders.find(item=>item.name.toLowerCase()===name.toLowerCase())||await createNavFolder(workspace.id,'page',name,pageFolders.length):null;await updatePage(page.id,{nav_folder_id:folder?.id||null});await refresh()}
 const moveDatabaseToFolder=async(database:Database)=>{const name=window.prompt('Move to folder. Leave blank for no folder.',databaseFolders.find(folder=>folder.id===database.nav_folder_id)?.name||'')?.trim();const folder=name?databaseFolders.find(item=>item.name.toLowerCase()===name.toLowerCase())||await createNavFolder(workspace.id,'database',name,databaseFolders.length):null;await updateDatabase(database.id,{nav_folder_id:folder?.id||null});await refresh()}
 const removePage=async(page:Page)=>{if(!window.confirm(`Delete “${page.title}”? This cannot be undone.`))return;try{await deletePage(page.id);await refresh();if(location.pathname.includes(page.id))navigate('/')}catch(error){window.alert(error instanceof Error?error.message:'Atlas could not delete that page. If it contains subpages, remove or move those first.') }}
 const removeDatabase=async(database:Database)=>{if(!window.confirm(`Delete database “${database.name}” and all of its records? This cannot be undone.`))return;try{await deleteDatabase(database.id);await refresh();if(location.pathname.includes(database.id))navigate('/')}catch(error){window.alert(error instanceof Error?error.message:'Atlas could not delete that database.')}}
 const addDatabase=async()=>{const name=window.prompt('What are you tracking?','Untitled database')?.trim();if(!name)return;const db=await createDatabase(workspace.id,name);await refresh();navigate(`/database/${db.id}`)}
 const toggleDatabaseFavorite=async(database:Database)=>{await updateDatabase(database.id,{favorite:!database.favorite});await refresh()}
 const toggle=(key:string)=>setOpenGroups(x=>({...x,[key]:!x[key]}));const toggleNode=(id:string)=>setOpenNodes(x=>({...x,[id]:!x[id]}));const completeGuide=()=>{try{localStorage.setItem(guideKey,'yes')}catch{}}
 return <div className={`atlas-shell ${collapsed?'nav-collapsed':''}`}>
  <aside className="atlas-sidebar" id="atlas-sidebar">
   <div className="atlas-normal-nav">
    <div className="atlas-sidebar-top"><button className="atlas-brand" onClick={()=>navigate('/')}><span>A</span>{!collapsed&&<strong>Atlas</strong>}</button><button className="atlas-nav-collapse" onClick={()=>setCollapsed(v=>!v)}><Menu/></button></div>
    {!collapsed&&<div className="atlas-sidebar-actions">{searching?<div className="atlas-sidebar-search"><Search/><input autoFocus placeholder="Search pages" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{setSearching(false);setQuery('')}}><X/></button></div>:<button onClick={()=>setSearching(true)}><Search/>Search</button>}<NavLink to="/" end><Home/>Dashboard</NavLink></div>}
    {!collapsed&&<div className="atlas-sidebar-scroll">
     {(favoritePages.length>0||favoriteDatabases.length>0)&&!query&&<SidebarSection label="Favorites" icon={<Heart/>} open={openGroups.favorites} onToggle={()=>toggle('favorites')}><SimpleLinks pages={favoritePages} onDelete={removePage}/><DatabaseLinks databases={favoriteDatabases} folders={databaseFolders} onFavorite={toggleDatabaseFavorite} onDelete={removeDatabase} favoriteContext/></SidebarSection>}
     <SidebarSection label={query?'Search results':'Pages'} open={openGroups.pages} onToggle={()=>toggle('pages')} action={!query?<><button onClick={()=>addFolder('page')} title="New page folder"><FolderPlus/></button><button onClick={()=>addPage()} title="New page"><Plus/></button></>:undefined}>{query?<SimpleLinks pages={filtered} onDelete={removePage}/>:<><PageTree pages={regularPages} parentId={null} folderId={null} depth={0} openNodes={openNodes} folders={pageFolders} onToggle={toggleNode} onAdd={addPage} onMove={movePageToFolder} onFavorite={async p=>{await updatePage(p.id,{favorite:!p.favorite});await refresh()}} onDelete={removePage}/>{pageFolders.map(folder=><FolderGroup key={folder.id} folder={folder} open={openNodes[`folder:${folder.id}`]??true} onToggle={()=>toggleNode(`folder:${folder.id}`)} onDelete={()=>void removeFolder(folder)}><PageTree pages={regularPages} parentId={null} folderId={folder.id} depth={0} openNodes={openNodes} folders={pageFolders} onToggle={toggleNode} onAdd={addPage} onMove={movePageToFolder} onFavorite={async p=>{await updatePage(p.id,{favorite:!p.favorite});await refresh()}} onDelete={removePage}/></FolderGroup>)}</>}</SidebarSection>
     {!query&&<SidebarSection label="Data" icon={<DatabaseIcon/>} open={openGroups.data} onToggle={()=>toggle('data')} action={<><button onClick={()=>addFolder('database')} title="New data folder"><FolderPlus/></button><button onClick={addDatabase} title="New database"><Plus/></button></>}><DatabaseLinks databases={databases.filter(database=>!database.nav_folder_id)} folders={databaseFolders} onMove={moveDatabaseToFolder} onFavorite={toggleDatabaseFavorite} onDelete={removeDatabase}/>{databaseFolders.map(folder=><FolderGroup key={folder.id} folder={folder} open={openNodes[`folder:${folder.id}`]??true} onToggle={()=>toggleNode(`folder:${folder.id}`)} onDelete={()=>void removeFolder(folder)}><DatabaseLinks databases={databases.filter(database=>database.nav_folder_id===folder.id)} folders={databaseFolders} onMove={moveDatabaseToFolder} onFavorite={toggleDatabaseFavorite} onDelete={removeDatabase}/></FolderGroup>)}{!databases.length&&<span className="atlas-empty-data-note">No databases yet</span>}</SidebarSection>}
    </div>}
    {collapsed&&<div className="atlas-collapsed-links"><NavLink to="/" title="Dashboard"><Home/></NavLink><button onClick={()=>addPage()} title="New page"><FilePlus2/></button><button onClick={addDatabase} title="New database"><DatabaseIcon/></button><button onClick={()=>setGuideOpen(true)} title="Atlas guide"><CircleHelp/></button></div>}
    <div className="atlas-sidebar-footer">{!collapsed&&<button className="atlas-guide-button" onClick={()=>setGuideOpen(true)}><CircleHelp/>Guide</button>}{!collapsed&&<button><Settings/>Settings</button>}<button onClick={()=>supabase.auth.signOut()}><LogOut/>{!collapsed&&'Sign out'}</button></div>
   </div>
   <div id="atlas-editor-sidebar-host" className="atlas-editor-sidebar-host" />
  </aside>
  {collapsed&&<button className="atlas-nav-reopen" onClick={()=>setCollapsed(false)} title="Open navigation"><ChevronRight/><span>Open navigation</span></button>}
  <section className="atlas-workspace">{children}</section><AtlasTutorial open={guideOpen} onClose={()=>setGuideOpen(false)} onComplete={completeGuide}/>
 </div>
}
function SidebarSection({label,icon,open,onToggle,action,children}:{label:string;icon?:ReactNode;open:boolean;onToggle:()=>void;action?:ReactNode;children:ReactNode}){return <div className="atlas-sidebar-section"><div className="atlas-section-head"><button onClick={onToggle}>{open?<ChevronDown/>:<ChevronRight/>}{icon}{label}</button>{action}</div>{open&&<div className="atlas-section-body">{children}</div>}</div>}
function SimpleLinks({pages,onDelete}:{pages:Page[];onDelete:(page:Page)=>void}){return <>{pages.map(p=><div className="atlas-page-link-row atlas-simple-page-row" key={p.id}><NavLink to={`/page/${p.id}`}><span>{p.icon||'•'}</span>{p.title}</NavLink><div className="atlas-tree-actions"><button className="atlas-nav-delete" title={`Delete ${p.title}`} onClick={()=>onDelete(p)}><Trash2/></button></div></div>)}</>}
function FolderGroup({folder,open,onToggle,onDelete,children}:{folder:NavFolder;open:boolean;onToggle:()=>void;onDelete:()=>void;children:ReactNode}){return <div className="atlas-folder-group"><div className="atlas-folder-head"><button onClick={onToggle}>{open?<ChevronDown/>:<ChevronRight/>}<Folder/>{folder.name}</button><button className="atlas-nav-delete" title={`Delete ${folder.name}`} onClick={onDelete}><Trash2/></button></div>{open&&<div className="atlas-folder-body">{children}</div>}</div>}
function DatabaseLinks({databases,folders,onMove,onFavorite,onDelete,favoriteContext=false}:{databases:Database[];folders:NavFolder[];onMove?:(db:Database)=>void;onFavorite:(db:Database)=>void;onDelete:(db:Database)=>void;favoriteContext?:boolean}){return <div className="atlas-data-links">{databases.map(d=><div className="atlas-data-link-row" key={d.id}><NavLink to={`/database/${d.id}`}><span className="atlas-dot">•</span>{d.name}</NavLink><div className="atlas-tree-actions">{onMove&&<button title={folders.length?'Move database to folder':'Create or move to folder'} onClick={()=>onMove(d)}><Folder/></button>}<button title={d.favorite?'Unfavorite database':'Favorite database'} onClick={()=>onFavorite(d)}><Heart fill={d.favorite?'currentColor':'none'}/></button><button className="atlas-nav-delete" title={`Delete ${d.name}`} onClick={()=>onDelete(d)}><Trash2/></button></div>{favoriteContext&&<span className="atlas-data-kind">DATA</span>}</div>)}</div>}
function PageTree({pages,parentId,folderId,depth,openNodes,folders,onToggle,onAdd,onMove,onFavorite,onDelete}:{pages:Page[];parentId:string|null;folderId?:string|null;depth:number;openNodes:Record<string,boolean>;folders:NavFolder[];onToggle:(id:string)=>void;onAdd:(parent:string|null)=>void;onMove:(p:Page)=>void;onFavorite:(p:Page)=>void;onDelete:(p:Page)=>void}){const children=pages.filter(p=>p.parent_id===parentId&&(parentId!==null||(p.nav_folder_id||null)===(folderId||null)));return <>{children.map(p=>{const childPages=pages.filter(x=>x.parent_id===p.id);const hasChildren=childPages.length>0;const open=openNodes[p.id]??true;return <div className="atlas-tree-node" key={p.id}><div className="atlas-page-link-row" style={{paddingLeft:depth*12}}>{hasChildren?<button className="atlas-tree-toggle" onClick={()=>onToggle(p.id)}>{open?<ChevronDown/>:<ChevronRight/>}</button>:<span className="atlas-tree-spacer"/>}<NavLink to={`/page/${p.id}`}><span>{p.icon||'•'}</span>{p.title}</NavLink><div className="atlas-tree-actions"><button title="Add subpage" onClick={()=>onAdd(p.id)}><Plus/></button><button title={folders.length?'Move page to folder':'Create or move to folder'} onClick={()=>onMove(p)}><Folder/></button><button title={p.favorite?'Unfavorite':'Favorite'} onClick={()=>onFavorite(p)}><Heart fill={p.favorite?'currentColor':'none'}/></button><button className="atlas-nav-delete" title={`Delete ${p.title}`} onClick={()=>onDelete(p)}><Trash2/></button></div></div>{hasChildren&&open&&<PageTree pages={pages} parentId={p.id} depth={depth+1} openNodes={openNodes} folders={folders} onToggle={onToggle} onAdd={onAdd} onMove={onMove} onFavorite={onFavorite} onDelete={onDelete}/>}</div>})}</>}
