import { PropsWithChildren, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { ChevronDown, ChevronRight, CircleHelp, Database as DatabaseIcon, FilePlus2, Folder, FolderPlus, Heart, Home, LogOut, Menu, Plus, Search, Settings, Trash2, X } from 'lucide-react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'
import { createDatabase, createNavFolder, createPage, deleteDatabase, deleteNavFolder, deletePage, getDatabases, getNavFolders, getPages, updateDatabase, updateNavFolder, updatePage } from '../lib/data'
import { supabase } from '../lib/supabase'
import { useAppContext } from '../App'
import type { Database, NavFolder, Page } from '../types'
import AtlasTutorial from './AtlasTutorial'

type NavDragItem={kind:NavFolder['kind'];id:string}
type NavFolderGroup={key:string;name:string;folders:NavFolder[];ids:string[];primary:NavFolder}

const sortByName=<T,>(items:T[],getName:(item:T)=>string)=>[...items].sort((a,b)=>getName(a).localeCompare(getName(b),undefined,{sensitivity:'base'}))
const folderKey=(name:string)=>name.trim().toLowerCase()

export default function AtlasShell({children}:PropsWithChildren){
 const{workspace,user}=useAppContext();const[pages,setPages]=useState<Page[]>([]),[databases,setDatabases]=useState<Database[]>([]),[folders,setFolders]=useState<NavFolder[]>([]),[collapsed,setCollapsed]=useState(false),[searching,setSearching]=useState(false),[query,setQuery]=useState(''),[openGroups,setOpenGroups]=useState<Record<string,boolean>>({favorites:true,pages:true,data:true}),[openNodes,setOpenNodes]=useState<Record<string,boolean>>({}),[guideOpen,setGuideOpen]=useState(false),[folderForm,setFolderForm]=useState<NavFolder['kind']|null>(null),[navDrag,setNavDrag]=useState<NavDragItem|null>(null);const navigate=useNavigate(),location=useLocation()
 const guideKey=`atlas-guide-complete:${user.id}`
 const refresh=async()=>{const[p,d]=await Promise.all([getPages(workspace.id),getDatabases(workspace.id)]);setPages(p);setDatabases(d);try{setFolders(await getNavFolders(workspace.id))}catch{setFolders([])}}
 useEffect(()=>{refresh().catch(console.error)},[workspace.id,location.pathname])
 useEffect(()=>{const handler=()=>{refresh().catch(console.error)};window.addEventListener('atlas-workspace-changed',handler);return()=>window.removeEventListener('atlas-workspace-changed',handler)},[workspace.id])
 useEffect(()=>{try{if(!localStorage.getItem(guideKey))setGuideOpen(true)}catch{}},[guideKey])
 const regularPages=useMemo(()=>pages.filter(p=>p.context_type==='page'),[pages]);const navFolderGroups=useMemo(()=>{const map=new Map<string,NavFolderGroup>();folders.forEach(folder=>{const key=folderKey(folder.name);const found=map.get(key);if(found){found.folders.push(folder);found.ids.push(folder.id);if(found.primary.kind!=='page'&&folder.kind==='page')found.primary=folder}else map.set(key,{key,name:folder.name,folders:[folder],ids:[folder.id],primary:folder})});return sortByName([...map.values()],group=>group.name)},[folders]);const favoritePages=useMemo(()=>regularPages.filter(p=>p.favorite),[regularPages]);const favoriteDatabases=useMemo(()=>databases.filter(d=>d.favorite),[databases]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return regularPages;return regularPages.filter(p=>p.title.toLowerCase().includes(q))},[regularPages,query])
 const addPage=async(parent_id:string|null=null)=>{const siblings=regularPages.filter(p=>p.parent_id===parent_id);const p=await createPage(workspace.id,'Untitled page',siblings.length,parent_id);if(parent_id)setOpenNodes(x=>({...x,[parent_id]:true}));await refresh();navigate(`/page/${p.id}`)}
 const createFolder=async(kind:NavFolder['kind'],name:string)=>{const clean=name.trim();if(!clean)return;const existing=navFolderGroups.find(group=>folderKey(group.name)===folderKey(clean));if(!existing)await createNavFolder(workspace.id,kind,clean,navFolderGroups.length);setFolderForm(null);await refresh()}
 const removeFolder=async(group:NavFolderGroup)=>{if(!window.confirm(`Delete folder “${group.name}”? Its contents will stay in Atlas.`))return;await Promise.all(regularPages.filter(page=>page.nav_folder_id&&group.ids.includes(page.nav_folder_id)).map(page=>updatePage(page.id,{nav_folder_id:null})));await Promise.all(databases.filter(database=>database.nav_folder_id&&group.ids.includes(database.nav_folder_id)).map(database=>updateDatabase(database.id,{nav_folder_id:null})));await Promise.all(group.folders.map(folder=>deleteNavFolder(folder.id)));await refresh()}
 const renameFolder=async(group:NavFolderGroup,name:string)=>{const clean=name.trim();if(!clean||clean===group.name)return;await Promise.all(group.folders.map(folder=>updateNavFolder(folder.id,{name:clean})));await refresh()}
 const renamePage=async(page:Page,title:string)=>{const clean=title.trim();if(!clean||clean===page.title)return;await updatePage(page.id,{title:clean});await refresh();window.dispatchEvent(new Event('atlas-workspace-changed'))}
 const renameDatabase=async(database:Database,name:string)=>{const clean=name.trim();if(!clean||clean===database.name)return;await updateDatabase(database.id,{name:clean});await refresh();window.dispatchEvent(new Event('atlas-workspace-changed'))}
 const moveDraggedToFolder=async(group:NavFolderGroup)=>{if(!navDrag)return;if(navDrag.kind==='page')await updatePage(navDrag.id,{nav_folder_id:group.primary.id,parent_id:null});else await updateDatabase(navDrag.id,{nav_folder_id:group.primary.id});setOpenNodes(x=>({...x,[`folder:${group.key}`]:true}));setNavDrag(null);await refresh()}
 const removePage=async(page:Page)=>{if(!window.confirm(`Delete “${page.title}”? This cannot be undone.`))return;try{await deletePage(page.id);await refresh();if(location.pathname.includes(page.id))navigate('/')}catch(error){window.alert(error instanceof Error?error.message:'Atlas could not delete that page. If it contains subpages, remove or move those first.') }}
 const removeDatabase=async(database:Database)=>{if(!window.confirm(`Delete database “${database.name}” and all of its records? This cannot be undone.`))return;try{await deleteDatabase(database.id);await refresh();if(location.pathname.includes(database.id))navigate('/')}catch(error){window.alert(error instanceof Error?error.message:'Atlas could not delete that database.')}}
 const addDatabase=async()=>{const name=window.prompt('What are you tracking?','Untitled database')?.trim();if(!name)return;const db=await createDatabase(workspace.id,name);await refresh();navigate(`/database/${db.id}`)}
 const toggleDatabaseFavorite=async(database:Database)=>{await updateDatabase(database.id,{favorite:!database.favorite});await refresh()}
 const toggle=(key:string)=>setOpenGroups(x=>({...x,[key]:!x[key]}));const toggleNode=(id:string)=>setOpenNodes(x=>({...x,[id]:!x[id]}));const completeGuide=()=>{try{localStorage.setItem(guideKey,'yes')}catch{}}
 return <div className={`atlas-shell ${collapsed?'nav-collapsed':''}`}>
  <aside className="atlas-sidebar" id="atlas-sidebar">
   <div className="atlas-normal-nav">
    <div className="atlas-sidebar-top"><button className="atlas-brand" onClick={()=>navigate('/')}><span>A</span>{!collapsed&&<strong>Atlas</strong>}</button><button className="atlas-nav-collapse" onClick={()=>setCollapsed(v=>!v)}><Menu/></button></div>
    {!collapsed&&<div className="atlas-sidebar-actions">{searching?<div className="atlas-sidebar-search"><Search/><input autoFocus placeholder="Search pages" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{setSearching(false);setQuery('')}}><X/></button></div>:<button onClick={()=>setSearching(true)}><Search/>Search</button>}<NavLink to="/" end><Home/>Dashboard</NavLink></div>}
    {!collapsed&&<div className="atlas-sidebar-scroll">
     {(favoritePages.length>0||favoriteDatabases.length>0)&&!query&&<SidebarSection label="Favorites" icon={<Heart/>} open={openGroups.favorites} onToggle={()=>toggle('favorites')}><SimpleLinks pages={favoritePages} onRename={renamePage} onDelete={removePage}/><DatabaseLinks databases={favoriteDatabases} onRename={renameDatabase} onFavorite={toggleDatabaseFavorite} onDelete={removeDatabase} favoriteContext/></SidebarSection>}
     <SidebarSection label={query?'Search results':'Pages'} open={openGroups.pages} onToggle={()=>toggle('pages')} action={!query?<><button onClick={()=>setFolderForm(folderForm==='page'?null:'page')} title="New folder"><FolderPlus/></button><button onClick={()=>addPage()} title="New page"><Plus/></button></>:undefined}>{query?<SimpleLinks pages={filtered} onRename={renamePage} onDelete={removePage}/>:<>{folderForm==='page'&&<FolderCreateForm kind="page" onCreate={createFolder} onCancel={()=>setFolderForm(null)}/>}<PageTree pages={sortByName(regularPages.filter(page=>!page.nav_folder_id),page=>page.title)} parentId={null} folderId={null} depth={0} openNodes={openNodes} onToggle={toggleNode} onAdd={addPage} onRename={renamePage} onDragStart={setNavDrag} onDragEnd={()=>setNavDrag(null)} onFavorite={async p=>{await updatePage(p.id,{favorite:!p.favorite});await refresh()}} onDelete={removePage}/>{navFolderGroups.map(group=><FolderGroup key={group.key} group={group} pages={sortByName(regularPages.filter(page=>page.nav_folder_id&&group.ids.includes(page.nav_folder_id)),page=>page.title)} databases={sortByName(databases.filter(database=>database.nav_folder_id&&group.ids.includes(database.nav_folder_id)),database=>database.name)} open={openNodes[`folder:${group.key}`]??true} dragActive={!!navDrag} onToggle={()=>toggleNode(`folder:${group.key}`)} onRename={name=>renameFolder(group,name)} onDrop={()=>void moveDraggedToFolder(group)} onDelete={()=>void removeFolder(group)} pageProps={{openNodes,onToggle:toggleNode,onAdd:addPage,onRename:renamePage,onDragStart:setNavDrag,onDragEnd:()=>setNavDrag(null),onFavorite:async p=>{await updatePage(p.id,{favorite:!p.favorite});await refresh()},onDelete:removePage}} databaseProps={{onRename:renameDatabase,onDragStart:setNavDrag,onDragEnd:()=>setNavDrag(null),onFavorite:toggleDatabaseFavorite,onDelete:removeDatabase}}/>)}</>}</SidebarSection>
     {!query&&<SidebarSection label="Data" icon={<DatabaseIcon/>} open={openGroups.data} onToggle={()=>toggle('data')} action={<><button onClick={()=>setFolderForm(folderForm==='database'?null:'database')} title="New folder"><FolderPlus/></button><button onClick={addDatabase} title="New database"><Plus/></button></>}>{folderForm==='database'&&<FolderCreateForm kind="page" onCreate={createFolder} onCancel={()=>setFolderForm(null)}/>}<DatabaseLinks databases={sortByName(databases.filter(database=>!database.nav_folder_id),database=>database.name)} onRename={renameDatabase} onDragStart={setNavDrag} onDragEnd={()=>setNavDrag(null)} onFavorite={toggleDatabaseFavorite} onDelete={removeDatabase}/>{!databases.length&&<span className="atlas-empty-data-note">No databases yet</span>}</SidebarSection>}
    </div>}
    {collapsed&&<div className="atlas-collapsed-links"><NavLink to="/" title="Dashboard"><Home/></NavLink><button onClick={()=>addPage()} title="New page"><FilePlus2/></button><button onClick={addDatabase} title="New database"><DatabaseIcon/></button><button onClick={()=>setGuideOpen(true)} title="Atlas guide"><CircleHelp/></button></div>}
    <div className="atlas-sidebar-footer">{!collapsed&&<button className="atlas-guide-button" onClick={()=>setGuideOpen(true)}><CircleHelp/>Guide</button>}{!collapsed&&<button><Settings/>Settings</button>}<button onClick={()=>supabase.auth.signOut()}><LogOut/>{!collapsed&&'Sign out'}</button></div>
   </div>
   <div id="atlas-editor-sidebar-host" className="atlas-editor-sidebar-host" />
  </aside>
  {collapsed&&<button className="atlas-nav-reopen" onClick={()=>setCollapsed(false)} title="Open navigation"><ChevronRight/><span>Open navigation</span></button>}
  <section className="atlas-workspace">{children}</section><AtlasTutorial open={guideOpen} onClose={()=>setGuideOpen(false)} onComplete={completeGuide}/>
 </div>
}
function SidebarSection({label,icon,open,onToggle,action,children}:{label:string;icon?:ReactNode;open:boolean;onToggle:()=>void;action?:ReactNode;children:ReactNode}){return <div className="atlas-sidebar-section"><div className="atlas-section-head"><button onClick={onToggle}>{open?<ChevronDown/>:<ChevronRight/>}{icon}{label}</button>{action&&<div className="atlas-section-actions">{action}</div>}</div>{open&&<div className="atlas-section-body">{children}</div>}</div>}
function SimpleLinks({pages,onRename,onDelete}:{pages:Page[];onRename?:(page:Page,title:string)=>void;onDelete:(page:Page)=>void}){return <>{pages.map(p=><div className="atlas-page-link-row atlas-simple-page-row" key={p.id}><NavLink to={`/page/${p.id}`} onDoubleClick={event=>event.preventDefault()}><span>{p.icon||'•'}</span><EditableNavLabel value={p.title} onSave={title=>onRename?.(p,title)}/></NavLink><div className="atlas-tree-actions"><button className="atlas-nav-delete" title={`Delete ${p.title}`} onClick={()=>onDelete(p)}><Trash2/></button></div></div>)}</>}
function FolderCreateForm({kind,onCreate,onCancel}:{kind:NavFolder['kind'];onCreate:(kind:NavFolder['kind'],name:string)=>void;onCancel:()=>void}){const[name,setName]=useState(kind==='page'?'New page folder':'New data folder');const submit=(event:FormEvent)=>{event.preventDefault();void onCreate(kind,name)};return <form className="atlas-folder-create-form" onSubmit={submit}><label><span>{kind==='page'?'Page folder name':'Data folder name'}</span><input autoFocus value={name} onChange={event=>setName(event.target.value)} onFocus={event=>event.currentTarget.select()}/></label><div><button type="button" onClick={onCancel}>Cancel</button><button type="submit">Create</button></div></form>}
function EditableNavLabel({value,onSave,className}:{value:string;onSave:(value:string)=>void;className?:string}){const[editing,setEditing]=useState(false),[draft,setDraft]=useState(value);const save=()=>{const clean=draft.trim();setEditing(false);if(clean&&clean!==value)void onSave(clean);else setDraft(value)};if(editing)return <input className={`atlas-nav-edit-input ${className||''}`} value={draft} autoFocus onChange={event=>setDraft(event.target.value)} onFocus={event=>event.currentTarget.select()} onBlur={save} onClick={event=>event.stopPropagation()} onKeyDown={event=>{if(event.key==='Enter')save();if(event.key==='Escape'){setDraft(value);setEditing(false)}}}/>;return <span className={className} onDoubleClick={event=>{event.preventDefault();event.stopPropagation();setDraft(value);setEditing(true)}}>{value}</span>}
function FolderGroup({group,pages,databases,open,dragActive,onToggle,onRename,onDrop,onDelete,pageProps,databaseProps}:{group:NavFolderGroup;pages:Page[];databases:Database[];open:boolean;dragActive:boolean;onToggle:()=>void;onRename:(name:string)=>void;onDrop:()=>void;onDelete:()=>void;pageProps:Omit<PageTreeProps,'pages'|'parentId'|'folderId'|'depth'>;databaseProps:Omit<DatabaseLinksProps,'databases'|'favoriteContext'>}){return <div className={`atlas-folder-group ${dragActive?'drop-ready':''}`} onDragOver={event=>{if(dragActive)event.preventDefault()}} onDrop={event=>{event.preventDefault();event.stopPropagation();onDrop()}}><div className="atlas-folder-head"><button onClick={onToggle}>{open?<ChevronDown/>:<ChevronRight/>}<Folder/><EditableNavLabel value={group.name} onSave={onRename}/></button><button className="atlas-nav-delete" title={`Delete ${group.name}`} onClick={onDelete}><Trash2/></button></div>{open&&<div className="atlas-folder-body">{pages.length>0&&<><span className="atlas-folder-divider">Pages</span><PageTree pages={pages} parentId={null} depth={0} {...pageProps}/></>}{databases.length>0&&<><span className="atlas-folder-divider">Data</span><DatabaseLinks databases={databases} {...databaseProps}/></>}{!pages.length&&!databases.length&&<span className="atlas-folder-empty">Empty folder</span>}</div>}</div>}
type DatabaseLinksProps={databases:Database[];onRename?:(db:Database,name:string)=>void;onDragStart?:(item:NavDragItem)=>void;onDragEnd?:()=>void;onFavorite:(db:Database)=>void;onDelete:(db:Database)=>void;favoriteContext?:boolean}
function DatabaseLinks({databases,onRename,onDragStart,onDragEnd,onFavorite,onDelete,favoriteContext=false}:DatabaseLinksProps){return <div className="atlas-data-links">{databases.map(d=><div className="atlas-data-link-row" key={d.id} draggable={!!onDragStart} onDragStart={()=>onDragStart?.({kind:'database',id:d.id})} onDragEnd={onDragEnd}><NavLink to={`/database/${d.id}`} onDoubleClick={event=>event.preventDefault()}><span className="atlas-dot">•</span><EditableNavLabel value={d.name} onSave={name=>onRename?.(d,name)}/></NavLink><div className="atlas-tree-actions"><button title={d.favorite?'Unfavorite database':'Favorite database'} onClick={()=>onFavorite(d)}><Heart fill={d.favorite?'currentColor':'none'}/></button><button className="atlas-nav-delete" title={`Delete ${d.name}`} onClick={()=>onDelete(d)}><Trash2/></button></div>{favoriteContext&&<span className="atlas-data-kind">DATA</span>}</div>)}</div>}
type PageTreeProps={pages:Page[];parentId:string|null;folderId?:string|null;depth:number;openNodes:Record<string,boolean>;onToggle:(id:string)=>void;onAdd:(parent:string|null)=>void;onRename:(page:Page,title:string)=>void;onDragStart:(item:NavDragItem)=>void;onDragEnd:()=>void;onFavorite:(p:Page)=>void;onDelete:(p:Page)=>void}
function PageTree({pages,parentId,depth,openNodes,onToggle,onAdd,onRename,onDragStart,onDragEnd,onFavorite,onDelete}:PageTreeProps){const children=sortByName(pages.filter(p=>p.parent_id===parentId),page=>page.title);return <>{children.map(p=>{const childPages=pages.filter(x=>x.parent_id===p.id);const hasChildren=childPages.length>0;const open=openNodes[p.id]??true;return <div className="atlas-tree-node" key={p.id}><div className="atlas-page-link-row" style={{paddingLeft:depth*12}} draggable onDragStart={()=>onDragStart({kind:'page',id:p.id})} onDragEnd={onDragEnd}>{hasChildren?<button className="atlas-tree-toggle" onClick={()=>onToggle(p.id)}>{open?<ChevronDown/>:<ChevronRight/>}</button>:<span className="atlas-tree-spacer"/>}<NavLink to={`/page/${p.id}`} onDoubleClick={event=>event.preventDefault()}><span>{p.icon||'•'}</span><EditableNavLabel value={p.title} onSave={title=>onRename(p,title)}/></NavLink><div className="atlas-tree-actions"><button title="Add subpage" onClick={()=>onAdd(p.id)}><Plus/></button><button title={p.favorite?'Unfavorite':'Favorite'} onClick={()=>onFavorite(p)}><Heart fill={p.favorite?'currentColor':'none'}/></button><button className="atlas-nav-delete" title={`Delete ${p.title}`} onClick={()=>onDelete(p)}><Trash2/></button></div></div>{hasChildren&&open&&<PageTree pages={pages} parentId={p.id} depth={depth+1} openNodes={openNodes} onToggle={onToggle} onAdd={onAdd} onRename={onRename} onDragStart={onDragStart} onDragEnd={onDragEnd} onFavorite={onFavorite} onDelete={onDelete}/>}</div>})}</>}
