import { useEffect, useMemo, useState } from 'react'
import { AlignCenter, AlignLeft, AlignRight, Minus, Plus, Trash2, Type } from 'lucide-react'
import { getFields } from '../lib/data'
import type { Database, Field } from '../types'
import { ensureCanvasCardTemplate, type CanvasCardElement, type CanvasCardTemplate } from './CanvasCardView'

type Patch=Record<string,unknown>
type Props={config:Record<string,unknown>;databases:Database[];save:(patch:Patch)=>void}
type Mode='gallery'|'list'|'rail'|'board'|'table'|'canvas'
const modes:Array<{id:Mode;label:string}>=[{id:'gallery',label:'Gallery'},{id:'list',label:'List'},{id:'rail',label:'Rail'},{id:'board',label:'Board'},{id:'table',label:'Table'},{id:'canvas',label:'Canvas Cards'}]

export default function CanvasCardSidebar({config,databases,save}:Props){
 const databaseId=String(config.databaseId||''),mode=String(config.mode||'gallery') as Mode
 const[fields,setFields]=useState<Field[]>([])
 useEffect(()=>{let alive=true;if(!databaseId){setFields([]);return()=>{alive=false}};getFields(databaseId).then(next=>{if(alive)setFields(next.filter(field=>field.name.trim().toLowerCase()!=='name'))}).catch(()=>{if(alive)setFields([])});return()=>{alive=false}},[databaseId])
 const template=useMemo(()=>ensureCanvasCardTemplate(config.canvasCardTemplate,fields),[config.canvasCardTemplate,fields])
 const selectedId=String(config.canvasCardSelectedElementId||'__card__')
 const selected=template.elements.find(element=>element.id===selectedId)||null
 const saveTemplate=(next:CanvasCardTemplate)=>save({canvasCardTemplate:next})
 const patchElement=(id:string,patch:Partial<CanvasCardElement>)=>saveTemplate({...template,elements:template.elements.map(element=>element.id===id?{...element,...patch}:element)})
 const addElement=(element:CanvasCardElement)=>{saveTemplate({...template,elements:[...template.elements,element]});save({canvasCardSelectedElementId:element.id})}
 const removeSelected=()=>{if(!selected)return;saveTemplate({...template,elements:template.elements.filter(element=>element.id!==selected.id)});save({canvasCardSelectedElementId:'__card__'})}
 const addField=(field:Field)=>addElement({id:`field-${field.id}-${Date.now()}`,kind:'field',fieldId:field.id,x:18,y:Math.max(84,template.height-52),width:Math.max(100,template.width-36),height:24,zIndex:template.elements.length+2,fontFamily:'Arial, sans-serif',fontSize:12,fontWeight:500,textColor:'#635a52'})
 const addText=()=>addElement({id:`text-${Date.now()}`,kind:'text',text:'Custom text',x:18,y:18,width:130,height:28,zIndex:template.elements.length+2,fontFamily:'Georgia, serif',fontSize:14,fontWeight:500,textColor:'#3b332e'})
 const addDivider=()=>addElement({id:`divider-${Date.now()}`,kind:'divider',x:18,y:Math.max(30,template.height/2),width:Math.max(60,template.width-36),height:1,zIndex:template.elements.length+2,background:'#ded5ca'})
 const addOpen=()=>addElement({id:`open-${Date.now()}`,kind:'open',text:'Open',x:18,y:Math.max(30,template.height-46),width:72,height:28,zIndex:template.elements.length+2,fontFamily:'Arial, sans-serif',fontSize:11,fontWeight:700,textColor:'#fff',background:'#2e2925',radius:9,textAlign:'center'})
 return <div className="atlas-canvas-card-sidebar">
  <Section title="View"><Control label="Presentation"><select value={mode} onChange={e=>save({mode:e.target.value,recordLayoutMode:'auto',canvasCardSelectedElementId:'__card__'})}>{modes.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></Control></Section>
  <Section title="Data"><Control label="Records from"><select value={databaseId} onChange={e=>save({databaseId:e.target.value,filterFieldId:'',filterValue:'',sortFieldId:'',canvasCardSelectedElementId:'__card__'})}><option value="">Choose a collection</option>{databases.map(db=><option key={db.id} value={db.id}>{db.name}</option>)}</select></Control>{mode==='canvas'&&databaseId&&<><div className="atlas-control-grid two"><Control label="Filter field"><select value={String(config.filterFieldId||'')} onChange={e=>save({filterFieldId:e.target.value,filterValue:''})}><option value="">No filter</option>{fields.map(field=><option key={field.id} value={field.id}>{field.name}</option>)}</select></Control><Control label="Matches"><input value={String(config.filterValue||'')} disabled={!config.filterFieldId} onChange={e=>save({filterValue:e.target.value})}/></Control></div><div className="atlas-control-grid two"><Control label="Sort by"><select value={String(config.sortFieldId||'')} onChange={e=>save({sortFieldId:e.target.value})}><option value="">Default</option>{fields.map(field=><option key={field.id} value={field.id}>{field.name}</option>)}</select></Control><Control label="Direction"><select value={String(config.sortDirection||'asc')} disabled={!config.sortFieldId} onChange={e=>save({sortDirection:e.target.value})}><option value="asc">Ascending</option><option value="desc">Descending</option></select></Control></div></>}</Section>
  {mode==='canvas'&&<><Section title="Layout"><div className="atlas-control-grid two"><Control label="Card width"><input type="number" min="80" value={template.width} onChange={e=>saveTemplate({...template,width:+e.target.value})}/></Control><Control label="Card height"><input type="number" min="60" value={template.height} onChange={e=>saveTemplate({...template,height:+e.target.value})}/></Control></div><Control label="Record limit"><input type="number" min="1" max="100" value={Number(config.limit||24)} onChange={e=>save({limit:+e.target.value})}/></Control></Section>
  <Section title="Card Design"><p className="atlas-helper">Click the card or one of its pieces on the canvas. Drag pieces to move them and use the corner handle to resize.</p><div className="atlas-card-add-row"><label><Plus/>Property<select value="" onChange={e=>{const field=fields.find(item=>item.id===e.target.value);if(field)addField(field);e.currentTarget.value=''}}><option value="">Choose…</option>{fields.map(field=><option key={field.id} value={field.id}>{field.name}</option>)}</select></label><button onClick={addText}><Type/>Text</button><button onClick={addDivider}><Minus/>Divider</button><button onClick={addOpen}><Plus/>Open</button></div>{selected?<ElementControls element={selected} field={selected.fieldId?fields.find(field=>field.id===selected.fieldId):undefined} patch={patch=>patchElement(selected.id,patch)} remove={removeSelected}/>:<CardControls template={template} saveTemplate={saveTemplate}/>}</Section>
  <Section title="Behavior"><label className="atlas-sidebar-toggle"><input type="checkbox" checked={Boolean(config.inlineEditing)} onChange={e=>save({inlineEditing:e.target.checked})}/><span><strong>Inline editing</strong><small>Edit property values directly on cards in Use mode.</small></span></label><label className="atlas-sidebar-toggle"><input type="checkbox" checked={config.allowCreate!==false} onChange={e=>save({allowCreate:e.target.checked})}/><span><strong>Quick add</strong><small>Show a New record action below the view.</small></span></label></Section></>}
 </div>
}

function CardControls({template,saveTemplate}:{template:CanvasCardTemplate;saveTemplate:(next:CanvasCardTemplate)=>void}){return <div className="atlas-card-selected-controls"><div className="atlas-selected-subhead"><strong>Card</strong><small>Background and frame</small></div><div className="atlas-control-grid two"><Control label="Background"><input type="color" value={safeColor(template.background,'#fffdfa')} onChange={e=>saveTemplate({...template,background:e.target.value})}/></Control><Control label="Border"><input type="color" value={safeColor(template.borderColor,'#d8cec2')} onChange={e=>saveTemplate({...template,borderColor:e.target.value})}/></Control><Control label="Border width"><input type="number" min="0" value={template.borderWidth} onChange={e=>saveTemplate({...template,borderWidth:+e.target.value})}/></Control><Control label="Radius"><input type="number" min="0" value={template.radius} onChange={e=>saveTemplate({...template,radius:+e.target.value})}/></Control></div><label className="atlas-sidebar-toggle compact"><input type="checkbox" checked={template.shadow} onChange={e=>saveTemplate({...template,shadow:e.target.checked})}/><span><strong>Shadow</strong></span></label></div>}

function ElementControls({element,field,patch,remove}:{element:CanvasCardElement;field?:Field;patch:(patch:Partial<CanvasCardElement>)=>void;remove:()=>void}){return <div className="atlas-card-selected-controls"><div className="atlas-selected-subhead"><div><strong>{element.kind==='field'?field?.name||'Property':element.kind==='title'?'Title':element.kind==='open'?'Open button':element.kind}</strong><small>Selected card element</small></div><button className="atlas-inline-danger" onClick={remove}><Trash2/>Delete</button></div><div className="atlas-control-grid four"><Control label="X"><input type="number" value={element.x} onChange={e=>patch({x:+e.target.value})}/></Control><Control label="Y"><input type="number" value={element.y} onChange={e=>patch({y:+e.target.value})}/></Control><Control label="W"><input type="number" min="20" value={element.width} onChange={e=>patch({width:+e.target.value})}/></Control><Control label="H"><input type="number" min="12" value={element.height} onChange={e=>patch({height:+e.target.value})}/></Control></div><div className="atlas-control-grid two"><Control label="Layer"><input type="number" min="1" value={element.zIndex} onChange={e=>patch({zIndex:+e.target.value})}/></Control><Control label="Opacity"><input type="number" min="0" max="1" step="0.05" value={element.opacity??1} onChange={e=>patch({opacity:+e.target.value})}/></Control></div>{(element.kind==='text'||element.kind==='open')&&<Control label="Text"><input value={element.text||''} onChange={e=>patch({text:e.target.value})}/></Control>}{element.kind!=='divider'&&<><Control label="Font"><input value={element.fontFamily||''} placeholder="Georgia, serif" onChange={e=>patch({fontFamily:e.target.value})}/></Control><div className="atlas-control-grid two"><Control label="Size"><input type="number" min="6" value={element.fontSize||14} onChange={e=>patch({fontSize:+e.target.value})}/></Control><Control label="Weight"><input type="number" min="100" max="900" step="100" value={element.fontWeight||400} onChange={e=>patch({fontWeight:+e.target.value})}/></Control><Control label="Text color"><input type="color" value={safeColor(element.textColor,'#2b2521')} onChange={e=>patch({textColor:e.target.value})}/></Control><Control label="Background"><input type="color" value={safeColor(element.background,'#ffffff')} onChange={e=>patch({background:e.target.value})}/></Control></div><div className="atlas-align-row"><button className={element.textAlign==='left'||!element.textAlign?'active':''} onClick={()=>patch({textAlign:'left'})}><AlignLeft/></button><button className={element.textAlign==='center'?'active':''} onClick={()=>patch({textAlign:'center'})}><AlignCenter/></button><button className={element.textAlign==='right'?'active':''} onClick={()=>patch({textAlign:'right'})}><AlignRight/></button></div></>}</div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="atlas-canvas-sidebar-section"><div className="atlas-edit-section-title">{title}</div>{children}</section>}
function Control({label,children}:{label:string;children:React.ReactNode}){return <label className="atlas-control"><span>{label}</span>{children}</label>}
function safeColor(value:unknown,fallback:string){const text=String(value||'');return /^#[0-9a-fA-F]{6}$/.test(text)?text:fallback}
