import { useMemo, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from 'react'
import { AlignCenter, AlignLeft, AlignRight, Grip, Minus, Plus, Trash2, Type } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Field, RecordRow } from '../types'

type ElementKind='title'|'field'|'text'|'divider'|'open'
export type CanvasCardElement={id:string;kind:ElementKind;fieldId?:string;text?:string;x:number;y:number;width:number;height:number;zIndex:number;fontFamily?:string;fontSize?:number;fontWeight?:number;textColor?:string;background?:string;borderColor?:string;borderWidth?:number;radius?:number;textAlign?:'left'|'center'|'right';padding?:number;opacity?:number}
export type CanvasCardTemplate={width:number;height:number;background:string;borderColor:string;borderWidth:number;radius:number;shadow:boolean;elements:CanvasCardElement[]}

type Props={records:RecordRow[];fields:Field[];databaseId:string;editing:boolean;template:CanvasCardTemplate;onChangeTemplate:(next:CanvasCardTemplate)=>void;inlineEditing:boolean;onPatchField:(record:RecordRow,fieldId:string,value:unknown)=>void;showCreate?:boolean;onCreate?:()=>void}

const starter=(fields:Field[]):CanvasCardTemplate=>({width:260,height:170,background:'#fffdfa',borderColor:'#d8cec2',borderWidth:1,radius:20,shadow:false,elements:[{id:'title',kind:'title',x:18,y:18,width:220,height:38,zIndex:4,fontFamily:'Georgia, serif',fontSize:22,fontWeight:600,textColor:'#2b2521'},{id:'divider',kind:'divider',x:18,y:64,width:224,height:1,zIndex:2,background:'#e6ddd2'},...fields.slice(0,3).map((f,i)=>({id:`field-${f.id}`,kind:'field' as const,fieldId:f.id,x:18,y:78+i*27,width:220,height:24,zIndex:3,fontFamily:'Arial, sans-serif',fontSize:12,fontWeight:500,textColor:'#635a52'})),{id:'open',kind:'open',text:'Open',x:172,y:132,width:70,height:26,zIndex:5,fontFamily:'Arial, sans-serif',fontSize:11,fontWeight:700,textColor:'#fff',background:'#2e2925',radius:9,textAlign:'center'}]})

export function ensureCanvasCardTemplate(raw:unknown,fields:Field[]):CanvasCardTemplate{if(raw&&typeof raw==='object'){const v=raw as Partial<CanvasCardTemplate>;if(Array.isArray(v.elements))return {width:Number(v.width||260),height:Number(v.height||170),background:String(v.background||'#fffdfa'),borderColor:String(v.borderColor||'#d8cec2'),borderWidth:Number(v.borderWidth??1),radius:Number(v.radius??20),shadow:Boolean(v.shadow),elements:v.elements as CanvasCardElement[]}}return starter(fields)}

export default function CanvasCardView({records,fields,databaseId,editing,template,onChangeTemplate,inlineEditing,onPatchField,showCreate,onCreate}:Props){
 const[selected,setSelected]=useState<string|null>(null)
 const fieldMap=useMemo(()=>new Map(fields.map(f=>[f.id,f])),[fields])
 const selectedElement=template.elements.find(el=>el.id===selected)||null
 const patchElement=(id:string,patch:Partial<CanvasCardElement>)=>onChangeTemplate({...template,elements:template.elements.map(el=>el.id===id?{...el,...patch}:el)})
 const removeElement=(id:string)=>{onChangeTemplate({...template,elements:template.elements.filter(el=>el.id!==id)});if(selected===id)setSelected(null)}
 const addElement=(element:CanvasCardElement)=>onChangeTemplate({...template,elements:[...template.elements,element]})
 const addField=(field:Field)=>addElement({id:`field-${field.id}-${Date.now()}`,kind:'field',fieldId:field.id,x:18,y:Math.max(84,template.height-52),width:Math.max(100,template.width-36),height:24,zIndex:template.elements.length+2,fontFamily:'Arial, sans-serif',fontSize:12,fontWeight:500,textColor:'#635a52'})
 const addText=()=>addElement({id:`text-${Date.now()}`,kind:'text',text:'Custom text',x:18,y:18,width:130,height:28,zIndex:template.elements.length+2,fontFamily:'Georgia, serif',fontSize:14,fontWeight:500,textColor:'#3b332e'})
 const addDivider=()=>addElement({id:`divider-${Date.now()}`,kind:'divider',x:18,y:Math.max(30,template.height/2),width:Math.max(60,template.width-36),height:1,zIndex:template.elements.length+2,background:'#ded5ca'})
 const addOpen=()=>addElement({id:`open-${Date.now()}`,kind:'open',text:'Open',x:18,y:Math.max(30,template.height-46),width:72,height:28,zIndex:template.elements.length+2,fontFamily:'Arial, sans-serif',fontSize:11,fontWeight:700,textColor:'#fff',background:'#2e2925',radius:9,textAlign:'center'})
 return <div className="canvas-card-view">
  <div className="canvas-card-records">{records.map(record=><article className="canvas-card-instance" key={record.id} style={{width:template.width,height:template.height,background:template.background,border:`${template.borderWidth}px solid ${template.borderColor}`,borderRadius:template.radius,boxShadow:template.shadow?'0 16px 34px rgba(42,32,24,.13)':'none'}}>{template.elements.map(el=><CanvasElement key={el.id} el={el} record={record} field={el.fieldId?fieldMap.get(el.fieldId):undefined} databaseId={databaseId} editing={editing} selected={selected===el.id} onSelect={()=>setSelected(el.id)} onPatch={patch=>patchElement(el.id,patch)} onRemove={()=>removeElement(el.id)} inlineEditing={inlineEditing&&!editing} onPatchField={(fieldId,value)=>onPatchField(record,fieldId,value)}/>)}</article>)}</div>
  {editing&&<div className="canvas-card-designer">
    <div className="canvas-card-designer-bar"><div><strong>Canvas card</strong><span>{template.width} × {template.height}</span></div><label>W<input type="number" min="80" value={template.width} onChange={e=>onChangeTemplate({...template,width:+e.target.value})}/></label><label>H<input type="number" min="60" value={template.height} onChange={e=>onChangeTemplate({...template,height:+e.target.value})}/></label><label>Background<input type="color" value={safeColor(template.background,'#fffdfa')} onChange={e=>onChangeTemplate({...template,background:e.target.value})}/></label><label>Border<input type="color" value={safeColor(template.borderColor,'#d8cec2')} onChange={e=>onChangeTemplate({...template,borderColor:e.target.value})}/></label><label>Radius<input type="number" min="0" value={template.radius} onChange={e=>onChangeTemplate({...template,radius:+e.target.value})}/></label><label className="canvas-card-check"><input type="checkbox" checked={template.shadow} onChange={e=>onChangeTemplate({...template,shadow:e.target.checked})}/>Shadow</label></div>
    <div className="canvas-card-tool-row"><div className="canvas-card-add-field"><Plus/>Field<select value="" onChange={e=>{const field=fields.find(f=>f.id===e.target.value);if(field)addField(field);e.currentTarget.value=''}}><option value="">Choose…</option>{fields.map(field=><option key={field.id} value={field.id}>{field.name}</option>)}</select></div><button onClick={addText}><Type/>Text</button><button onClick={addDivider}><Minus/>Divider</button><button onClick={addOpen}><Plus/>Open button</button></div>
    {selectedElement&&<ElementInspector element={selectedElement} field={selectedElement.fieldId?fieldMap.get(selectedElement.fieldId):undefined} onPatch={patch=>patchElement(selectedElement.id,patch)} onDelete={()=>removeElement(selectedElement.id)}/>} 
  </div>}
  {showCreate&&onCreate&&<button className="db-live-add" onClick={onCreate}><Plus/>New record</button>}
 </div>
}

function ElementInspector({element,field,onPatch,onDelete}:{element:CanvasCardElement;field?:Field;onPatch:(patch:Partial<CanvasCardElement>)=>void;onDelete:()=>void}){return <div className="canvas-card-inspector"><div className="canvas-card-inspector-head"><div><small>SELECTED</small><strong>{element.kind==='field'?field?.name||'Field':element.kind}</strong></div><button className="danger" onClick={onDelete}><Trash2/>Delete</button></div><div className="canvas-card-inspector-grid"><label>X<input type="number" value={element.x} onChange={e=>onPatch({x:+e.target.value})}/></label><label>Y<input type="number" value={element.y} onChange={e=>onPatch({y:+e.target.value})}/></label><label>Width<input type="number" min="20" value={element.width} onChange={e=>onPatch({width:+e.target.value})}/></label><label>Height<input type="number" min="12" value={element.height} onChange={e=>onPatch({height:+e.target.value})}/></label><label>Layer<input type="number" min="1" value={element.zIndex} onChange={e=>onPatch({zIndex:+e.target.value})}/></label><label>Opacity<input type="number" min="0" max="1" step="0.05" value={element.opacity??1} onChange={e=>onPatch({opacity:+e.target.value})}/></label></div>{element.kind==='text'||element.kind==='open'?<label className="canvas-card-wide">Text<input value={element.text||''} onChange={e=>onPatch({text:e.target.value})}/></label>:null}{element.kind!=='divider'&&<><div className="canvas-card-inspector-grid"><label>Font<input value={element.fontFamily||''} placeholder="Georgia, serif" onChange={e=>onPatch({fontFamily:e.target.value})}/></label><label>Size<input type="number" min="6" value={element.fontSize||14} onChange={e=>onPatch({fontSize:+e.target.value})}/></label><label>Weight<input type="number" min="100" max="900" step="100" value={element.fontWeight||400} onChange={e=>onPatch({fontWeight:+e.target.value})}/></label><label>Text color<input type="color" value={safeColor(element.textColor,'#2b2521')} onChange={e=>onPatch({textColor:e.target.value})}/></label><label>Background<input type="color" value={safeColor(element.background,'#ffffff')} onChange={e=>onPatch({background:e.target.value})}/></label><label>Radius<input type="number" min="0" value={element.radius||0} onChange={e=>onPatch({radius:+e.target.value})}/></label></div><div className="canvas-card-align"><button className={element.textAlign==='left'||!element.textAlign?'active':''} onClick={()=>onPatch({textAlign:'left'})}><AlignLeft/></button><button className={element.textAlign==='center'?'active':''} onClick={()=>onPatch({textAlign:'center'})}><AlignCenter/></button><button className={element.textAlign==='right'?'active':''} onClick={()=>onPatch({textAlign:'right'})}><AlignRight/></button></div></>}</div>}

function CanvasElement({el,record,field,databaseId,editing,selected,onSelect,onPatch,onRemove,inlineEditing,onPatchField}:{el:CanvasCardElement;record:RecordRow;field?:Field;databaseId:string;editing:boolean;selected:boolean;onSelect:()=>void;onPatch:(patch:Partial<CanvasCardElement>)=>void;onRemove:()=>void;inlineEditing:boolean;onPatchField:(fieldId:string,value:unknown)=>void}){const style:CSSProperties={position:'absolute',left:el.x,top:el.y,width:el.width,height:el.height,zIndex:el.zIndex,fontFamily:el.fontFamily,fontSize:el.fontSize,fontWeight:el.fontWeight,color:el.textColor,background:el.background,border:el.borderWidth?`${el.borderWidth}px solid ${el.borderColor||'transparent'}`:'0',borderRadius:el.radius,textAlign:el.textAlign,padding:el.padding,boxSizing:'border-box',opacity:el.opacity??1};const drag=(event:ReactPointerEvent<HTMLDivElement>)=>{if(!editing||(event.target as HTMLElement).closest('input,select,button,a'))return;event.preventDefault();event.stopPropagation();onSelect();const target=event.currentTarget,sx=event.clientX,sy=event.clientY,ox=el.x,oy=el.y;target.setPointerCapture(event.pointerId);const move=(e:PointerEvent)=>onPatch({x:Math.max(0,ox+e.clientX-sx),y:Math.max(0,oy+e.clientY-sy)});const up=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',up)};target.addEventListener('pointermove',move);target.addEventListener('pointerup',up)};return <div className={`canvas-card-element ${selected&&editing?'selected':''}`} style={style} onPointerDown={drag} onClick={e=>{if(editing){e.preventDefault();e.stopPropagation();onSelect()}}}>{editing&&selected&&<><Grip className="canvas-card-grip"/><button className="canvas-card-delete" onClick={onRemove}><Trash2/></button><button className="canvas-card-resize" onPointerDown={e=>{e.preventDefault();e.stopPropagation();const sx=e.clientX,sy=e.clientY,ow=el.width,oh=el.height,target=e.currentTarget;target.setPointerCapture(e.pointerId);const move=(p:PointerEvent)=>onPatch({width:Math.max(20,ow+p.clientX-sx),height:Math.max(12,oh+p.clientY-sy)});const up=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',up)};target.addEventListener('pointermove',move);target.addEventListener('pointerup',up)}}/></>}{el.kind==='title'?<Link to={`/database/${databaseId}/record/${record.id}`}>{record.title}</Link>:el.kind==='field'&&field?<FieldValue field={field} value={record.data?.[field.id]} editing={inlineEditing} onChange={value=>onPatchField(field.id,value)}/>:el.kind==='text'?<span>{el.text||'Text'}</span>:el.kind==='divider'?<span className="canvas-card-divider"/>:el.kind==='open'?<Link className="canvas-card-open" to={`/database/${databaseId}/record/${record.id}`}>{el.text||'Open'}</Link>:null}</div>}

function FieldValue({field,value,editing,onChange}:{field:Field;value:unknown;editing:boolean;onChange:(value:unknown)=>void}){const options=Array.isArray(field.config?.options)?field.config.options.map(String):[];if(field.type==='image'&&!editing){const src=String(value||'');return src?<img className="canvas-card-field-image" src={src} alt=""/>:<span/>}if(!editing)return <span>{Array.isArray(value)?value.join(', '):field.type==='checkbox'?(value?'Yes':'No'):String(value??'')}</span>;if(field.type==='checkbox')return <input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>;if(field.type==='select'||field.type==='status')return <select value={String(value??'')} onChange={e=>onChange(e.target.value)}><option value="">None</option>{options.map(option=><option key={option}>{option}</option>)}</select>;if(field.type==='date')return <input type="date" value={String(value??'')} onChange={e=>onChange(e.target.value)}/>;if(field.type==='number')return <input type="number" value={String(value??'')} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/>;return <input value={String(value??'')} onChange={e=>onChange(e.target.value)}/>}

function safeColor(value:unknown,fallback:string){const text=String(value||'');return /^#[0-9a-fA-F]{6}$/.test(text)?text:fallback}
