import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { AlignCenter, AlignLeft, AlignRight, ArrowDown, ArrowUp, Copy, Database, Eye, EyeOff, Heading, Image, Layers, LayoutTemplate, Lock, Minus, MousePointer2, Palette, Plus, Quote, Square, Trash2, Type, Unlock, Upload } from 'lucide-react'
import { deleteAsset, getAssets, loadFontAsset, uploadAsset, type AtlasAsset } from '../lib/assets'
import type { Database as DatabaseType, Field, Page, PageBlock, PageBlockType, RecordRow } from '../types'
import CollectionDataPanel from './CollectionDataPanel'
import TemplatePanel from './TemplatePanel'
import WidgetSettings from './WidgetSettings'
import CanvasCardSidebar from './CanvasCardSidebar'

type Patch = Record<string, unknown>
type Tab = 'add' | 'selected' | 'data' | 'layers' | 'templates' | 'assets'
type Props = { workspaceId:string; userId:string; page:Page; blocks:PageBlock[]; selected:PageBlock|null; databases:DatabaseType[]; database:DatabaseType|null; record:RecordRow|null; fields:Field[]; onAdd:(type:PageBlockType)=>void; onAddPageTitle:()=>void; onAddPageCover:()=>void; onSelectBlock:(id:string|null)=>void; onSaveBlock:(id:string,patch:Patch)=>void; onDeleteBlock:(id:string)=>void; onDuplicateBlock:(id:string)=>void; onSavePage:(patch:Partial<Page>)=>void; onSavePageSettings:(patch:Patch)=>void; onOpenData:()=>void; onDone:()=>void }

export default function EditorSidebar(props:Props){
 const [tab,setTab]=useState<Tab>('add'),[assets,setAssets]=useState<AtlasAsset[]>([]),[assetError,setAssetError]=useState(''),[uploading,setUploading]=useState(false)
 useEffect(()=>{getAssets(props.workspaceId).then(setAssets).catch(e=>setAssetError(e instanceof Error?e.message:String(e)))},[props.workspaceId])
 useEffect(()=>{if(props.selected)setTab('selected')},[props.selected?.id])
 const ordered=useMemo(()=>[...props.blocks].sort((a,b)=>num(b.config.zIndex,1)-num(a.config.zIndex,1)),[props.blocks])
 const images=assets.filter(a=>a.kind==='image'),fonts=assets.filter(a=>a.kind==='font')
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const t=e.target as HTMLElement|null;if(t?.matches('input,textarea,select')||t?.isContentEditable||!props.selected)return;const s=e.shiftKey?10:1,c=props.selected.config,x=num(c.x,0),y=num(c.y,0),z=num(c.zIndex,1);if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();props.onDeleteBlock(props.selected.id)}else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='d'){e.preventDefault();props.onDuplicateBlock(props.selected.id)}else if(e.key==='ArrowLeft'){e.preventDefault();props.onSaveBlock(props.selected.id,{x:Math.max(0,x-s)})}else if(e.key==='ArrowRight'){e.preventDefault();props.onSaveBlock(props.selected.id,{x:x+s})}else if(e.key==='ArrowUp'){e.preventDefault();props.onSaveBlock(props.selected.id,{y:Math.max(0,y-s)})}else if(e.key==='ArrowDown'){e.preventDefault();props.onSaveBlock(props.selected.id,{y:y+s})}else if((e.metaKey||e.ctrlKey)&&e.key===']'){e.preventDefault();props.onSaveBlock(props.selected.id,{zIndex:z+1})}else if((e.metaKey||e.ctrlKey)&&e.key==='['){e.preventDefault();props.onSaveBlock(props.selected.id,{zIndex:Math.max(1,z-1)})}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[props.selected,props.onSaveBlock,props.onDeleteBlock,props.onDuplicateBlock])
 const upload=async(file:File,kind:'image'|'font')=>{setUploading(true);try{const a=await uploadAsset(props.workspaceId,props.userId,file,kind);setAssets(v=>[a,...v]);if(kind==='font')await loadFontAsset(a)}catch(e){setAssetError(e instanceof Error?e.message:String(e))}finally{setUploading(false)}}
 return <div className="atlas-editor-rail"><div className="atlas-edit-rail-head"><div><span>EDITING</span><strong>{props.database?props.record?props.record.title:props.database.name:props.page.title}</strong></div><button onClick={props.onDone}>Done</button></div>
  {props.database&&<div className="atlas-context-strip"><Database/><div><strong>{props.record?'RECORD':'COLLECTION HOME'}</strong><span>{props.record?`This page is centered on ${props.record.title}.`:`This is the customizable home for ${props.database.name}. Design content stays on the page; data tools read or write real ${props.database.name} records.`}</span></div></div>}
  <div className="atlas-edit-tabs"><button className={tab==='add'?'active':''} onClick={()=>setTab('add')}><Plus/>Add</button><button className={tab==='selected'?'active':''} onClick={()=>setTab('selected')}><MousePointer2/>Selected</button><button className={tab==='data'?'active':''} onClick={()=>setTab('data')}><Database/>Data</button><button className={tab==='layers'?'active':''} onClick={()=>setTab('layers')}><Layers/>Layers</button><button className={tab==='templates'?'active':''} onClick={()=>setTab('templates')}><LayoutTemplate/>Templates</button><button className={tab==='assets'?'active':''} onClick={()=>setTab('assets')}><Image/>Assets</button></div>
  <div className="atlas-edit-scroll">{tab==='add'&&<AddPanel onAdd={props.onAdd} database={props.database}/>} {tab==='selected'&&<SelectedPanel {...props} images={images} fonts={fonts}/>} {tab==='data'&&<CollectionDataPanel page={props.page} database={props.database} databases={props.databases} onOpenData={props.onOpenData}/>} {tab==='layers'&&<LayersPanel layers={ordered} selected={props.selected} onSelect={props.onSelectBlock} onPatch={props.onSaveBlock} onDelete={props.onDeleteBlock} onDuplicate={props.onDuplicateBlock}/>} {tab==='templates'&&<TemplatePanel page={props.page} blocks={props.blocks} databases={props.databases} database={props.database}/>} {tab==='assets'&&<AssetsPanel images={images} fonts={fonts} uploading={uploading} error={assetError} upload={upload} onDelete={async a=>{await deleteAsset(a);setAssets(v=>v.filter(x=>x.id!==a.id))}}/>}</div>
 </div>
}

function AddPanel({onAdd,database}:{onAdd:(t:PageBlockType)=>void;database:DatabaseType|null}){return <><div className="atlas-editor-explain"><strong>Add to this canvas</strong><span>Design content lives only on this page. Data elements show or calculate real collection information.</span></div><PanelTitle>Design content</PanelTitle><div className="atlas-add-grid"><Add icon={<Heading/>} label="Heading" onClick={()=>onAdd('heading')}/><Add icon={<Type/>} label="Text" onClick={()=>onAdd('text')}/><Add icon={<Quote/>} label="Callout" onClick={()=>onAdd('callout')}/><Add icon={<Image/>} label="Image" onClick={()=>onAdd('image')}/><Add icon={<MousePointer2/>} label="Button" onClick={()=>onAdd('button')}/><Add icon={<Minus/>} label="Divider" onClick={()=>onAdd('divider')}/><Add icon={<Square/>} label="Section" onClick={()=>onAdd('section')}/></div><PanelTitle>{database?`${database.name} data`:'Connected data'}</PanelTitle>{database&&<p className="atlas-helper">These start connected to {database.name} because you are on its collection home. You can change the source later.</p>}<div className="atlas-add-grid"><Add icon={<Database/>} label="Records view" onClick={()=>onAdd('database_view')}/><Add icon={<Palette/>} label="Metric" onClick={()=>onAdd('metric')}/><Add icon={<Palette/>} label="Progress" onClick={()=>onAdd('progress')}/></div><PanelTitle>Widgets</PanelTitle><div className="atlas-add-grid"><Add icon={<Square/>} label="Widget library" onClick={()=>onAdd('widget')}/></div><p className="atlas-helper">Need to add an actual book, episode, expense, ritual, or other record? Use the Data tab instead.</p></>}
function Add({icon,label,onClick}:{icon:ReactNode;label:string;onClick:()=>void}){return <button className="atlas-add-tile" onClick={onClick}>{icon}<span>{label}</span></button>}
function PanelTitle({children}:{children:ReactNode}){return <div className="atlas-edit-section-title">{children}</div>}

function SelectedPanel(props:Props&{images:AtlasAsset[];fonts:AtlasAsset[]}){const b=props.selected;if(!b)return <PageInspector {...props}/>;const c=b.config,save=(p:Patch)=>props.onSaveBlock(b.id,p),isText=['heading','text','callout'].includes(b.type),bound=String(c.databaseId||''),boundDb=props.databases.find(d=>d.id===bound),context=c.systemBinding==='page_title'?'PAGE TITLE':c.systemBinding==='page_cover'?'PAGE COVER':b.type==='property'?'CURRENT RECORD':(['database_view','metric'].includes(b.type)||bound)?'CONNECTED DATA':'PAGE CONTENT';return <div className="atlas-design-panel"><div className="atlas-binding-identity"><small>{context}</small><strong>{labelFor(b)}</strong><span>{context==='PAGE CONTENT'?'This exists only on this page.':context==='CONNECTED DATA'?`This reads from ${boundDb?.name||'a collection'}.`:context==='CURRENT RECORD'?`This shows information from ${props.record?.title||'the current record'}.`:'This is part of the page itself.'}</span></div><div className="atlas-selected-actions-wide"><button onClick={()=>props.onDuplicateBlock(b.id)}><Copy/>Duplicate</button><button onClick={()=>props.onDeleteBlock(b.id)}><Trash2/>Delete</button></div>
 {isText&&<><PanelTitle>Content</PanelTitle><label className="atlas-control"><span>Text</span><textarea value={c.systemBinding==='page_title'?props.page.title:String(c.text||'')} onChange={e=>save({text:e.target.value})}/></label><p className="atlas-helper">Double-click the words on the canvas to type there directly.</p></>}
 <PanelTitle>Position & size</PanelTitle><div className="atlas-control-grid four">{[['X','x'],['Y','y'],['W','width'],['H','height']].map(([l,k])=><Control key={k} label={l}><input type="number" value={num(c[k],k==='width'?320:k==='height'?140:0)} onChange={e=>save({[k]:+e.target.value})}/></Control>)}</div><div className="atlas-control-grid two"><Control label="Rotation"><input type="number" value={num(c.rotation,0)} onChange={e=>save({rotation:+e.target.value})}/></Control><Control label="Layer"><input type="number" value={num(c.zIndex,1)} onChange={e=>save({zIndex:+e.target.value})}/></Control></div><div className="atlas-layer-actions"><button onClick={()=>save({zIndex:Math.max(1,...props.blocks.map(x=>num(x.config.zIndex,1)))+1})}>To front</button><button onClick={()=>save({zIndex:num(c.zIndex,1)+1})}><ArrowUp/>Forward</button><button onClick={()=>save({zIndex:Math.max(1,num(c.zIndex,1)-1)})}><ArrowDown/>Backward</button><button onClick={()=>save({zIndex:1})}>To back</button></div>
 <PanelTitle>Appearance</PanelTitle><div className="atlas-control-grid two"><Control label="Background"><input type="color" value={color(c.background,'#ffffff')} onChange={e=>save({background:e.target.value})}/></Control><Control label="Text"><input type="color" value={color(c.textColor,'#211e1a')} onChange={e=>save({textColor:e.target.value})}/></Control></div><div className="atlas-lock-row"><button onClick={()=>save({locked:!c.locked})}>{c.locked?<Lock/>:<Unlock/>}{c.locked?'Locked':'Unlocked'}</button><button onClick={()=>save({hidden:!c.hidden})}>{c.hidden?<EyeOff/>:<Eye/>}{c.hidden?'Hidden':'Visible'}</button></div>
 {isText&&<><PanelTitle>Typography</PanelTitle><Control label="Font"><select value={String(c.fontFamily||'Georgia, serif')} onChange={e=>save({fontFamily:e.target.value})}><option value="Georgia, serif">Georgia</option><option value="Arial, sans-serif">Arial</option>{props.fonts.map(f=><option key={f.id} value={String(f.metadata?.family||f.name)}>{f.name}</option>)}</select></Control><div className="atlas-control-grid two"><Control label="Size"><input type="number" value={num(c.fontSize,b.type==='heading'?40:17)} onChange={e=>save({fontSize:+e.target.value})}/></Control><Control label="Weight"><input type="number" step="100" min="100" max="900" value={num(c.fontWeight,400)} onChange={e=>save({fontWeight:+e.target.value})}/></Control></div><div className="atlas-align-row"><button onClick={()=>save({textAlign:'left'})}><AlignLeft/></button><button onClick={()=>save({textAlign:'center'})}><AlignCenter/></button><button onClick={()=>save({textAlign:'right'})}><AlignRight/></button></div></>}
 {b.type==='database_view'&&<CanvasCardSidebar config={c} databases={props.databases} save={save}/>} 
 {b.type==='metric'&&<><PanelTitle>Data source</PanelTitle><Control label="Count records from"><select value={String(c.databaseId||'')} onChange={e=>save({databaseId:e.target.value})}>{props.databases.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Control></>}
 {b.type==='property'&&props.record&&<><PanelTitle>Record data</PanelTitle><Control label="Shows property"><select value={String(c.fieldId||'__title__')} onChange={e=>save({fieldId:e.target.value})}><option value="__title__">Record title</option>{props.fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Control></>}
 {b.type==='widget'&&<><PanelTitle>Widget</PanelTitle><WidgetSettings config={c} databases={props.databases} save={save}/></>}
 {b.type==='image'&&props.images.length>0&&<><PanelTitle>Replace image</PanelTitle><div className="atlas-asset-mini-grid">{props.images.slice(0,12).map(a=><button key={a.id} onClick={()=>save({url:a.public_url||''})}><img src={a.public_url||''} alt=""/></button>)}</div></>}
 </div>}

function PageInspector(props:Props){return <div className="atlas-design-panel"><div className="atlas-binding-identity"><small>PAGE</small><strong>{props.database?`${props.database.name} collection home`:props.page.title}</strong><span>{props.database?`This canvas is the customizable home for ${props.database.name}. Decorative elements do not become records automatically.`:'Click an object to edit it, or change the canvas itself here.'}</span></div><PanelTitle>Canvas</PanelTitle><div className="atlas-control-grid two"><Control label="Background"><input type="color" value={color(props.page.settings?.background,'#fbfaf7')} onChange={e=>props.onSavePageSettings({background:e.target.value})}/></Control><Control label="Text default"><input type="color" value={color(props.page.settings?.textColor,'#211e1a')} onChange={e=>props.onSavePageSettings({textColor:e.target.value})}/></Control></div><Control label="Canvas height"><input type="number" min="600" value={num(props.page.settings?.canvasHeight,1100)} onChange={e=>props.onSavePageSettings({canvasHeight:+e.target.value})}/></Control><PanelTitle>Page pieces</PanelTitle><div className="atlas-control-grid two"><button className="atlas-data-primary" onClick={props.onAddPageTitle}>Add page title</button><button className="atlas-data-primary" onClick={props.onAddPageCover}>Add cover</button></div>{props.database&&<><PanelTitle>{props.database.name} data</PanelTitle><p className="atlas-helper">Use the Data tab to quick-add records and decide exactly what fields this collection tracks.</p><button className="atlas-data-primary" onClick={props.onOpenData}><Database/>Open all records</button></>}</div>}

function LayersPanel({layers,selected,onSelect,onPatch,onDelete,onDuplicate}:{layers:PageBlock[];selected:PageBlock|null;onSelect:(id:string|null)=>void;onPatch:(id:string,p:Patch)=>void;onDelete:(id:string)=>void;onDuplicate:(id:string)=>void}){return <div className="atlas-layer-list">{layers.map(l=><div key={l.id} className={`atlas-layer-row ${selected?.id===l.id?'active':''}`}><button className="atlas-layer-main" onClick={()=>onSelect(l.id)}><span>{labelFor(l)}</span><small>{l.config.databaseId?'data-linked':'page content'}</small></button><button onClick={()=>onPatch(l.id,{hidden:!l.config.hidden})}>{l.config.hidden?<EyeOff/>:<Eye/>}</button><button onClick={()=>onDuplicate(l.id)}><Copy/></button><button onClick={()=>onDelete(l.id)}><Trash2/></button></div>)}</div>}
function AssetsPanel({images,fonts,uploading,error,upload,onDelete}:{images:AtlasAsset[];fonts:AtlasAsset[];uploading:boolean;error:string;upload:(f:File,k:'image'|'font')=>void;onDelete:(a:AtlasAsset)=>void}){return <div><PanelTitle>Upload</PanelTitle><label className="atlas-upload-button"><Upload/>{uploading?'Uploading…':'Upload image'}<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'image')}/></label><label className="atlas-upload-button"><Upload/>Upload font<input hidden type="file" accept=".ttf,.otf,.woff,.woff2" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'font')}/></label>{error&&<p className="atlas-asset-error">{error}</p>}<PanelTitle>Images</PanelTitle><div className="atlas-asset-mini-grid">{images.map(a=><div key={a.id}><img src={a.public_url||''} alt=""/><button onClick={()=>onDelete(a)}><Trash2/></button></div>)}</div><PanelTitle>Fonts</PanelTitle>{fonts.map(f=><div key={f.id} className="atlas-asset-row"><span>{f.name}</span><button onClick={()=>onDelete(f)}><Trash2/></button></div>)}</div>}
function Control({label,children}:{label:string;children:ReactNode}){return <label className="atlas-control"><span>{label}</span>{children}</label>}
function labelFor(b:PageBlock){if(b.config.systemBinding==='page_title')return'Page title';if(b.config.systemBinding==='page_cover')return'Page cover';if(b.type==='database_view')return String(b.config.title||'Records view');if(b.type==='widget')return String(b.config.widgetType||'Widget').replaceAll('_',' ');return b.type.replaceAll('_',' ')}
function num(v:unknown,d:number){const n=Number(v);return Number.isFinite(n)?n:d}
function color(v:unknown,d:string){const s=String(v||d);return /^#[0-9a-f]{6}$/i.test(s)?s:d}
