import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { AlignCenter, AlignLeft, AlignRight, ArrowDown, ArrowUp, ChevronDown, Copy, Database, Eye, EyeOff, FileAudio, FileText, Heading, Image, Layers, LayoutTemplate, Lock, Minus, MousePointer2, Palette, Plus, Quote, Square, Trash2, Type, Unlock, Upload, X } from 'lucide-react'
import { deleteAsset, getAssets, getAssetUsageCount, loadFontAsset, uploadAsset, type AtlasAsset } from '../lib/assets'
import type { Database as DatabaseType, Field, Page, PageBlock, PageBlockType, RecordRow } from '../types'
import TemplatePanel from './TemplatePanel'
import WidgetSettings from './WidgetSettings'
import CanvasCardSidebar from './CanvasCardSidebar'

type Patch = Record<string, unknown>
type Tab = 'add' | 'layers' | 'templates' | 'assets'
type Props = { workspaceId:string; userId:string; page:Page; blocks:PageBlock[]; selected:PageBlock|null; databases:DatabaseType[]; database:DatabaseType|null; record:RecordRow|null; fields:Field[]; layoutLocked:boolean; onAdd:(type:PageBlockType)=>void; onInsertAsset:(asset:AtlasAsset)=>void; onAddPageTitle:()=>void; onAddPageCover:()=>void; onSelectBlock:(id:string|null)=>void; onSaveBlock:(id:string,patch:Patch)=>void; onDeleteBlock:(id:string)=>void; onDuplicateBlock:(id:string)=>void; onSavePage:(patch:Partial<Page>)=>void; onSavePageSettings:(patch:Patch)=>void; onOpenData:()=>void; onRefresh:()=>Promise<void>|void }

export default function EditorSidebar(props:Props){
 const [tab,setTab]=useState<Tab|null>(null),[inspectorOpen,setInspectorOpen]=useState(false),[assets,setAssets]=useState<AtlasAsset[]>([]),[assetError,setAssetError]=useState(''),[uploading,setUploading]=useState(false)
 useEffect(()=>{getAssets(props.workspaceId).then(setAssets).catch(e=>setAssetError(e instanceof Error?e.message:String(e)))},[props.workspaceId])
 useEffect(()=>{const open=()=>setInspectorOpen(true);window.addEventListener('atlas-open-inspector',open);return()=>window.removeEventListener('atlas-open-inspector',open)},[])
 const ordered=useMemo(()=>[...props.blocks].sort((a,b)=>num(b.config.zIndex,1)-num(a.config.zIndex,1)),[props.blocks])
 const images=assets.filter(a=>a.kind==='image'),fonts=assets.filter(a=>a.kind==='font')
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const t=e.target as HTMLElement|null;if(t?.matches('input,textarea,select')||t?.isContentEditable||!props.selected)return;if(props.layoutLocked)return;const s=e.shiftKey?10:1,c=props.selected.config,x=num(c.x,0),y=num(c.y,0),z=num(c.zIndex,1);if(e.key==='Delete'||e.key==='Backspace'){
   if(props.selected.type==='database_view'&&String(c.mode||'gallery')==='canvas'){
    e.preventDefault();const selectedElementId=String(c.canvasCardSelectedElementId||'__card__');if(selectedElementId!=='__card__'&&c.canvasCardTemplate&&typeof c.canvasCardTemplate==='object'){const template=c.canvasCardTemplate as {elements?:Array<{id?:string}>};if(Array.isArray(template.elements))props.onSaveBlock(props.selected.id,{canvasCardTemplate:{...template,elements:template.elements.filter(el=>String(el.id)!==selectedElementId)},canvasCardSelectedElementId:'__card__'})}return
   }
   e.preventDefault();props.onDeleteBlock(props.selected.id)
  }else if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='d'){e.preventDefault();props.onDuplicateBlock(props.selected.id)}else if(e.key==='ArrowLeft'){e.preventDefault();props.onSaveBlock(props.selected.id,{x:Math.max(0,x-s)})}else if(e.key==='ArrowRight'){e.preventDefault();props.onSaveBlock(props.selected.id,{x:x+s})}else if(e.key==='ArrowUp'){e.preventDefault();props.onSaveBlock(props.selected.id,{y:Math.max(0,y-s)})}else if(e.key==='ArrowDown'){e.preventDefault();props.onSaveBlock(props.selected.id,{y:y+s})}else if((e.metaKey||e.ctrlKey)&&e.key===']'){e.preventDefault();props.onSaveBlock(props.selected.id,{zIndex:z+1})}else if((e.metaKey||e.ctrlKey)&&e.key==='['){e.preventDefault();props.onSaveBlock(props.selected.id,{zIndex:Math.max(1,z-1)})}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[props.selected,props.layoutLocked,props.onSaveBlock,props.onDeleteBlock,props.onDuplicateBlock])
 const upload=async(file:File,kind:'image'|'audio'|'font'|'file')=>{setUploading(true);try{const a=await uploadAsset(props.workspaceId,props.userId,file,kind);setAssets(v=>[a,...v]);if(kind==='font')await loadFontAsset(a)}catch(e){setAssetError(e instanceof Error?e.message:String(e))}finally{setUploading(false)}}
 const toggle=(next:Tab)=>setTab(current=>current===next?null:next)
 return <><nav className="atlas-tool-rail" aria-label="Workspace tools"><button className={tab==='add'?'active':''} onClick={()=>toggle('add')}><Plus/><span>Add</span></button><button className={tab==='layers'?'active':''} onClick={()=>toggle('layers')}><Layers/><span>Layers</span></button><button className={tab==='assets'?'active':''} onClick={()=>toggle('assets')}><Image/><span>Assets</span></button><button className={tab==='templates'?'active':''} onClick={()=>toggle('templates')}><LayoutTemplate/><span>Library</span></button></nav>{tab&&<aside className="atlas-workspace-toolbox" aria-label="Build toolbox"><div className="atlas-edit-rail-head"><div><span>BUILD</span><strong>{tab}</strong></div><button onClick={()=>setTab(null)} aria-label="Close toolbox"><X/></button></div><div className="atlas-edit-scroll">{tab==='add'&&<AddPanel onAdd={props.onAdd} database={props.database}/>} {tab==='layers'&&<LayersPanel layers={ordered} selected={props.selected} onSelect={props.onSelectBlock} onPatch={props.onSaveBlock} onDelete={props.onDeleteBlock} onDuplicate={props.onDuplicateBlock}/>} {tab==='templates'&&<TemplatePanel page={props.page} blocks={props.blocks} databases={props.databases} database={props.database} onRefresh={props.onRefresh}/>} {tab==='assets'&&<AssetsPanel assets={assets} uploading={uploading} error={assetError} upload={upload} onInsert={props.onInsertAsset} onDelete={async a=>{const uses=await getAssetUsageCount(a.id);const message=uses?`This asset is used by ${uses} page element(s). Delete anyway? Existing elements will stop displaying it.`:`Delete “${a.name}” from the workspace library?`;if(!window.confirm(message))return;await deleteAsset(a);setAssets(v=>v.filter(x=>x.id!==a.id))}}/>}</div></aside>}{inspectorOpen&&<aside className="atlas-context-inspector" aria-label="Object inspector"><div className="atlas-inspector-heading"><span>INSPECTOR</span><strong>{props.selected?labelFor(props.selected):'Page'}</strong><button onClick={()=>setInspectorOpen(false)} aria-label="Close inspector"><X/></button></div><div className="atlas-edit-scroll"><SelectedPanel {...props} images={images} fonts={fonts}/></div></aside>}</>
}

function AddPanel({onAdd,database}:{onAdd:(t:PageBlockType)=>void;database:DatabaseType|null}){return <><div className="atlas-editor-explain"><strong>Add to this page</strong><span>Compose freely. Content stays separate from structured database values.</span></div><PanelTitle>Content</PanelTitle><div className="atlas-add-grid"><Add icon={<Heading/>} label="Heading" onClick={()=>onAdd('heading')}/><Add icon={<Type/>} label="Text" onClick={()=>onAdd('text')}/><Add icon={<FileText/>} label="Document" onClick={()=>onAdd('document')}/><Add icon={<Quote/>} label="Callout" onClick={()=>onAdd('callout')}/><Add icon={<Minus/>} label="Divider" onClick={()=>onAdd('divider')}/></div><PanelTitle>Media</PanelTitle><div className="atlas-add-grid"><Add icon={<Image/>} label="Image" onClick={()=>onAdd('image')}/><Add icon={<FileAudio/>} label="Audio" onClick={()=>onAdd('audio')}/><Add icon={<FileText/>} label="File" onClick={()=>onAdd('file')}/></div><PanelTitle>Data</PanelTitle><div className="atlas-add-grid"><Add icon={<Database/>} label="Database view" onClick={()=>onAdd('database_view')}/>{database&&<Add icon={<Palette/>} label="Property" onClick={()=>onAdd('property')}/>}<Add icon={<Palette/>} label="Metric" onClick={()=>onAdd('metric')}/><Add icon={<Palette/>} label="Progress" onClick={()=>onAdd('progress')}/></div><PanelTitle>Layout & utility</PanelTitle><div className="atlas-add-grid"><Add icon={<Square/>} label="Section" onClick={()=>onAdd('section')}/><Add icon={<MousePointer2/>} label="Button" onClick={()=>onAdd('button')}/><Add icon={<Square/>} label="Widget" onClick={()=>onAdd('widget')}/></div></>}
function Add({icon,label,onClick}:{icon:ReactNode;label:string;onClick:()=>void}){return <button className="atlas-add-tile" onClick={onClick}>{icon}<span>{label}</span></button>}
function PanelTitle({children}:{children:ReactNode}){return <div className="atlas-edit-section-title">{children}</div>}

function SelectedPanel(props:Props&{images:AtlasAsset[];fonts:AtlasAsset[]}){
 const b=props.selected;if(!b)return <PageInspector {...props} />
 if(b.type==='database_view')return <RecordsViewPanel {...props} block={b}/>
 const c=b.config,save=(p:Patch)=>props.onSaveBlock(b.id,p),isText=['heading','text','callout'].includes(b.type),bound=String(c.databaseId||''),boundDb=props.databases.find(d=>d.id===bound),context=c.systemBinding==='page_title'?'PAGE TITLE':c.systemBinding==='page_cover'?'PAGE COVER':b.type==='property'?'CURRENT RECORD':(['metric'].includes(b.type)||bound)?'CONNECTED DATA':'PAGE CONTENT'
 return <div className="atlas-design-panel"><div className="atlas-binding-identity"><small>{context}</small><strong>{labelFor(b)}</strong><span>{context==='PAGE CONTENT'?'This exists only on this page.':context==='CONNECTED DATA'?`This reads from ${boundDb?.name||'a collection'}.`:context==='CURRENT RECORD'?`This shows information from ${props.record?.title||'the current record'}.`:'This is part of the page itself.'}</span></div><div className="atlas-selected-actions-wide"><button onClick={()=>props.onDuplicateBlock(b.id)}><Copy/>Duplicate</button><button onClick={()=>props.onDeleteBlock(b.id)}><Trash2/>Delete</button></div>
 {isText&&<><PanelTitle>Content</PanelTitle><label className="atlas-control"><span>Text</span><textarea value={c.systemBinding==='page_title'?props.page.title:String(c.text||'')} onChange={e=>save({text:e.target.value})}/></label><p className="atlas-helper">Double-click the words on the canvas to type there directly.</p></>}
 <PanelTitle>Position & size</PanelTitle><PositionControls config={c} blocks={props.blocks} save={save}/>
 <PanelTitle>Appearance</PanelTitle><div className="atlas-control-grid two"><Control label="Background"><input type="color" value={color(c.background,'#ffffff')} onChange={e=>save({background:e.target.value})}/></Control><Control label="Text"><input type="color" value={color(c.textColor,'#211e1a')} onChange={e=>save({textColor:e.target.value})}/></Control></div>
 <VisibilityControls config={c} save={save}/>
 {isText&&<><PanelTitle>Typography</PanelTitle><Control label="Font"><select value={String(c.fontFamily||'Georgia, serif')} onChange={e=>save({fontFamily:e.target.value})}><option value="Georgia, serif">Georgia</option><option value="Arial, sans-serif">Arial</option>{props.fonts.map(f=><option key={f.id} value={String(f.metadata?.family||f.name)}>{f.name}</option>)}</select></Control><div className="atlas-control-grid two"><Control label="Size"><input type="number" value={num(c.fontSize,b.type==='heading'?40:17)} onChange={e=>save({fontSize:+e.target.value})}/></Control><Control label="Weight"><input type="number" step="100" min="100" max="900" value={num(c.fontWeight,400)} onChange={e=>save({fontWeight:+e.target.value})}/></Control></div><div className="atlas-align-row"><button onClick={()=>save({textAlign:'left'})}><AlignLeft/></button><button onClick={()=>save({textAlign:'center'})}><AlignCenter/></button><button onClick={()=>save({textAlign:'right'})}><AlignRight/></button></div></>}
 {b.type==='metric'&&<><PanelTitle>Data source</PanelTitle><Control label="Count records from"><select value={String(c.databaseId||'')} onChange={e=>save({databaseId:e.target.value})}>{props.databases.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Control></>}
 {b.type==='property'&&props.record&&<><PanelTitle>Record data</PanelTitle><Control label="Shows property"><select value={String(c.fieldId||'__title__')} onChange={e=>save({fieldId:e.target.value})}><option value="__title__">Record title</option>{props.fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Control></>}
 {b.type==='widget'&&<><PanelTitle>Widget</PanelTitle><WidgetSettings config={c} databases={props.databases} save={save}/></>}
 {b.type==='image'&&props.images.length>0&&<><PanelTitle>Replace image</PanelTitle><div className="atlas-asset-mini-grid">{props.images.slice(0,12).map(a=><button key={a.id} onClick={()=>save({url:a.public_url||''})}><img src={a.public_url||''} alt=""/></button>)}</div></>}
 </div>
}

function RecordsViewPanel(props:Props&{block:PageBlock}){const b=props.block,c=b.config,save=(p:Patch)=>props.onSaveBlock(b.id,p);return <div className="atlas-design-panel atlas-records-view-panel"><div className="atlas-binding-identity"><small>RECORDS VIEW</small><strong>{labelFor(b)}</strong><span>Choose how existing database records appear here. Drag cards inside Canvas Cards; drag the block itself only from its outer selection frame.</span></div><div className="atlas-selected-actions-wide"><button onClick={()=>props.onDuplicateBlock(b.id)}><Copy/>Duplicate</button><button onClick={()=>props.onDeleteBlock(b.id)}><Trash2/>Delete</button></div><CanvasCardSidebar config={c} databases={props.databases} save={save}/><Disclosure title="Block on page"><PositionControls config={c} blocks={props.blocks} save={save}/><VisibilityControls config={c} save={save}/></Disclosure></div>}

function PositionControls({config,blocks,save}:{config:Patch;blocks:PageBlock[];save:(p:Patch)=>void}){return <><div className="atlas-control-grid four">{[['X','x'],['Y','y'],['W','width'],['H','height']].map(([l,k])=><Control key={k} label={l}><input type="number" value={num(config[k],k==='width'?320:k==='height'?140:0)} onChange={e=>save({[k]:+e.target.value})}/></Control>)}</div><div className="atlas-control-grid two"><Control label="Rotation"><input type="number" value={num(config.rotation,0)} onChange={e=>save({rotation:+e.target.value})}/></Control><Control label="Layer"><input type="number" value={num(config.zIndex,1)} onChange={e=>save({zIndex:+e.target.value})}/></Control></div><div className="atlas-layer-actions"><button onClick={()=>save({zIndex:Math.max(1,...blocks.map(x=>num(x.config.zIndex,1)))+1})}>To front</button><button onClick={()=>save({zIndex:num(config.zIndex,1)+1})}><ArrowUp/>Forward</button><button onClick={()=>save({zIndex:Math.max(1,num(config.zIndex,1)-1)})}><ArrowDown/>Backward</button><button onClick={()=>save({zIndex:1})}>To back</button></div></>}
function VisibilityControls({config,save}:{config:Patch;save:(p:Patch)=>void}){return <div className="atlas-lock-row"><button onClick={()=>save({locked:!config.locked})}>{config.locked?<Lock/>:<Unlock/>}{config.locked?'Locked':'Unlocked'}</button><button onClick={()=>save({hidden:!config.hidden})}>{config.hidden?<EyeOff/>:<Eye/>}{config.hidden?'Hidden':'Visible'}</button></div>}
function Disclosure({title,children}:{title:string;children:ReactNode}){return <details className="atlas-editor-disclosure atlas-block-disclosure"><summary><span>{title}</span><ChevronDown/></summary><div className="atlas-editor-disclosure-body">{children}</div></details>}

function PageInspector(props:Props){return <div className="atlas-design-panel"><div className="atlas-binding-identity"><small>PAGE</small><strong>{props.database?`${props.database.name} collection home`:props.page.title}</strong><span>{props.database?`This canvas is the customizable home for ${props.database.name}. Edit the database itself from the main Data navigation.`:'Click an object to edit it, or change the canvas itself here.'}</span></div><PanelTitle>Page appearance</PanelTitle><div className="atlas-control-grid two"><Control label="Background"><input type="color" value={color(props.page.settings?.background,'#fbfaf7')} onChange={e=>props.onSavePageSettings({background:e.target.value})}/></Control><Control label="Default text"><input type="color" value={color(props.page.settings?.textColor,'#211e1a')} onChange={e=>props.onSavePageSettings({textColor:e.target.value})}/></Control></div><Control label="Canvas height"><input type="number" min="600" value={num(props.page.settings?.canvasHeight,1100)} onChange={e=>props.onSavePageSettings({canvasHeight:+e.target.value})}/></Control><PanelTitle>Page pieces</PanelTitle><div className="atlas-control-grid two"><button className="atlas-data-primary" onClick={props.onAddPageTitle}>Add page title</button><button className="atlas-data-primary" onClick={props.onAddPageCover}>Add cover</button></div>{props.database&&<><PanelTitle>Database</PanelTitle><p className="atlas-helper">This editor controls how data appears on this page. Open the collection itself when you want to change records or fields.</p><button className="atlas-data-primary" onClick={props.onOpenData}><Database/>Open {props.database.name}</button></>}</div>}

function LayersPanel({layers,selected,onSelect,onPatch,onDelete,onDuplicate}:{layers:PageBlock[];selected:PageBlock|null;onSelect:(id:string|null)=>void;onPatch:(id:string,p:Patch)=>void;onDelete:(id:string)=>void;onDuplicate:(id:string)=>void}){return <div className="atlas-layer-list">{layers.map(l=><div key={l.id} className={`atlas-layer-row ${selected?.id===l.id?'active':''}`}><button className="atlas-layer-main" onClick={()=>onSelect(l.id)}><span>{labelFor(l)}</span><small>{l.config.databaseId?'data-linked':'page content'}</small></button><button onClick={()=>onPatch(l.id,{hidden:!l.config.hidden})}>{l.config.hidden?<EyeOff/>:<Eye/>}</button><button onClick={()=>onDuplicate(l.id)}><Copy/></button><button onClick={()=>onDelete(l.id)}><Trash2/></button></div>)}</div>}
function AssetsPanel({assets,uploading,error,upload,onInsert,onDelete}:{assets:AtlasAsset[];uploading:boolean;error:string;upload:(f:File,k:'image'|'audio'|'font'|'file')=>void;onInsert:(a:AtlasAsset)=>void;onDelete:(a:AtlasAsset)=>void}){const choices:Array<['image'|'audio'|'font'|'file',string,string]>=[['image','Upload image','image/*'],['audio','Upload audio','.mp3,.m4a,.wav,.ogg,audio/*'],['file','Upload file','.pdf,.zip,.doc,.docx,.txt,application/*'],['font','Upload font','.ttf,.otf,.woff,.woff2']];return <div><PanelTitle>Workspace library</PanelTitle><p className="atlas-helper">Upload once, then place the same asset on multiple pages.</p>{choices.map(([kind,label,accept])=><label key={kind} className="atlas-upload-button"><Upload/>{uploading?'Uploading…':label}<input hidden type="file" accept={accept} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],kind)}/></label>)}{error&&<p className="atlas-asset-error">{error}</p>}<PanelTitle>Reusable assets</PanelTitle><div className="atlas-reusable-assets">{assets.filter(a=>a.kind!=='emoji').map(a=><div key={a.id} className="atlas-asset-row">{a.kind==='image'&&<img src={a.public_url||''} alt=""/>}<span><strong>{a.name}</strong><small>{a.kind}</small></span>{a.kind!=='font'&&<button onClick={()=>onInsert(a)}>Place</button>}<button title="Delete asset" onClick={()=>onDelete(a)}><Trash2/></button></div>)}</div></div>}
function Control({label,children}:{label:string;children:ReactNode}){return <label className="atlas-control"><span>{label}</span>{children}</label>}
function labelFor(b:PageBlock){if(b.config.systemBinding==='page_title')return'Page title';if(b.config.systemBinding==='page_cover')return'Page cover';if(b.type==='database_view')return String(b.config.title||'Records view');if(b.type==='widget')return String(b.config.widgetType||'Widget').replaceAll('_',' ');return b.type.replaceAll('_',' ')}
function num(v:unknown,d:number){const n=Number(v);return Number.isFinite(n)?n:d}
function color(v:unknown,d:string){const s=String(v||d);return /^#[0-9a-f]{6}$/i.test(s)?s:d}
