import { useState } from 'react'
import { Palette, X } from 'lucide-react'
import TemplatePanel from './TemplatePanel'
import type { Database, Page, PageBlock } from '../types'

const themes=[{name:'Paper',background:'#fbfaf7',textColor:'#211e1a'},{name:'Linen',background:'#eee7dc',textColor:'#2d251f'},{name:'Sage',background:'#edf0e9',textColor:'#253027'},{name:'Ink',background:'#302a31',textColor:'#fff9f2'}]
export default function PageCustomization({page,blocks,databases,database,onSaveSettings,onRefresh,onClose}:{page:Page;blocks:PageBlock[];databases:Database[];database:Database|null;onSaveSettings:(patch:Record<string,unknown>)=>void;onRefresh:()=>Promise<void>|void;onClose:()=>void}){
 const[tab,setTab]=useState<'appearance'|'templates'>('appearance')
 return <aside className="page-customization" aria-label="Page customization"><header><div><span>PAGE</span><strong>Customize</strong></div><button onClick={onClose} aria-label="Close page customization"><X/></button></header><nav><button className={tab==='appearance'?'active':''} onClick={()=>setTab('appearance')}>Theme & appearance</button><button className={tab==='templates'?'active':''} onClick={()=>setTab('templates')}>Templates</button></nav><div className="page-customization-scroll">{tab==='appearance'?<><div className="page-panel-title">Theme</div><div className="page-theme-grid">{themes.map(theme=><button key={theme.name} style={{background:theme.background,color:theme.textColor}} onClick={()=>onSaveSettings({background:theme.background,textColor:theme.textColor})}><Palette/><span>{theme.name}</span></button>)}</div><div className="page-panel-title">Page appearance</div><label>Background<input type="color" value={safeColor(page.settings.background,'#fbfaf7')} onChange={event=>onSaveSettings({background:event.target.value})}/></label><label>Default text<input type="color" value={safeColor(page.settings.textColor,'#211e1a')} onChange={event=>onSaveSettings({textColor:event.target.value})}/></label><label>Background image<input value={String(page.settings.backgroundImage||'')} placeholder="Image URL" onBlur={event=>onSaveSettings({backgroundImage:event.target.value})}/></label><label>Canvas height<input type="number" min="600" value={Number(page.settings.canvasHeight||1100)} onChange={event=>onSaveSettings({canvasHeight:+event.target.value})}/></label></>:<><p className="page-template-safety">Templates can be added alongside your existing composition. Replacing existing layout remains an explicit confirmed action inside each template.</p><TemplatePanel page={page} blocks={blocks} databases={databases} database={database} onRefresh={onRefresh}/></>}</div></aside>
}
function safeColor(value:unknown,fallback:string){const text=String(value||'');return /^#[0-9a-f]{6}$/i.test(text)?text:fallback}
