import { Navigate, Outlet, Route, Routes, useLocation } from 'react-router-dom'
import { createContext, useContext, useEffect, useState } from 'react'
import type { Session, User } from '@supabase/supabase-js'
import { configured, supabase } from './lib/supabase'
import { ensureWorkspace } from './lib/data'
import type { Workspace } from './types'
import AuthPage from './pages/AuthPage'; import DashboardPage from './pages/DashboardPage'; import DatabasePage from './pages/DatabasePage'; import RecordPage from './pages/RecordPage'; import DesignHubPage from './pages/DesignHubPage'; import SurfaceDesignerPage from './pages/SurfaceDesignerPage'; import WorkspacePage from './pages/WorkspacePage'; import AppShell from './components/AppShell'
interface AppContextValue{user:User;workspace:Workspace;refreshWorkspace:()=>Promise<void>};const AppContext=createContext<AppContextValue|null>(null);export function useAppContext(){const v=useContext(AppContext);if(!v)throw new Error('useAppContext must be used inside AppContext');return v}
function ProtectedLayout(){const[session,setSession]=useState<Session|null>(null),[workspace,setWorkspace]=useState<Workspace|null>(null),[authReady,setAuthReady]=useState(false),[workspaceLoading,setWorkspaceLoading]=useState(false),[workspaceError,setWorkspaceError]=useState<string|null>(null);const location=useLocation();const loadWorkspace=async(u:User)=>setWorkspace(await ensureWorkspace(u.id,u.email));useEffect(()=>{let m=true;supabase.auth.getSession().then(({data,error})=>{if(!m)return;if(error)setWorkspaceError(error.message);setSession(data.session);setAuthReady(true)});const{data:a}=supabase.auth.onAuthStateChange((_e,s)=>{if(m){setSession(s);setAuthReady(true)}});return()=>{m=false;a.subscription.unsubscribe()}},[]);useEffect(()=>{let c=false;if(!authReady)return;if(!session?.user){setWorkspace(null);setWorkspaceLoading(false);return}setWorkspaceLoading(true);ensureWorkspace(session.user.id,session.user.email).then(w=>{if(!c)setWorkspace(w)}).catch(e=>{if(!c)setWorkspaceError(e instanceof Error?e.message:String(e))}).finally(()=>{if(!c)setWorkspaceLoading(false)});return()=>{c=true}},[authReady,session?.user?.id]);if(!configured)return <MissingConfig/>;if(!authReady||workspaceLoading)return <div className="center-screen"><div className="spinner"/><p>Opening your workspace…</p></div>;if(!session?.user)return <Navigate to="/login" replace state={{from:location.pathname}}/>;if(workspaceError)return <div className="center-screen setup-card"><h1>Atlas could not open your workspace</h1><p>{workspaceError}</p></div>;if(!workspace)return null;return <AppContext.Provider value={{user:session.user,workspace,refreshWorkspace:()=>loadWorkspace(session.user)}}><AppShell><Outlet/></AppShell></AppContext.Provider>}
function MissingConfig(){return <div className="center-screen setup-card"><div className="brand-mark">A</div><h1>Atlas Studio needs Supabase</h1><p>Add your project URL and publishable key. Run schema.sql, 002_revamp.sql, then 003_pages.sql.</p></div>}
export default function App(){return <Routes><Route path="/login" element={<AuthPage/>}/><Route element={<ProtectedLayout/>}><Route path="/" element={<DashboardPage/>}/><Route path="/page/:pageId" element={<WorkspacePage/>}/><Route path="/database/:databaseId" element={<DatabasePage/>}/><Route path="/database/:databaseId/record/:recordId" element={<RecordPage/>}/><Route path="/database/:databaseId/design" element={<DesignHubPage/>}/><Route path="/database/:databaseId/design/:surface" element={<SurfaceDesignerPage/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
